### ISSUE TITLE
Feature request: Image Upload

### ISSUE THREAD

**Issue by philippeowagner** [GitJournal/GitJournal#10]
1. Upload selected file to repository, eg. into an asset directory.
2. Link using markdown `![]( image .png)` in note. 

---
> Please vote on this issue with a 👍reaction. It's one of the primary mechanisms used to prioritize issues.

**Comment by igsol** [comment]
Absence of image support on the MarkDown pages is a real showstopper for me to use the application fully.

**Comment by vHanda** [comment]
It seems that this is one of the most voted issues, so I would like to start tackling it next week. However, I'm not sure exactly how to go about it. The main thing blocking me is the lack of a rich text editor in GitJournal.

So far my plan is the following -
* Add an image bottom app bar. The idea is to function similar to how Google Keep functions, it will open up a dialog which would allow to either choose from your gallery or take a photo with the camera.
* This photo would then be saved in either the save folder as the note or in a specific folder. This will be configurable. The filename which the note is saved with should ideally also be configurable.
* In the markdown editor, I'll add a button which allows you to add an image - This will show a dialog with 3 options - "An existing photo in the repo", "A photo from the gallery" or "Take a new photo". The relevant markdown will then be added to the editor.
* The FS view proposed in #91, should also be implemented and it should show the images present in the repo, and allow you to move/rename them.

These are quite a number of changes that would be required. Please let me know if I'm forgetting something else that would be required for this, or if anyone has any other ideas.

**Comment by vHanda** [comment]
I have not added this - "Add an image icon in the bottom app bar. The idea is to function similar to how Google Keep functions, it will open up a dialog which would allow to either choose from your gallery or take a photo with the camera.".

It made the bottom app bar look way too crowded. If someone wants that option please open a new bug, and I'll implement it + allow the bottom app icons to be configured.

**Comment by AronMav** [comment]
Hi. I'd like to see in next relises new format image-link how in Obsidian.md
![[media/Pasted image 6.png]]

**Comment by vHanda** [comment]
> Hi. I'd like to see in next relises new format image-link how in Obsidian.md
> ![[media/Pasted image 6.png]]

Hey Aron. Could you please point me to the documentation on what this does differently than the standard markdown image format?

**Comment by AronMav** [comment]
> > Hi. I'd like to see in next relises new format image-link how in Obsidian.md
> > ![[media/Pasted image 6.png]]
> 
> Hey Aron. Could you please point me to the documentation on what this does differently than the standard markdown image format?

Standart image format: https://www.markdownguide.org/basic-syntax/#images
 ![Tux, the Linux mascot](/assets/images/tux.png)

Obsidian.md format (screen documentation): http://prntscr.com/u2onb6  
![[media/Pasted image 6.png]]

**Comment by ddelange** [comment]
Would people :+1: to see a github/gitlab specific feature to upload media to their server instead of checking the files in, or :-1: is it out of scope?

[Example](https://gist.github.com/ddelange/aa4a97f5d8a9d9e3625d405161aac9b2) media links generated using file upload dialog or drag & drop in the GitHub issue editor view

Pros:
- Much smaller repository size
- More scalable / performant
Cons:
- Increased complexity (https caching, ...?)
- Vendor lock-in
- ...?

**Comment by vHanda** [comment]
> Would people 👍 to see a github/gitlab specific feature to upload media to their server instead of checking the files in, or 👎 is it out of scope?
> 
> [Example](https://gist.github.com/ddelange/aa4a97f5d8a9d9e3625d405161aac9b2) media links generated using file upload dialog or drag & drop in the GitHub issue editor view
> 
> Pros:
> 
> * Much smaller repository size
> * More scalable / performant
> 
> Cons:
> 
> * Increased complexity (https caching, ...?)
> * Vendor lock-in
> * ...?

It would probably be best to file a new issue about this. Also, maybe mention which API one could use to implement this.

Another option could be to use Git LFS, I think there is another issue tracking it.
