### ISSUE TITLE
feature request : Create/Maintain jekyll blog from home screen

### ISSUE THREAD

**Issue by sachinsshetty** [GitJournal/GitJournal#100]
For new bloggers(users), 
provide option to choose from curated list of jekyll template blogs.
Ex. [so-simple-theme](https://github.com/mmistakes/so-simple-theme)

New users,

1. can create github/gitlab accounts in App 
2. Choose jekyll template 
3. Pre-fill required information based on User Input
4. Setup blog and get notifications from site about deployment(failure/success)
5. Update blog with required template file from jekyll

P.S
My daily workflow is to write articles/poems on my diary/phone. At end of the day, update blog from laptop.  The app helps to reduce time from phone to laptop. 
The app is perfect for my use case, was planning to implement a basic app for the same
 [jekyll blog: gaganyatri.com](https://github.com/sachinsshetty/gaganyatri.com)

**Comment by vHanda** [comment]
Hey sachinsshetty.

My goal with this project is to build a kickass notes editing app integrated with Git. Right now it's only focused on Markdown + Git, but I'm open to supporting more file formats. However, my idea is not to create an app geared towards creating/managing Jekyll/Hugo/etc blogs. That's simply not something that interests me. Even if I could generate revenue from that.

Supporting most of the features you've mentioned would take this app in a completely different direction. I'm open to adding features which would help with the stated goal and also help with managing Jekyll/Hugo blogs. One such example could be templates [#20].

Fortunately for you, the app is completely open source, so if you want you can use the existing code base and create a new app focused on Jekyll blogs. I'll be happy to help you with re-using GitJournal's code.

**Comment by vHanda** [comment]
Also, regarding (1), GitHub as far as I know doesn't offer an API to create a new account. So this just isn't possible.
