### ISSUE TITLE
[WIP] Where to discuss GitJournal development?

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#103]
Even though I'm the main developer in GitJournal, I often email a few users to ask for some feedback during development. I would like an easier and more scalable manner than IMing and emailing individual users. The desired feedback is usually centered around - 

1. Note workflows - The way each user manages their notes and how GitJournal fits into their particular workflow and with other tools is extremely individualistic. It helps to be able to talk about a new feature and get feedback from users.

2. Design Mockups - I have major design concerns with GitJournal, and want to revamp certain key screens - such as note editing (in order to clearly display the folder). For this I would like feedback from some users, before implementing it. It's much faster and effective if I can share an image over implementing that interface.

Ideas on where to discuss this -

**Requirements -**
* Ability to respond via emails
* Publicly searchable and indexable
* WebUI (Maybe?)

**Possible Solutions -** 
1. GitHub Issues - This could be a useful place, however this would include a lot more noise from all the other GitHub issues.

2. Classical Mailing List - I setup a classical mailman3 server. It doesn't have a Web UI for others to respond/post, but I'm not sure how important that is. It does come with a [decent UI](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/) for reading. This also reduces the dependency on GitHub, which in general is a good thing, as GitHub is not accessible in all parts of the world. Based on usage statistics GitJournal is used quite a bit in China.

A classical mailing list would include some infrastructure costs, but it shouldn't be more than a few dollars a month. That's acceptable to me.

This issue is to gather feedback about the proposed solutions, and other potential solutions.

**Comment by groovenectar** [comment]
Trying to think of what would be the drawbacks of actually just using GitHub issues for this...

I recall GitLab having some additional collaboration tools as well...

**Comment by vHanda** [comment]
> Trying to think of what would be the drawbacks of actually just using GitHub issues for this...

I wonder how many people get notified when a new issue is opened. I know I get notified. I think it's related to the watching the repo. For some reason open an "issue" for some feedback about which icon seems better, seems a bit much. Maybe it's just a matter of getting used to it.

**Comment by groovenectar** [comment]
Yep I think that watching the repo enables notifications, will have to tinker with it though

GitLab has Kanban boards:
https://about.gitlab.com/stages-devops-lifecycle/kanban-boards/

**Comment by aepound** [comment]
Gitlab does seem to have some nice integrations. I think that you can integrate Mattermost/Slack/Google Hangouts chat into gitlab very easily.  I actually haven't used them much, but I know that they are there. I'm unsure about how authentication and permissions work, but it's possible that it could be limited based on roles in the project.

I'm not sure if github has the same, as I'm not as familiar with github...
If you were to migrate to GitLab, then you could set this repo up as a mirror. 

I wonder if there is a way to move issues between the 2. I.e. issues submitted on github get copied over to gitlab or vice-versa...

**Comment by vHanda** [comment]
Okay, so after researching a bit. Here in my proposed plan -

* I'll continue to use GitHub for development. Issues are tracked over here. And since GitHub also offers Kanban boards, I can use them to track sub-projects like 'Google Keep Compatibility'.

* For user feedback and sharing design mockups, I've decided to use a [sub-reddit](https://www.reddit.com/r/GitJournal/) . It doesn't exactly allow posting/responding via emails, but being on reddit gives GitJournal great network efforts. Also it's threading mechanism is quite nice. Additionally, since my goal for GitJournal is for it to be used by non-developers, having a mailing list, isn't ideal.

* For more development related concerns - I think I'll just use github issues, with a clear feedback wanted tag.

* For more realtime chat - I'm going to continue with Matrix for now.
