### ISSUE TITLE
Error updating after folder name edit

### ISSUE THREAD

**Issue by zacdemi** [GitJournal/GitJournal#108]
Device: IOS iphone SE 
Version: 13.3.1
Reproduce: Edit folder name -> open folder -> click cloud to update.
![IMG_0225](https://user-images.githubusercontent.com/8942619/79592793-27424a80-80a0-11ea-9d39-db012b4561c8.png)

**Comment by vHanda** [comment]
Oh this is awesome. I can reliably reproduce it.

Thank you for reporting this!

**Comment by zacdemi** [comment]
You're welcome!
