### ISSUE TITLE
Feature Request: work with Keybase private git host

### ISSUE THREAD

**Issue by keegoid** [GitJournal/GitJournal#11]
Would love to get this working with private repos on Keybase. Not sure how that would work though. Private Keybase git repos already work with Github Desktop. Is it possible for it to work on Android? The clone URL looks like keybase://private/username/repo

**Comment by vHanda** [comment]
I've looked a bit into it, and it looks like a substantial amount of work.

There is already a keyboase client for [Android/iOS](https://github.com/keybase/client). That could be adapted to integrate into GitJournal, but it'll take a while. I can leave this bug open for a while incase someone else wants to get around to it, but it's not something I plan on tackling for a long time.

**Comment by vHanda** [comment]
I just learnt that the Keybase Server is [closed source](https://github.com/keybase/client/issues/6374), and therefore won't be implementing support for it. I'm closing this issue.

Patches are, of course, welcome.

I do plan to figure out a way to store notes in an encrypted manner in Git.
