### ISSUE TITLE
Problems with the Pro 

### ISSUE THREAD

**Issue by ataliba** [GitJournal/GitJournal#110]
I had a problem and needed to clear the app's data.
I opted for Pro to help development.
The problem is that after clearing the data the app accuses me that I don't have the Pro. When I try to purchase again, Google Play warns me that I already have it activated.
Any tips on how to try to solve this? or is it really a bug?

**Comment by vHanda** [comment]
Hi. Thank you so much for supporting development.

I'm afraid I was a bit shortsighted and didn't think of this case at all. I'll try to fix this ASAP.
