### ISSUE TITLE
Default state of markdown editor for new notes

### ISSUE THREAD

**Issue by mipro98** [GitJournal/GitJournal#119]
When the default state of the markdown editor under "Editor Settings" is "View", creating a new note with the markdown editor causes it also to open up in view mode on a blank note.

It would be good if the default state of the markdown editor for new notes was always edit.

**Comment by vHanda** [comment]
Eeeep. This is how it should have been. I didn't realize I broke it as I probably didn't test it enough. Let me fix it right now.
