### ISSUE TITLE
Day One Classic to GitJournal script

### ISSUE THREAD

**Issue by sanzoghenzo** [GitJournal/GitJournal#12]
Hi,
first of all, thanks a lot for this app!

I just converted my old journal entries from Day One Classic (mac os) and Narrate (android) to GitJournal, [here](https://gist.github.com/sanzoghenzo/fb5011aa566292a4eb1b62fc7a4a50cc) you can find the python script I wrote to do the conversion, in case anyone has the same need.

I kept the metadata (tags, location, weather) into the yaml header, just in case...

Happy GitJournaling!

**Comment by vHanda** [comment]
Hello.

Thanks. This is awesome. I'm going to add it to the README.
