### ISSUE TITLE
Filename extension consistency

### ISSUE THREAD

**Issue by scottrosenquist** [GitJournal/GitJournal#122]
I don't know when the change happened, but I've started seeing files generated by Git Journal that do not have the .md file extension. So I renamed all the other entries in my journal repo to maintain consistency, and now the ones I renamed are not showing up.

I then created two new brand new entries from my desktop. One with a .md extension, one without. Only the one with the .md extension showed up in Git Journal.

But every new Git Journal entry I make is missing the .md file extension. Yet it still shows up in Git Journal. It's all very confusing.

**Comment by vHanda** [comment]
That is very weird. I haven't touched the filename code in a while. Could you please try adding another new note and then use the report a bug button. It will send me the app logs which may contain some helpful info.

**Comment by scottrosenquist** [comment]
My Bug Report button does not seem to do anything...I press it, and nothing happens.

**Comment by vHanda** [comment]
Wow. Something is very wrong.

Could you please share what device and OS you're using?

**Comment by scottrosenquist** [comment]
iPhone 11, iOS 13.4.1, Git Journal 1.46.0+1118.

**Comment by vHanda** [comment]
Ok. I don't save the logs on iOS anyway. So this wouldn't have helped.

So two possible options -
1. You reinstall the app and hope this magically starts working again.
2. I implement some kind of dev console in the app which displays the logs and works in both iOS and Android. It's been on my Todo list for a while, but this raises the priority. I imagine I could have this done before the end of the week, and then let's assume Apple will take a day or so to approve it.

I'll keep you updated during the week as I implement it.

**Comment by scottrosenquist** [comment]
Hey, reinstalling the app helped. Both all my journal entries written from both Git Journal and my linux machines are showing up. Thankfully, since everything is hosted on git, I have zero worries of ever losing data.
