### ISSUE TITLE
Unsynced changes indicator

### ISSUE THREAD

**Issue by scottrosenquist** [GitJournal/GitJournal#123]
It would be nice if the cloud checkmark icon would indicate if there are changes in the app that have not been synced. It'd be handy for anyone, like myself, who likes to manually sync changes.

I don't know whether to open another issue for this, but it would be also nice if, when you open up an existing entry, but have not changed anything, the top left close icon could be an x instead of a checkmark? If you make changes, the checkmark would indicate that you are about to save them, or if you didn't mean to edit it, you could discard your changes.

**Comment by vHanda** [comment]
I'm working on the first one. It'll soon show the number of changes.

The second suggested change also makes a lot of sense. Will do.
