### ISSUE TITLE
Changing Github Author credentials requires restart of iPad app

### ISSUE THREAD

**Issue by UnreachableCode** [GitJournal/GitJournal#130]
Your operating system name and version.
iOS 31.3.1

Any details about your local setup that might be helpful in troubleshooting.
Changed from the default GitJournal author to my Github account.

Detailed steps to reproduce the bug.

1. I changed the author name and email, and made a few edits to some notes. 
2. I then noticed they were still making commits under 'GitJournal'. 
3. I checked the settings, and they had retained my username and email. 
4. So I restarted the app, and then made another edit. 
5. The correct author now appeared. 

Is there a way to make the change take effect automatically?

**Comment by vHanda** [comment]
Thanks for reporting the issue. I'll release a new iOS version in a few days.
