### ISSUE TITLE
Hidden spaces

### ISSUE THREAD

**Issue by scottrosenquist** [GitJournal/GitJournal#131]
I don't know if this is a new change, or just something I never noticed, but when I type a space, it does not appear until I follow it with another character. I'm on iOS btw. v1.50.0+1223. (Though I'm feeling like I should get my old Pixel out so I can test on both platforms...)

**Comment by vHanda** [comment]
You're right. This happens sometimes. It's an underlying bug in Flutter. Let me try to link to that bug report. It's super annoying.

**Comment by vHanda** [comment]
I'll try to cherry pick to fix in the stable branch, and compile it with a custom Flutter engine.

**Comment by BWPanda** [comment]
I've noticed this too, quite annoying. Is the same bug also responsible for the extra space at the end of each line...?

**Comment by vHanda** [comment]
> I've noticed this too, quite annoying. Is the same bug also responsible for the extra space at the end of each line...?

What bug is this?

**Comment by BWPanda** [comment]
When I edit a note, if I click at the end of a line, the cursor is one space away from the last character (i.e., there's a space at the end of each line). But I'm having trouble reproducing this now... So ignore me, don't want to hijack this issue.
