### ISSUE TITLE
Font size and maybe font type should be selectable

### ISSUE THREAD

**Issue by MelBourbon** [GitJournal/GitJournal#133]
As a user I want to change the font size in editing as well as viewing mode to be able to adjust to my used screen and improve readability. 

Also consider, as a user I may want to switch to another font in viewing mode.

**Comment by vHanda** [comment]
Hey Mel. Definitely.

I'm going to close this as it's a duplicate of #35. Would you mind voting on that issue? I'm trying to target tags this week, but maybe I can make this a priority for the next week!

**Comment by MelBourbon** [comment]
Thanks. May have not searched correctly before I opened this issue. I voted on #35
