### ISSUE TITLE
Notes without .md extension are being ignored

### ISSUE THREAD

**Issue by danfelipe** [GitJournal/GitJournal#135]
I discovered this scenario by trying to add a note committed from another source into the journal repository and expecting to see the entry on my phone.

Description:
This code block checks for the extension of the note to decide if ignore or not the file. However, the file is not being saved with the .md extension. 

```
var note = Note(this, fsEntity.path);
if (!note.filePath.toLowerCase().endsWith('.md')) {
  Log.v("Ignoring file ${fsEntity.path}");
  continue;
}
```

Expected: 
Notes/Files follow the same rules during creation and during retrieval.
Scenario 1: A note can be pulled to the local list if it matches the note signature (naming convention, header tag, extension)
Scenario 2: If selecting an existing repository, the existent notes are sync'd into my new environment.

Workaround:
Rename the file to [filename].md and works as expected.

PS: A really nice project. Keep up the good work!

**Comment by vHanda** [comment]
Hey Daniel. I'm a bit confused. Currently when saving a note/renaming a note via the app, it should always have a `.md` extension. Is that not the case for you?

So for scenario 1 - You would like the ability to load other files which do not end with a .md based on a controllable criteria. Is that correct? 

I'm afraid I don't understand Scenario 2. Could you please elaborate? Maybe with an example.

**Comment by danfelipe** [comment]
Hey @vHanda thanks for the prompt response, see below the image explaining better, I don't think it matters but I'm using a Galaxy S8+. I wonder if it's only for my current settings, I'm using timestamps for file names. 

![firefox_bWK4nSUp6r](https://user-images.githubusercontent.com/25276659/81775904-b2560b00-94bb-11ea-95dc-7540c909a676.png)

Scenario #2 happens if I try to install the app and point to an existent repository with notes (think a new phone, but I want to use the existent repository). In this case all notes are ignored except those with the .md extension.

Let me know if you need more info to replicate.
