### ISSUE TITLE
Create Folder dialogue create/discard incorrect way around

### ISSUE THREAD

**Issue by adonald** [GitJournal/GitJournal#139]
## Repro steps:

1. Menu > Folders > "+" (create new) > Type in folder name
2. Select "create" - actually discards
3. Select "discard" - actually creates

## System info

- Android v10
- Sony Xperia 5
- GitJournal 1.52.0+1298

**Comment by vHanda** [comment]
Thanks for reporting this. I've been trying to make the app translatable and mixed up the strings. I'll make a new release Android release today with this fix.
