### ISSUE TITLE
Add an easy way to link to another Note

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#142]
Currently in order to link to another note one has to remember the filename of that note. It would be nice if one could open a dialog and select the note, and it accordingly inserts the correct markdown.

---
> Please vote on this issue with a 👍reaction. It's one of the primary mechanisms used to prioritize issues.

**Comment by aisbergde** [comment]
Notes also could get an UUID in the metadata and the UUID could be used to link. This will not work outside GitJournal but this would allow to rename note files without loosing the link.

I still hope that I could use GitJournal on Android together with on the desktop: https://github.com/notable/notable

Would be fine if they could use the same syntax to link other notes.

**Comment by craignicol** [comment]
Either that or autocomplete based on title or filename?

**Comment by vHanda** [comment]
I'm closing this in favor of #210 and #176. With those two, it should be easy to link to other notes.
