### ISSUE TITLE
Checklist notes - last item deletion is being ignored

### ISSUE THREAD

**Issue by danfelipe** [GitJournal/GitJournal#148]
This is a bug I found recently. Please let me know if you need more info about this.

**Description:**
When deleting all the items from a checklist note, these change are being ignored. If there are more items, the delete process works as expected. 

I'm not attaching logs since there is nothing to see there about this scenario.

Installed app version: 1.53.0

**Steps to reproduce:**

**Step 1:** Create a note with multiple items.
![Step1](https://user-images.githubusercontent.com/25276659/82846193-ab64ca80-9eb5-11ea-8292-62e4ec28c471.png)

**Step 2:** Delete all items and save changes.
![Step2](https://user-images.githubusercontent.com/25276659/82846203-b61f5f80-9eb5-11ea-810d-05b361c6ae9b.png)

**Step 3:** Note is reverted to the last state, nothing to commit.
![Step3](https://user-images.githubusercontent.com/25276659/82846210-bae41380-9eb5-11ea-8bb3-83be399e69d5.png)

**Expected:**
Delete changes are detected similar to deleting when there are other entries on the checklist.

**Workaround:**
So far the workaround for me has been changing the view of the note to raw and manually deleting the content.
![Step4](https://user-images.githubusercontent.com/25276659/82846226-cafbf300-9eb5-11ea-9cea-b3e4b17f2e70.png)

This way changes are detected and I can commit a note without items as expected.
![Step5](https://user-images.githubusercontent.com/25276659/82846233-cf281080-9eb5-11ea-8476-3bda70fb1daa.png)

**Comment by vHanda** [comment]
Hey Dan.

Thank you for the extremely detailed bug report. It was very easy to reproduce. I'll make a new release (1.54) with the changes in a day or so.

**Comment by danfelipe** [comment]
Glad to help. Thanks for your quick turnaround!
