### ISSUE TITLE
iOS v1.55.0+1389 update issue

### ISSUE THREAD

**Issue by scottrosenquist** [GitJournal/GitJournal#159]
I just updated to the new version, and none of my entries as showing up. Luckily, because everything is in git, I'm not worried, and I'm sure I can reset the repo and get it working, but I still wanted to file this.

I took some screenshots of the error. The in-app logs are nice, but I only seem to be able to select one line at a time, not the whole thing. So I took screenshots.

![image](https://user-images.githubusercontent.com/6862371/83663427-d8406e00-a596-11ea-8f3b-8d198bce9a44.png)

![image](https://user-images.githubusercontent.com/6862371/83663464-de364f00-a596-11ea-8d81-70fb1cb2ad75.png)

![image](https://user-images.githubusercontent.com/6862371/83663633-ebebd480-a596-11ea-9cbd-ac50f250ac20.png)

**Comment by vHanda** [comment]
Damn. My crash reports also shows this mysteriously happening on some Android devices. I was hoping it was just an issue where Android was "accidentally" removing all the app data, but if it's happening on iOS as well.

Let me make a new release which prints out the contents of each folder. The errors logs indicate that the folder where the notes were saved no longer exists.

Maybe another thing I could do is if the folder has disappeared for some reason (I'll look for it more thoroughly, then I reset the app state, so you're forced to setup the git host again)

**Comment by scottrosenquist** [comment]
Reinstalling (obviously) helped, now I'm back up and journaling.

**Comment by vHanda** [comment]
Thanks Scott. This is one of those situations where I have no idea how this could happen. I'm glad all your notes were synced.

**Comment by scottrosenquist** [comment]
I just wanted to let you know this issue happened again on the update to 1.56.1+1407 on iOS.

**Comment by vHanda** [comment]
Thanks Scott.

The update for 1.56.1 is from Friday. It just took really long to get
approved. This bug is fixed in 1.57, I could reliably reproduce it. I'll
make a new release today and you'll get it .. hopefully soon?

**Comment by scottrosenquist** [comment]
Hey, no rush! I'm a software developer too, so I understand completely. I know what things can happen when developers rush. :wink:
