### ISSUE TITLE
Unable to create new notes directly from the All Notes View

### ISSUE THREAD

**Issue by danfelipe** [GitJournal/GitJournal#164]
[Update]
Updating text to remove all references to last update - unrelated. 

Hi @vHanda,
I'm having this unexpected behavior on the App. Please let me know if I can help with more details.

**Description:**
When trying to add new notes from the "All Notes" view (home screen for me), a gray square overlapping the whole typing area is shown. I can't switch/select folders or enter any text.

Installed app version: 1.56.0+1403

**Steps to reproduce:**
**Step1:** Click the "Create Note" button
![Step1](https://user-images.githubusercontent.com/25276659/83943117-52573980-a7c7-11ea-9085-a9a4cd37b401.jpg)

**Step2:** See the gray layout, it doesn't allow any edit on the new note.
![Step2](https://user-images.githubusercontent.com/25276659/83943128-7c106080-a7c7-11ea-8d79-171b8ff7645d.jpg)

**Step3:** There is not much information about the action on the logs.
![Step3](https://user-images.githubusercontent.com/25276659/83943138-8fbbc700-a7c7-11ea-98b8-d4de3f8b50e0.jpg)

**Expected:**
I can add a new note from the "All Notes" screen.

**Workaround:**
So far the workaround for me has been switching to a specific folder.
![Step4](https://user-images.githubusercontent.com/25276659/83943160-bc6fde80-a7c7-11ea-9a6c-04833644152b.jpg)

Then adding the note from there.
![Step5](https://user-images.githubusercontent.com/25276659/83943162-c396ec80-a7c7-11ea-8483-54af2d7aeba5.jpg)

**Comment by vHanda** [comment]
Hey Dan.

In the logs, there would be one line giving the settings. Could you please paste that?

**Comment by danfelipe** [comment]
Sure!
And apologies, I can't copy the whole section from the logs to paste it as a block of text, it needs to be entry per entry, which in this case would be an overkill. Will this screenshot work for you?

![log_settings](https://user-images.githubusercontent.com/25276659/83943509-d52dc380-a7ca-11ea-9188-8fe58a318aac.jpg)

**Comment by danfelipe** [comment]
Hey @vHanda,
I found what was happening 🤦‍♂️... I deleted the folder that was being used as default in the setting "Default Folder for new notes", so each time the app was creating a new note, it was pointing to (null). Switching to an existing folder fixed the issue. Not sure if you want to add a message or something in the app about this, or if the folder should be blocked from deletion if it's being used. From my perspective the issue is solved. 

Thanks for your help!

**Comment by vHanda** [comment]
No no. This is great stuff.

1. If you delete a folder, I should update the settings.
2. Allow logs to be more easily copied.

**Comment by danfelipe** [comment]
I can create two new issues to track these items as new requests if you prefer.

**Comment by vHanda** [comment]
Nah. It's fine.

These are both small things. Let's leave this open. I'll close it later
today as I fix both those things.
