### ISSUE TITLE
Custom YAML Metadata for all notes

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#168]
Allow the user to configure custom yaml metadata which is added by default to all notes.

Use case is to add 'draft: true', while writing blog posts.

**Comment by xplosionmind** [comment]
This could be a very nice way to use the app to edit on the go Jekyll websites hosted on GitHub pages, or Netlify etc.

Do you feel like I should open a dedicated issue about this?

**Comment by vHanda** [comment]
> This could be a very nice way to use the app to edit on the go Jekyll websites hosted on GitHub pages, or Netlify etc.
> 
> Do you feel like I should open a dedicated issue about this?

Hey. I'm sorry I don't follow. A dedicated issue for what exactly?

**Comment by xplosionmind** [comment]
I’m sorry if I didn’t explain myself very well, I meant an issue about better integration between GitJournal and Jekyll websites. Thus, not only improving YAML fromt matter by making it compatible with Jekyll’s one, but to understand th efile naming criteria and other Jekyll-related data.

**Comment by vHanda** [comment]
> I’m sorry if I didn’t explain myself very well, I meant an issue about better integration between GitJournal and Jekyll websites. Thus, not only improving YAML fromt matter by making it compatible with Jekyll’s one, but to understand th efile naming criteria and other Jekyll-related data.

Hey. Sorry about the delayed response.

I'm not sure what all features you have in mind, but please feel free to open new issues for each of them. For now - I'm focusing on making sure GitJournal is a great markdown based note taking application with Git Integration, but there is a large overlap between that and Jekyll websites :)

**Comment by xplosionmind** [comment]
Great. Thanks a lot!
