### ISSUE TITLE
The app stops responding when I turn on markdown preview

### ISSUE THREAD

**Issue by illus0r** [GitJournal/GitJournal#170]
## Environment

**App version:**    
1.57.0+1438

**Device information:**
<img src="https://user-images.githubusercontent.com/797993/86247459-299f4580-bbb5-11ea-9466-54a134a2f7f3.jpg" width="400">

## Description

**Expected behavior:**
When I press the eye icon while editing markdown, it should show preview of the page.

**Current behavior:**
It changes icon to a pencil and freezes, until I force quit the app

<img src="https://user-images.githubusercontent.com/797993/86247717-8ac71900-bbb5-11ea-906b-fd39768a6240.jpg" width="400">

## Steps to reproduce

1. Create markdown file
2. Fill in the title and text
3. Press eye icon
4. The app stops responding

**Comment by vHanda** [comment]
Hey. This is weird. Could you please reproduce it and then use the report a bug button? That should send me the debug logs which will help diagnose the issue.

**Comment by illus0r** [comment]
@vHanda, thank you! I've emailed

**Comment by feng1st** [comment]
same issue, hang a while when first open a note if the default state of markdown editor is set to View

**Comment by vHanda** [comment]
Hello. I think this might be cause of the backlinks view. I'm making a new release (1.58) with an 'Experimental Features' option in the Settings which can be used to disable the BackLinks viewer. Could you please try disable the backlinks and tell me if that fixes the issue?

**Comment by feng1st** [comment]
it's fixed after turn off the backlinks

**Comment by illus0r** [comment]
@vHanda thank you, after backlinks are disabled, preview mode works fine!

**Comment by vHanda** [comment]
This should be fixed even without switching off the backlinks with `1.59`
