### ISSUE TITLE
Markdown links in preview mode don't react when pressed

### ISSUE THREAD

**Issue by illus0r** [GitJournal/GitJournal#173]
## Environment

**App version:**  1.58.0+1470
**Device information:**
<img src="https://user-images.githubusercontent.com/797993/86247459-299f4580-bbb5-11ea-9466-54a134a2f7f3.jpg" width="400">

## Description

**Expected behavior:**
When I open markdown file a.md with content
```
---
title: A article
---

A

Links to B:
[B article](b)
[B article](b.md)

[Google](https://google.com)
```
 in preview mode, first two links should open b.md in preview mode. Last one should open google.com

**Current behavior:**
All links don't react when pressed:

<img src="https://user-images.githubusercontent.com/797993/86537127-ccc9c500-befd-11ea-9dad-79910df4e546.gif" width="400">

## Steps to reproduce

1. Create a.md and b.md in the same folder.
2. Open a.md and paste:
```
---
title: A article
---

A

Links to B:
[B article](b)
[B article](b.md)

[Google](https://google.com)
```

3. Open b.md and paste:
```
---
title: B article
---

B
```
4. Open a.md, switch to preview mode and press any links, they don't work.

**Comment by illus0r** [comment]
Wow, thanks so much! When do you plan to update it on Google play?

**Comment by vHanda** [comment]
Doing it now. Version 1.58.2, you should get it within a few hours.

**Comment by illus0r** [comment]
External links work now, cheers!

But local links are still broken. In the log I get:
```
{"t":1594107880094,"l":"i","msg":"Launching b.md"}
{"t":1594107880829,"l":"i","msg":"Launching b.md"}
{"t":1594107881321,"l":"i","msg":"Launching b.md"}
{"t":1594107881707,"l":"i","msg":"Launching b.md"}
{"t":1594107882107,"l":"i","msg":"Launching b.md"}
{"t":1594107882625,"l":"i","msg":"Launching b"}
{"t":1594107883101,"l":"i","msg":"Launching b"}
{"t":1594107883494,"l":"i","msg":"Launching b"}
{"t":1594107883785,"l":"i","msg":"Launching b"}
{"t":1594107884571,"l":"i","msg":"Launching https://google.com"}
```

v1.58.2+1479

**Comment by illus0r** [comment]
@vHanda thank you for the fix! When it will be possible to get update from Google Play?

**Comment by vHanda** [comment]
You should get it today or tomorrow. I made the new release a few hours ago.
