### ISSUE TITLE
HTTPS support for git repositories

### ISSUE THREAD

**Issue by harrybaumann** [GitJournal/GitJournal#179]
I just installed the iOS version and found out during setup that it's only possible to access a git repository via SSH. However, my git repo is only accessible via HTTPS and I cannot change that.

As it is a standard feature of many providers, **I suggest to implement HTTPS access to a git repository.**

Besides that, good work! :-)

**Comment by vHanda** [comment]
Hey Harry.

Could you please elaborate why only HTTPS is an option for you? I'm going to close this bug as a duplicate of #31, please vote on that issue.
