### ISSUE TITLE
Provide Folder support

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#18]
GitJournal should show folders within a Git repo, and not just a plain list of all notes.

**Comment by devoldski** [comment]
I have a tree of content that I work within and not being able to change working folders makes it hard for me to use gitjournal as much as I would like to

**Comment by vHanda** [comment]
With the next release `1.20`, we will have basic Folder support. You'll be able to manage your Notes within Folders, however you will not be able to add/remove/edit Folders.

I'm going to keep this issue open until that is also resolved.

You should receive version `1.20` within a few days. I want to test it far more thoroughly before shipping to all the users.

**Comment by vHanda** [comment]
Marking this as fixed. Only #37 still needs to be implemented.
