### ISSUE TITLE
iOS manual build fails with `Build input file cannot be found` error

### ISSUE THREAD

**Issue by k4biri** [GitJournal/GitJournal#184]
## Environment

**App version:**  master branch [9d00fda](https://github.com/GitJournal/GitJournal/commit/9d00fdac0671fe236a71d9d0c5cd0f3e404f4a63)  
**Device information:**
 - Dart 2.8.4
 - Flutter 1.17.5 stable 
 - Xcode Version 11.6
 - Pod 1.9.3

## Description

**Seems like something goes wrong with Manual iOS build:**

The build for iOS fails with the following error:
```
error: Build input file cannot be found: '/Users/johndoe/projects/GitJournal/ios/Runner/empty.swift' (in target 'Runner' from project 'Runner')
```
I also tried both New Build System and the Legacy Build System with no success either way.

## Steps to reproduce

1. Clone the project and choose the `master` branch.
2. Open the project in an Android Studio and try to run it while having an iPhone (iOS 13.4) connected and it fails. 
3. Run `flutter clean` in project dir.
4. Navigate to `project_dir/ios` and  run `pod install`.
5. Finally, Run `flutter build ios --debug --no-codesign`.

<details>
  <summary>Logs</summary>

`flutter doctor -v` output:

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-DE)
    • Flutter version 1.17.5 at /Users/johndoe/Development/flutter
    • Framework revision 8af6b2f038 (vor 4 Wochen), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
m
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/johndoe/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK evRuntime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All yd licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • fluppy  • ios • iOS 13.4

• No issues found!
```

[ios_manual_build_log.txt](https://github.com/GitJournal/GitJournal/files/4980333/ios_manual_build_log.txt)

</details>

**Comment by vHanda** [comment]
Hi. I fixed this particular issue yesterday with - https://github.com/GitJournal/GitJournal/commit/7918676c7aeef21918028b551e47d2921d462d19 , however GitJournal really isn't ready to be compiled by other people on iOS.

This - https://stackoverflow.com/questions/63072231/flutter-ios-plugin-with-custom-frameworks is blocking me.

 If I cannot solve the above problem, I'll document how exactly I build it on iOS - It's a mix of some system links and copying some libraries manually.

**Comment by vHanda** [comment]
I'm closing this bug as the particular issue has been fixed, but building on iOS is still a pain and not trivial. Please let me know if you would like the build instructions.

**Comment by k4biri** [comment]
Thank you so much for your info and the fix, however, it seems like there are still other build files that are missing.
For example, the following three files are avoiding the build to succeed with a similar error:
```
GitJournal/gj_common/gitjournal.c
GitJournal/gj_common/common.c
GitJournal/gj_common/keygen.c
```

**Comment by mvolpato** [comment]
> If I cannot solve the above problem, I'll document how exactly I build it on iOS - It's a mix of some system links and copying some libraries manually.

If this does not take too much of your time, it would be appreciated. I would like to contribute, but I cannot use Android emulators in my system.

**Comment by vHanda** [comment]
> > If I cannot solve the above problem, I'll document how exactly I build it on iOS - It's a mix of some system links and copying some libraries manually.
> 
> If this does not take too much of your time, it would be appreciated. I would like to contribute, but I cannot use Android emulators in my system.

I've now automated all of it. I just run the `scripts/build_ios.sh` file, and it does everything. I would put it up on the GitHub CI, but I couldn't figure out the code signing :(

Oh, and also firebase gives me strange compile errors, but this seems to be a problem with my specific machine, so I've been shipping the ios builds without any analytics.
