### ISSUE TITLE
FR: Set Root folder location

### ISSUE THREAD

**Issue by VKondakoff** [GitJournal/GitJournal#192]
Is there a way to set Root folder location (iCloud Drive)? 
![IMG_0201](https://user-images.githubusercontent.com/230824/88830430-9d456a00-d1d6-11ea-97d1-804e7cc36c96.jpeg)
I'm testing GJ 1.61.0+1538 on iPadOS14.
Thanks!

**Comment by vHanda** [comment]
Hello. No there currently isn't a way. There is issue #99 to allow moving it the SD card, but that wouldn't work on iOS. I'm really not sure what all options are available on iOS to break out of the sandbox.

Any help would be appreciated.

**Comment by VKondakoff** [comment]
Thanks! I changed the question to be a feature request.

**Comment by vHanda** [comment]
With `1.73` the notes can be saved in an external directory in Android, and there is some basic iCloud support - however it is buggy. I've opened https://github.com/GitJournal/GitJournal/issues/296 to track that.
