### ISSUE TITLE
iOS loses repo connection or access after force close

### ISSUE THREAD

**Issue by scottrosenquist** [GitJournal/GitJournal#195]
If I force close the app, or if it is closed due to memory management by the iOS, the next time I launch it is as if my repo is not set up.![image](https://user-images.githubusercontent.com/6862371/88841019-58580e00-d1ab-11ea-864d-55b51c0bf95e.png)![image](https://user-images.githubusercontent.com/6862371/88841033-5e4def00-d1ab-11ea-8dd0-b94e3b2515da.png)![image](https://user-images.githubusercontent.com/6862371/88841050-627a0c80-d1ab-11ea-99e4-1564b3ef490b.png)

**Comment by fmagin** [comment]
I can confirm that I lost my repo configuration twice yesterday. I use Android 10, so this is most likely not just an iOS issue. I am not sure what caused it, but I am on the same version, so it seems likely that it is related.

**Comment by vHanda** [comment]
Hi.

Apologies for the issue. I've fixed it in version 1.62. Apple emailed me an hour ago that the update is live, and on Android it was shipped yesterday.

Please update, and reopen this bug if it still happens.

Sorry for the trouble.

**Comment by fmagin** [comment]
Ah, I had to manually go to the play store page to update, it hadn't auto-updated yet.

Thank you for very much for writing and maintaining this app!
