### ISSUE TITLE
After the upgrade the settings were lost

### ISSUE THREAD

**Issue by ataliba** [GitJournal/GitJournal#199]
## Environment

**App version:**  1.6.1.0+1538
**Device information:** Multilaser M7s
 - OS name and version: Android 8.1 Go
 - Manufacturer: Multilaser
 - Model: M7s 

## Description

Após atualizar o aplicativo as configurações foram apagadas. Achei que fosse algum problema no meu dispositivo. 

Reconfigurei o aplicativo e após alguns minutos ao abrir novamente ele pedia para que eu configurasse novamente o repositório Git. 

Reconfigurei e novamente houve o problema conforme já falei no canal do Matrix. 

**Expected behavior:**

The settings made are saved by the application

**Current behavior:**

The settings made are not saved by the application

## Steps to reproduce

1. Upgrade  to the new version of GitJournal 
2. All the configs are lost 
3. Config again the app and the repository
4. Open after few minutes and the configuration is gone again

**Comment by vHanda** [comment]
Fixed in version `1.62`
