### ISSUE TITLE
crash when try to acces setting section

### ISSUE THREAD

**Issue by muhammadarif1** [GitJournal/GitJournal#2]
#### expected behavior
Users should be able to open the settings section so that users can manage whatever they want
#### actual behavior
when the user presses the settings option, this application crashes
#### bug recording
https://www.youtube.com/watch?v=vE92I9ZVVYg
sorry i can't find a logcat so i can't provide it

**Comment by vHanda** [comment]
Hi. Thanks a lot for reporting the bug.

Unfortunately, I cannot seem to reproduce it, and the youtube video isn't loading as well. Could you please provide me with you Phone Model and App Version? I can at least then try to reproduce it on an emulated version of that model.

**Comment by muhammadarif1** [comment]
My android model is 5.1 ,app version is latest version from playstote

**Comment by vHanda** [comment]
Hi. I've tried to run it on an emulated 5.1 phone and cannot seem to reproduce it.

How comfortable are you with Android development? I'm hoping you could provide me with the 'adb logs'. I can provide detailed instructions on how to do so, if you aren't aware.

**Comment by muhammadarif1** [comment]
you can provide a details instruction how to get a log

**Comment by vHanda** [comment]
Hi. I've rewritten most of the Settings screen. It should no longer crash, please feel to reopen the bug if it does.
