### ISSUE TITLE
Register on open collective

### ISSUE THREAD

**Issue by b3u** [GitJournal/GitJournal#202]
As long as you have 100+ stars on GitHub (:heavy_check_mark:), you can register and accept recurring or one-time donations. You can list supporters on the readme (they have an api endpoint) as an incentive to donate.

**Comment by b3u** [comment]
https://opencollective.com/create

**Comment by vHanda** [comment]
I was just registering for GitHub sponsors. Do you know if there is an advantage over open collective? Or should I just do both?

**Comment by b3u** [comment]
GitHub sponsors currently doesn't accept one-time donations

**Comment by vHanda** [comment]
> GitHub sponsors currently doesn't accept one-time donations

Thanks. Will do!

**Comment by vHanda** [comment]
Update: I've removed GitJournal from Open Collective. It's one more place to manage and post updates. For now one time donations can be made via paypal.

For recurring donations I'm using GitHub sponsors.
