### ISSUE TITLE
More advanced filename options

### ISSUE THREAD

**Issue by planetscripton** [GitJournal/GitJournal#205]
## Environment

**App version:**
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: Google
 - Model: Pixel 3xl

## Description

**What you'd like to happen:**
I'd like to be able to set more advanced filename options. I'm looking for: yyyy-mm-dd-title-of-the-note.md
This is to create a filename that is compatible with the Jekyll blogging platform

**Alternatives you've considered:**   
I could script the name change by pulling the title from the yaml frontmatter during my CI process. It's just messy.

**Images:**

**Comment by vHanda** [comment]
Closing this issue, as this will be resolved by https://github.com/GitJournal/GitJournal/issues/56
