### ISSUE TITLE
Allow customizing 'tags' yaml metadata key

### ISSUE THREAD

**Issue by planetscripton** [GitJournal/GitJournal#206]
## Environment

**App version:**
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: Google
 - Model: Pixel 3XL

## Description

**What you'd like to happen:**
I'd like to be able to set some custom yaml frontmatter items.

The specific ones I'm looking for are:
layout: post
date: yyyy-mm-dd HH:MM:ss TZ (instead of created)
categories: 

**Alternatives you've considered:**   
Manually type them in - but time consuming.

**Images:**

**Comment by b3u** [comment]
They're available for pro, I think.

**Comment by vHanda** [comment]
* Is `categories` supposed to be used instead of `tags`?
* The `modified` date can be configured to a few different options right now (in pro as b3u commented) - not the created. I can add that option.
* The `layout` part is definitely a duplicate for #168

**Comment by planetscripton** [comment]
> 
> * Is `categories` supposed to be used instead of `tags`?
> * The `modified` date can be configured to a few different options right now (in pro as b3u commented) - not the created. I can add that option.
> * The `layout` part is definitely a duplicate for #168 

For Jekyll, it uses categories, not tags.

Thanks for replying so quickly!

**Comment by jpatters** [comment]
I would actually like to see what @planetscripton  originally requested; the ability to add custom front master tags. I don’t just want to customize the built in ones. I want to be able to add my own.

**Comment by vHanda** [comment]
> I would actually like to see what @planetscripton originally requested; the ability to add custom front master tags. I don’t just want to customize the built in ones. I want to be able to add my own.

Hey Jordan. Would #168 cover your use case? I plan to implement it by providing a text box where you can add whatever you want, and that will get added to the YAML metadata for every new note.
