### ISSUE TITLE
RFC: Dropbox Sync

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#207]
I've received a number of low ratings on the Google Play Store, because of the lack of DropBox Support. These reviews are typically 1-2 stars and are quite disheartening.

I'm wondering if I should actually just add support for it. One would still have a local git repo, but every time you do a sync it would just make a new commit with all the changes.

I might just be overreacting to the negative reviews.

**Comment by AronMav** [comment]
I thint DropBox Support it's very good idea. This will increase the audience.

**Comment by ovichiro** [comment]
You probably are overreacting :) Some people give 1 star just to get noticed.
On the other hand, Dropbox support is not a bad idea, especially if it's done the way Joplin did it, by writing to the `/Apps/GitJournal/` folder. This way the app only requests and has access to that specific folder. This approach may be more interesting to privacy minded people, although I see it as a good approach in general (i.e. don't ask for more access than you need).

**Comment by Iglum** [comment]
I did just read [all reviews ](https://play.google.com/store/apps/details?id=io.gitjournal.gitjournal&hl=en&showAllReviews=true) on Google play and like this one star review, 

> No way to open files from local or cloud storage like Dropbox or OneDrive.

the person did not clearly read the description of 📗 GitJournal and the review is breaking the comment posting policy.
So i just mark it **Unhelpful** and hope it helps.

###  😠
Dropbox compromised my account once and it seems the company still is stuck in 2015 when it comes to features,design and the applications.

>  Dropbox
> 
> In mid-2012, Dropbox suffered a data breach which exposed the stored credentials of tens of millions of their customers. In August 2016, they forced password resets for customers they believed may be at risk. A large volume of data totalling over 68 million records was subsequently traded online and included email addresses and salted hashes of passwords (half of them SHA1, half of them bcrypt).
> 
> Breach date: 1 July 2012
> Date added to HIBP: 31 August 2016
> Compromised accounts: 68,648,009
> Compromised data: Email addresses, Passwords

**source** on [haveibeenpwned.com](https://haveibeenpwned.com/PwnedWebsites#Dropbox)

**Comment by vHanda** [comment]
In the end I've decided not to implement this. In the currently Android version, the notes can be stored in a directory which is accessible to other apps, and can therefore be synced with apps such as [AutoSync for DropBox](https://play.google.com/store/apps/details?id=com.ttxapps.dropsync&hl=en_US&gl=US)
