### ISSUE TITLE
Use "support" instead of "bug report" & "feedback"

### ISSUE THREAD

**Issue by binyamin** [GitJournal/GitJournal#209]
this way, users can simply contact the developer for whatever reason they want. Also, less items in the app drawer.

**Comment by vHanda** [comment]
Earlier I was sure this was a good idea, now I'm not too sure. Let me run it by a few other people

**Comment by vHanda** [comment]
In the end, I decided not to implement this, as the 'Bug' button attaches the debug logs, and in the future, I would like to provide a more automated form which takes screenshots and then posts it on GitHub as an Issue. Something similar to [Instabug](https://instabug.com/).
