### ISSUE TITLE
Need to click on 'Unlock Pro Version' to unlock pro on new devices when paid on another device

### ISSUE THREAD

**Issue by chris2fr** [GitJournal/GitJournal#211]
## Environment

**App version:**  Android store on Android 9
**Device information:**
 - OS name and version: Telcast TE30 Tablet
 - Manufacturer:
 - Model:

## Description

**Expected behavior:**

Subscription applies to all devices on account.

**Current behavior:**

Subscription does not allow "pro" features on second device by same owner in Play Store.

## Steps to reproduce

1. Install on phone
2. Subscribe
3. Install on tablet

**Comment by vHanda** [comment]
Could you please send me the debug logs? Use the report a bug button, that should generate an email with them attached.
