### ISSUE TITLE
Support number-only ISO filenames

### ISSUE THREAD

**Issue by craignicol** [GitJournal/GitJournal#216]
For Zettelkasten notes, files get a unique id from the current timestamp, which is just the ISO datetime without separators (i.e. 202008150909 instead of 2020-08-15 09:09) it would be nice if Gitjournal supported this default.

**Comment by craignicol** [comment]
@vHanda thanks for the update, just tried it on my Pixel, and or looks like setting the yyyymmsshhmmss option for filename is actually outputting iso1601?

**Comment by vHanda** [comment]
@craignicol : You're right. My fault. Fixing and making a new release (1.68)

**Comment by craignicol** [comment]
All good. Thank you.
