### ISSUE TITLE
Add YAML Metadata to the end of the note

### ISSUE THREAD

**Issue by benwalio** [GitJournal/GitJournal#223]
## Environment

**App version: 1.66.0+1654 pro**
**Device information:**
 - OS name and version: ios beta 14
 - Manufacturer: apple
 - Model: iphone XR

## Description

**What you'd like to happen:**

add a toggle on the metadata page to allow metadata to appear in the footer rather than in the header. it's nit-picky but the first line in the document is _theoretically_ supposed to be an h1 (https://cirosantilli.com/markdown-style-guide/#top-level-header). allowing the metadata to be stored in the footer helps preserve the commonmark standard there. 

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by vHanda** [comment]
As I started implementing this a while ago, it opened a huge can of worms of edge cases, and I therefore stopped. If enough people want this, I'll implement this.

**Comment by vHanda** [comment]
Sorry. I'm closing this as "wontfix".

This is complicating the code a lot and implementing it correctly requires handling a lot of edge cases. I rather not ship it in a broken way. The good news is that you can disable the YAML header completely, and most of GitJournal will work perfectly. I'm trying to ensure that all GitJournal features work with or without YAML.
