### ISSUE TITLE
Unable to connect to AWS CodeCommit

### ISSUE THREAD

**Issue by inkstain** [GitJournal/GitJournal#224]
## Environment

**App version:**  1.67.0+1678
**Device information:**
 - OS name and version: Android 8.1.0
 - Manufacturer:Blackberry
 - Model:KeyOne

## Description

When trying to do the initial commit from app in setting up a connection with CodeCommit, I receive an error `Failed Unknown Error`

**Expected behavior:**

Successful completion of account setup and commit.

**Current behavior:**

Error message as indicated

## Steps to reproduce

I created an IAM user and pre-created a repo (since it asks for the associated SSH URL) and have tried uploading the SSH keys that are generated into the IAM user settings but it is not connecting, I suspect due to how I am inputting the SSH URL

AWS provides the SSH URL as follows (obfuscating the final portion)

`ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/blah`

if I try preceding that URL with the IAM username followed by `@`, GitJournal does not allow me to get to the next step of the setup (stating that it must be an SSH URL), but if I provide the string as shown above it will allow me to get to the SSH key generation which I upload to the AWS IAM user's ssh keys but then when I proceed to commit in the app it just indicates

`Failed Unknown Error`

I had no problems whatsoever in setting up a test onto github but wanted to get this onto AWS instead (larger capacity in case it is needed). Not sure if this is really a bug or if it is an insufficiently understood feature :) but either way I would appreciate a bit of guidance

I did review the debug log but it it didn't give any more detail on the nature of the failure than the above.

Please let me know if you need any additional details. Currently on the dummy github account but can nuke and return to AWS once I have some action items to try.

thx for the great app, I am looking forward to digging more into it!

**Comment by vHanda** [comment]
Hey. Give me a few days. I remember one user using AWS, so it does work, and I tried it myself long ago. I'll be back home tomorrow, and I'll try it out.

I also just noticed that someone (you?) posted about this on Reddit as well.

**Comment by inkstain** [comment]
No worries, whenever you have time will be great. Yes that's me on reddit, I will put a response there that it is being looked into so don't worry about that

thx!

**Comment by inkstain** [comment]
Well, I was bit by the curiousity bug, since you were sure it worked and others had used it. It does in fact work, here is what I posted on the reddit thread

---

Okay so there are a couple of missing pieces here. The basic setup process in terms of AWS are outlined here

https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html

The wrinkles as it pertains to GitJournal are as follows

Need to create the Git repo in AWS as I did earlier

When troubleshooting the earlier issue, I tried, just in case, to create an initial file in the repo in case that was the hangup. Not sure if that was needed in the end but I know it worked after I did that and I did the following. So you may want to create an initial file in the Web UI just to be sure.

Use whatever PC host with SSH you have access to to create an SSH keypair as specified in the AWS link I provided above. However you cannot create/protect the keys with a passphrase, just hit Enter when prompted and Enter again to confirm.

Upload the public key you created to the AWS IAM User SSH Key, and note the SSH Key ID value it generates for it. The Key will look something like `APKSN15ZX2WHUISVRRDF`

The initial URI that you put in GitJournal when starting the Custom wizard is along the lines of the following

`ssh://YOUR-IAM-USER-SSH-KEY-ID@git-codecommit.us-east-2.amazonaws.com/v1/repos/gitjournal`

changing the SSH KEY ID to yours and the portion to the right of the @ symbol to match your assigned repo host and repo name 6. Select custom ssh key option rather than have it generate them, upload the public and private keys you generated earlier and then select clone and all should be good.

At the time I did the final steps, I had bumped up the IAM user from CodeCommit_PowerUser to CodeCommit_FullAccess as a troubleshooting step but almost certainly the former would be enough for the setup process.

[late edit] Forgot to add that given that there is no passphrase protection on the ssh key pair, I would definitely recommend creating a new pair just for this purpose and not reuse it elsewhere.

---

Hope this helps. Feel free to close the ticket or if you have any questions about the steps as I outlined them don't hesitate to let me know.

Thx!

**Comment by vHanda** [comment]
Thanks for providing the instructions. I'm going to close this bug.

I've opened two new issues - https://github.com/GitJournal/GitJournal/issues/228 and https://github.com/GitJournal/GitJournal/issues/227 to track related issues.
