### ISSUE TITLE
Support Multiple Repos

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#229]
Currently GitJournal can only have 1 repo. Many many users have requested the ability to have multiple repos.

Internally this will require some rather large refactorings.

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by dmotte** [comment]
Just a suggestion: graphically, i think it would be a good idea to have this in the upper left section of the sidebar, like the **Nextcloud** app, which handles multiple users this way :wink:

![nextcloud-multi-users](https://user-images.githubusercontent.com/37443982/99070195-131be880-25b0-11eb-880f-ce47dcad0320.png)

**Comment by vHanda** [comment]
Implemented in `1.74`. It should reach all of you within a day or two.
