### ISSUE TITLE
ability to rename files

### ISSUE THREAD

**Issue by devoldski** [GitJournal/GitJournal#23]
it would be very convenient to be able to rename filenames rather than only have the default timestamp.md

**Comment by devoldski** [comment]
i see that this issue aligns with #7 since it would also solve making differnet journals

**Comment by dabeeeenster** [comment]
On option to store file with the filename as the title of the note (or some sort of slug of the note) would mean the app would work nicely with things like https://github.com/glushchenko/fsnotes

**Comment by vHanda** [comment]
Hey Ben. There is an option for that. It might even be the new default

**Comment by dabeeeenster** [comment]
Ah great - has that not yet made it to the play store?

**Comment by vHanda** [comment]
Ah. Maybe not. I'll check and make a new release today.

**Comment by dabeeeenster** [comment]
Great thanks

**Comment by dgleba** [comment]
I was writing  new issue and found this. I will add my two-cents below here...

I love this project. Well done!

I would like to have an option to add the title and body to the file name.

Say, add the first `N` characters of the title, plus the first `N` characters of the note body to the `ISO8601 without colons` date.

The UI could have the existing options and two new options below.  It could simply add two boxes to enter a number between 0 and 99. This would keep scope of the change narrow.

Another idea: It could have checkboxes (or numbers to indicate the order) to allow the user to include the pieces they choose. Each piece would be separated by underscores for windows file system compatibility.


Number | Description
------------ | -------------
| X | First `X` of characters of the `Title` (special characters in the title are replaced with an underscore for windows file system compatibility.) Valid entries are 0-99. |
| Y | First `Y` of characters of the `Note Body` (special characters in the title are replaced with underscore for windows file system compatibility.) Valid entries are 0-99. |


Note: the resulting filename would have no spaces. It would not have special characters that are not compatible with Windows OS. That OS seems to have the most restrictive naming rules.
