### ISSUE TITLE
Editor: Allow undo / redo

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#242]
When editing a note it's essential to be able to undo some changes that have been made.

Notes to self: Use https://github.com/jheyne/diff-match-patch to compute a patch after each change in Editor, and keep storing the patches. The undo, redo buttons can be used to apply these patches.

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by akvadrako** [comment]
I would especially like to be able to undo deletions, or just in general revert to previous commits on a file/dir basis.

**Comment by vHanda** [comment]
I've released a very basic undo / redo support for the Raw Editor. (Version `1.74`)

**Comment by vHanda** [comment]
Fixed with 1.82.2
