### ISSUE TITLE
Option to generate only one journal entry per day

### ISSUE THREAD

**Issue by meatlover** [GitJournal/GitJournal#243]
## Description
Great app! I personally would prefer only keep one journal entry per day and keep editing it over and over. I think there must be others who also prefer it this way. It would be cool if there is an on/off option, something like 'one journal entry per day'. When it turns on alters the behavior of new journal button at bottom of app:
- default new journal name now becomes yyyy-mm-dd.md, instead of yyyy-mm-dd-HH-MM-SS.md
- if there is already a journal created earlier today, it does not create new journal entry and instead opens the existing entry. 

If there are multiple journal entries created in the same day in the repo, this feature does not need to merge them into one.

**Comment by vHanda** [comment]
On it! Someone on Twitter also requested this feature. Thanks for taking the time to file it.

**Comment by vHanda** [comment]
Opened a related issue https://github.com/GitJournal/GitJournal/issues/251
