### ISSUE TITLE
Support SVG Images

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#246]
We don't render them right now.

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by ModProg** [comment]
I was actually thinking about integrating some form of drawing feature and wanted to implement this using SVGs to make it compatible with other markdown renderers, but keep the possibility to edit them.

**Comment by ModProg** [comment]
I will work on this.

**Comment by ModProg** [comment]
Should SVG Rendering transform Images for Dark mode, i.e. make black lines white.
