### ISSUE TITLE
File naming ignores minutes and seconds < 10

### ISSUE THREAD

**Issue by da5nsy** [GitJournal/GitJournal#247]
## Environment

**Device information:**
 - OS name and version: Android 9 (Fairphone beta)
 - Manufacturer: Fairphone
 - Model: 2

## Description

**Expected behavior:** On the yyyymmddhhmmss mode I would expect, for example 20200914010101 to be possible.

**Current behavior:** It appears as though it not include leading zeros, and thus condense to 20200914111 (I have only tested minutes and hours, haven't been awake at midnight yet!). This causes ambiguity between, for example 20200914193507and 20200914190357, which would both condense to 2020091419357.

**Comment by vHanda** [comment]
Urgh. Fixing

**Comment by vHanda** [comment]
Thanks for reporting it. I'll make a new release tomorrow (1.70), you caught me right as I was going to bed, and this was going to annoy me otherwise.

Cheers.
