### ISSUE TITLE
Relative Links Don't work

### ISSUE THREAD

**Issue by ginkgomzd** [GitJournal/GitJournal#256]
## Environment

**App version:** 1.69.0+1745 
**Device information:**
 - OS name and version: Android
 - Manufacturer:
 - Model:

## Steps to reproduce

Links to files in the same folder, or in a child folder work just fine.
However, the parent-directory (..) is not understood in link paths.

1. Create a file to link to: A.md
1. Create a sub-folder and a file in the Sub-Folder: B.md
1. Create a link in B.md: `[A](../A.md)`
1. Switch to view-mode and try to open the link
1. Message is displayed in footer: "Link '../A.md' not found"

**Comment by ginkgomzd** [comment]
Thanks for the quick fix!
I'll look forward to the release.

**Comment by vHanda** [comment]
> Thanks for the quick fix!
> I'll look forward to the release.

You're welcome. Please keep filing all the bugs that you see, this has been super helpful.
