### ISSUE TITLE
setup without generating keys

### ISSUE THREAD

**Issue by devoldski** [GitJournal/GitJournal#26]
I would like to use my own pre-generated keys when setting up an account

**Comment by vHanda** [comment]
Wouldn't reusing ssh keys generate more of a security risk? Do you think we should allow this.

Maybe you could elaborate on the problem you're trying to solve.

**Comment by devoldski** [comment]
in general this I think it should be up to the user to determine if she/he want a new key or not. people have different reasons and different setups that works for them or within their security parameters. I for instance use one key for getting access to certain repositories as one user. and other keys other places. 

lots of different opinions on what is secure and what is best practice. Either way I would like to have the option to reuse keypairs
