### ISSUE TITLE
Move away from 'ssh-rsa' algorithm for ssh keys

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#260]
Based on https://marc.info/?l=openssh-unix-dev&m=160121534105667&w=2 , it is not recommended to use `ssh-rsa` any more. I'm not sure which of the 3 suggested alternatives should be used, but whichever is chosen should be compatible with GitHub (60-70% of the users) and Gitlab (30% of the users).

Additionally, I should probably document exactly what kind of keys are being generated so that people who are self hosting an SSH server can diagnose any issues.

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by kitambi** [comment]
SSH library probably just needs to be updated here, since I've experienced a similar issue with the MAC algorithms. Here are the sshd logs for both issues:
```
no matching host key type found. Their offer: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss [preauth]
no matching MAC found. Their offer: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com [preauth]
```
https://www.sshaudit.com/hardening_guides.html recommends disabling hmac-sha2-512 and ssh-rsa, which I've re-enabled specifically for GitJournal, even though that's not exactly ideal.

**Comment by vHanda** [comment]
> SSH library probably just needs to be updated here, since I've experienced a similar issue with the MAC algorithms. Here are the sshd logs for both issues:
> 
> ```
> no matching host key type found. Their offer: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss [preauth]
> no matching MAC found. Their offer: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com [preauth]
> ```
> 
> https://www.sshaudit.com/hardening_guides.html recommends disabling hmac-sha2-512 and ssh-rsa, which I've re-enabled specifically for GitJournal, even though that's not exactly ideal.

Which platform are you on?

**Comment by kitambi** [comment]
> > SSH library probably just needs to be updated here, since I've experienced a similar issue with the MAC algorithms. Here are the sshd logs for both issues:
> > ```
> > no matching host key type found. Their offer: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss [preauth]
> > no matching MAC found. Their offer: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com [preauth]
> > ```
> > 
> > 
> > https://www.sshaudit.com/hardening_guides.html recommends disabling hmac-sha2-512 and ssh-rsa, which I've re-enabled specifically for GitJournal, even though that's not exactly ideal.
> 
> Which platform are you on?

Server platform: Ubuntu 20.04 LTS (after following the linked hardening guide -- I've since re-enabled enough to make GitJournal work)
Client platform: Android 9

Actually, I think this issue was opened about client keys, so might benefit from a separate one.

**Comment by eleith** [comment]
git initially advises `ssh-ed25519` in their [ssh keygen documentation](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

**Comment by vHanda** [comment]
I'm a bit stuck on this as I can't seem to figure out how to serialize the ed25519 key to the openssh format. If anyone knows some documentation on how to do, that would really help. Otherwise I'll have to read either the openssl code or ssh or golang crypto code.
