### ISSUE TITLE
[ios] Support Shortcuts

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#262]
Quick Actions only works on Android so far.

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by vHanda** [comment]
Fixed with version `1.73`

**Comment by ScootRay** [comment]
Yay! Thanks.

Ray
