### ISSUE TITLE
Maintain Pro Purchases on Two Devices with Same Google Pay Account

### ISSUE THREAD

**Issue by chris2fr** [GitJournal/GitJournal#264]
## Environment

**App version:** 1.7.1+1857
**Device information:**
2 Devices Nokia with Android 9 and TECLAST T30 with Android 8

## Description

When I "restore Pro subscription" (previous monthly plan) on my Nokia, it disactivates on the TECLAST and inversely.
Furthermore, the settings (YAML, etc.) are fully lost in the process.

**What you'd like to happen:**

Same settings and pro subscription active on two terminals.

**Alternatives you've considered:** 

Persistent settings on terminals even when pro subscription deleted.

**Comment by chris2fr** [comment]
Actually, my settings seem persistent.

**Comment by vHanda** [comment]
Hey Chris. I'm not sure why this is happening, would you mind using the 'report a bug' button from both the devices? It will generate a debug log and attach it to an email.

**Comment by vHanda** [comment]
Hey Chris, could you please confirm if this is still happening with the latest release `1.73.1`?

**Comment by vHanda** [comment]
Hi. I'm hoping this has gotten fixed. Please let me know if it is still an issue.
