### ISSUE TITLE
Editable YAML in Raw Editor

### ISSUE THREAD

**Issue by devoldski** [GitJournal/GitJournal#27]
It would be nice to display the full document including YAML header in the Raw Editor so that it can be edited, also for adding extra meta information if needed

```
---
Date: 29.11.2019 - 01:02
Title: Whatever title i would like
Author: Alfa Sommersol
Template: journal
---
# header etc etc

and the rest of the document
```

**Comment by vHanda** [comment]
I'm confused. This is exactly what the Raw Editor is doing. It is showing the YAML Header. Is that not the case for you?

**Comment by devoldski** [comment]
My bad, closing issue. I review a file with no YAML meta :-)
