### ISSUE TITLE
GitJournal is not showing any notes

### ISSUE THREAD

**Issue by craignicol** [GitJournal/GitJournal#270]
## Environment

**App version:**  1.71.0+1963
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: Pixel
 - Model: 3a

## Description

**Expected behavior:** 

I can see my notes

**Current behavior:**

Cloud icon is crossed out, and sync displays an error at the bottom of the screen. 

![Screenshot_20201015-220133](https://user-images.githubusercontent.com/164306/96185760-4aa46000-0f32-11eb-90ef-6a8b364b1924.png)

## Steps to reproduce

1. Load the app

## Others 

Images

![Screenshot_20201015-215519](https://user-images.githubusercontent.com/164306/96185821-627be400-0f32-11eb-9f73-2b8d20c6d91d.png)

<details>
  <summary>Logs</summary>

```
```

```
```
</details>

**Comment by vHanda** [comment]
Hey Craig. You're the 3rd user to report this. I'm not sure what is going on - I pushed an update today - 1.71.1 which adds some more debugging info. Do you think you could update to it and use the report a bug button again, please?

**Comment by danfelipe** [comment]
Hi @vHanda 
I can confirm this is happening still in 1.71.1 

I use an Android phone so this seems to be some general issue and not OS specific, see below the same exception.

![img1](https://user-images.githubusercontent.com/25276659/96355143-659adf80-10ac-11eb-8c03-c5318128c0f5.png)

**Comment by vHanda** [comment]
Hey. I figured it out, it's because of a bad migration. I'll try to fix it tomorrow.

Till then, either resetting the git host or reinstalling the app will make it work.

**Comment by danfelipe** [comment]
Great! I can live with that :) Thanks as always for your quick responses.

**Comment by craignicol** [comment]
Just checked and reinstall worked for me. Thanks.
