### ISSUE TITLE
Clicking on a link is sometimes very slow

### ISSUE THREAD

**Issue by 1001ruchka** [GitJournal/GitJournal#271]
## Environment

**App version:**    
**Device information:**
 - OS name and version: iOS 14
 - Manufacturer: Apple
 - Model: iPhone SE (2016)

## Description
In the latest version, there is an animation when clicking on a link. On iphone se ios14, it slows down. Please add a function to disable it.

**Comment by vHanda** [comment]
I would prefer fixing the underlying problem which causes it to be slow rather than disabling the animation.

**Comment by vHanda** [comment]
@1001ruchka : If this is still reproducible, could you please add a video showcasing the bug? That would really help.
