### ISSUE TITLE
Allow Emoji Transformation to be controlled

### ISSUE THREAD

**Issue by agathauy** [GitJournal/GitJournal#280]
## Environment

**App version:**    1.7.1+1939
**Device information:**
 - OS name and version: Android 9
 - Manufacturer:
 - Model: OnePlus 3T

## Description

**Expected behavior:**
Retain Unicode format of emojis.
**Current behavior:**
Emojis transform to text form upon edit on a note.
## Steps to reproduce

1. Load note with Emojis that are Unicode characters
2. Make edit to note. Sync app to git.
3. Emojis in text form do not render on markdown editors nor wikis.

## Others   

Images

<details>
  <summary>Logs</summary>

```
```

```
```
</details>

**Comment by agathauy** [comment]
Hi! I realize that this bug(?) was apparently possibly caused by this feature request: https://github.com/GitJournal/GitJournal/issues/62

Just letting you know that the implementation for it also causes unicode to revert to text form. Just thought about checking on this when you posted your October update :D

**Comment by vHanda** [comment]
This is simple to remove, I'm just not sure how to make it configurable in the UI. One idea I had was to expose 'Read Transformers' and 'Write Transformers' or just 'Transformers' where you could enable or disable this emoji translation along with other things.

What do you think?

**Comment by agathauy** [comment]
@vHanda I'm not really sure haha. Haven't really made projects in Flutter so far, have yet to have time to try it out :D But that might work. All I'm thinking about is just not convert the unicode emojis back to the text fields.

Found this link tho, it might help https://stackoverflow.com/questions/44936239/displaying-text-with-emojis-on-flutter

**Comment by vHanda** [comment]
> @vHanda I'm not really sure haha. Haven't really made projects in Flutter so far, have yet to have time to try it out :D But that might work. All I'm thinking about is just not convert the unicode emojis back to being text entry emojis.
> 

I meant from a UI point of view. I know how to implement this, I'm not sure how to present it to the user. My current idea is to expose a new screen in the Settings page for 'Transformers', and over there you could unselect the emoji transformer (I might just disable it by default).

Is Transformers a descriptive enough name or should I call it something else?

**Comment by agathauy** [comment]
Yeah maybe the Transformer got confusing for me. Not sure, Parse Settings might be closer? Yeah I think it would be better to actually disable it by default, if you mean the transformation of emoji text to unicode and vice versa, just because it's more standard and cross-platform compatible.

**Comment by goodevilgenius** [comment]
It also seems odd that emojis are transformed in the file, but not in the filename.

For example, as a test, I created a new note called "💯 Emojis"

The filename was "💯 Emojis.md", but the header in the file said:

`# :100: Emojis`

For me, personally, I would rather they be left untouched in the file body, but modified in the filename. Although, having them in the filename isn't a big problem.

I think a "Transformers" option where we could switch it on/off would make sense.

**Comment by GeorgFoc** [comment]
I am also affected by this bug. I do not want, that gitjournal transform my files. Please can you make this behaviour customizable? This destroys my notes.

**Comment by nglgzz** [comment]
This behavior is breaking my workflow as well. I use emojis to categorize links and after they're converted to text they're no longer rendered properly.

Regarding the UI for this, I would actually expect it to be under the editor settings instead of a new category. Same for the metadata settings. I don't think they need a new category as they currently have just one option, and from the user's point of view they're just tweaking the behavior of the editor.

**Comment by ljantzen** [comment]
I'd love to see some progress on this issue.  Personally, i prefer `emoji text substitution`to `transformation`.

**Comment by heesters** [comment]
Same here, at the moment it breaks some of my links (I could change things around, but that's not really fixing it). I would like the option to have them untouched overall.
Thanks!

**Comment by vHanda** [comment]
Fixed. With 1.80
