### ISSUE TITLE
Import Key

### ISSUE THREAD

**Issue by fekir** [GitJournal/GitJournal#285]
## Environment

**App version:** 1.72.1
**Device information:**
 - OS name and version:
 - Manufacturer:
 - Model:

## Description

**What you'd like to happen:**

Being able to import a ssh key after adding a git remote

Why I would like to have such a feature.

This week my key got deleted from the application, maybe during an update, I do not know as it did not manifest again (therefore did not made a bug report yet).
The only way I was able to re-add the key was resetting the application, which might cause data loss if I had some unsynchronized notes.

As I had the key on the phone, but no direct access to the git remote for eventually changing it, I wanted to import the existing key again but not adding a new one.

It might also be useful if one decides to change/update keys.

**Comment by vHanda** [comment]
Fixed in `1.73`

I encountered the same problem
