### ISSUE TITLE
Bug: iPad input via bluetooth keyboard

### ISSUE THREAD

**Issue by zcysxy** [GitJournal/GitJournal#288]
**App version:**  1.72.3+1987
**Device information:**
- iPad OS 14
- bluetooth keyboard

## Description

I’m using a bluetooth keyboard and a different input (Chinese) other than directly inputing English through the keyboard. However the input block appears at top-left corner, making the app almost useless for me 😢

![IMG_1385](https://user-images.githubusercontent.com/48207708/97547795-3c157880-1a09-11eb-8177-6e1dd5fa1e4f.jpeg)

**Comment by vHanda** [comment]
Hi. Are you still facing this issue? Was there any easy way for you to move the input block. Redoing the interface to not use the top left seems rather difficult.
