### ISSUE TITLE
Sharing a website on Android does nothing

### ISSUE THREAD

**Issue by Nebucatnetzer** [GitJournal/GitJournal#293]
## Environment

**App version:**  1.73.0+2015
**Device information:** Pixel 4XL
 - OS name and version: Android 11
 - Manufacturer: Google

## Description

**Expected behavior:**
The content of the website gets saved in a note or at minimum the link to the website.

**Current behavior:**
It opens a new note without a title or content.

## Steps to reproduce

1. Open any browser
2. Share the website to Git Notes.

**Comment by vHanda** [comment]
Fixed with version `1.73.2`
