### ISSUE TITLE
Allow a custom ssh port to be specified

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#30]
One cannot access via a custom port right now.

**Comment by darkermatter** [comment]
This is a showstopper for the majority of self hosted repos.

**Comment by vHanda** [comment]
I didn't realize it was such a big problem. I'll investigate the issue
today and get back to you.

**Comment by vHanda** [comment]
It turns out that this works perfectly. It's just the URL syntax that can be a bit confusing.

For SSH running on the standard port (22) - `user@host.com:/path/to/repo/journal.git` works perfectly.
For SSH running on a non standard port one needs to specify the ssh protocol - `ssh://user@host.com:4555/path/to/repo/journal.git`. There isn't any way to specify the port when using the syntax without the protocol.

I'm closing this for now, but I'm open to suggestions on how to improve this to make it clearer. For now I'm going to add a FAQ over here - https://gitjournal.io/support/

**Comment by darkermatter** [comment]
Using the full URL syntax works great 👍
