### ISSUE TITLE
Support more of the markdown syntax

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#32]
We currently support a very limited subset of Markdown. We should support more - specially tables and checkboxes.

The [flutter_markdown](https://pub.dev/packages/flutter_markdown) now supports Github flavoured markdown. However, we can cannot upgrade as it requires a beta version of Flutter.

I don't want to switch of "beta" or "master" of Flutter as we're already getting loads of random Flutter related crashes. Specially on iOS.

**Comment by carun** [comment]
Having support for checkboxes would make this a task list alternative as well - taking inspiration from Google Keep is optional too.
