### ISSUE TITLE
Setup Grafana for metrics

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#335]
It would be nice to setup Grafana to visualize different metrics and to see how the backend is performing.

**Comment by gerhard-tinned** [comment]
do you need help with that?

**Comment by vHanda** [comment]
> do you need help with that?

Hey. Thanks for the offer.

I'd been in a bit of rut lately as my health issues have resulted in my right hand not working that well, but it seems to be getting better, and I'm learning to use my left hand more, and I even landed up getting some pedals, and I'm going to experiment with coding with my voice, so it's not all bad.

Thanks a lot for the offer. I just landed up setting it up - https://github.com/GitJournal/env - It's very basic right now, but at least I have some metrics. I plan to make most dashboards public.
