### ISSUE TITLE
Share menu doesn't work on Android

### ISSUE THREAD

**Issue by Bassmann** [GitJournal/GitJournal#341]
## Environment

**App version:**  1.7
**Device information:**
 - OS name and version: Android 9
 - Manufacturer: OnePlus
 - Model: 3T

## Description

**Expected behavior:**

Selecting something in an app and choose GitJournal in the "share" menu, GitJOurnal should open with the selected text included in a note. This works in iOS.

**Current behavior:**

An empty note is opened.

## Steps to reproduce

1. Select anything
2. Choose "share"
3. Tap "GitJournal"

**Comment by vHanda** [comment]
Fixed with `1.73.2`.

**Comment by Bassmann** [comment]
Great, thanks a lot!
