### ISSUE TITLE
Error "remote origin already exists"

### ISSUE THREAD

**Issue by dmotte** [GitJournal/GitJournal#343]
## Environment

**App version:**  1.73.0+2015 (downloaded from Google Play store)
**Device information:**
 - OS name and version: Android 9
 - Manufacturer: Xiaomi
 - Model: Mi A1

## Description

**Current behavior:** when i click `Clone repo` in _screen02_, if GitJournal cannot clone the repo for some reason (for example, i forgot to add the SSH public key in my Gitlab account), then when i go back and try again (for example, after adding SSH public key in my Gitlab account) i see the error message in _screen05_: **remote origin already exists**. If i want to try again, then i have to reset the whole application data storage from Android settings.

**Expected behaviour**: i should be able to try again after an unsuccessful attempt to clone the repository.

## Steps to reproduce

Follow these screenshots in order to reproduce.

Screen01:

![screen01](https://user-images.githubusercontent.com/37443982/99050432-63874c00-2598-11eb-9003-647d7f0334c3.jpg)

Screen02:

![screen02](https://user-images.githubusercontent.com/37443982/99050554-700ba480-2598-11eb-9fdc-6873654d49bf.jpg)

Screen03:

![screen03](https://user-images.githubusercontent.com/37443982/99050565-70a43b00-2598-11eb-8bed-65dd77ed4f91.jpg)

Screen04:

![screen04](https://user-images.githubusercontent.com/37443982/99050568-70a43b00-2598-11eb-89e9-51975b84cbf2.jpg)

Screen05:

![screen05](https://user-images.githubusercontent.com/37443982/99050572-713cd180-2598-11eb-859d-a18cf77c7f29.jpg)

**Comment by vHanda** [comment]
Fixed with 1.73.1, the update should be rolling out. Google does it a bit slowly.

Sorry about the bug. It was the result of me switching from a git clone to a git init + add remote + fetch + merge. This was done so that the history of the repo before you added the host is preserved properly
