### ISSUE TITLE
Error: "Not a Git Repository" when setting up Git Host

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#347]
A user has reported this, and based on the logs the '.git' folder exists, so I'm not sure what is going on.

**Comment by paulmach** [comment]
I have this same issue.  iOS 1.73.4+2122. I tried a bunch of different things. I can try more if you want.

Here is the debug info. https://gist.github.com/paulmach/f19070965cd79cf2f94dc68d81106eae

**Comment by flickerfly** [comment]
![Screenshot_20210107-063043.png](https://user-images.githubusercontent.com/119957/103889119-e0740500-50b3-11eb-96ae-79d5ff67f7f8.png)

**Comment by vHanda** [comment]
Closing this as it's the same bug as #377
