### ISSUE TITLE
Can't add repo in iOS app: `remote "origin" already exists`

### ISSUE THREAD

**Issue by eddyg** [GitJournal/GitJournal#348]
## Environment

**App version:** 1.72.3+1987
**Device information:** OS name and version: iOS 14.2

## Description

**Expected behavior:** Can add a git repo

**Current behavior:** Can't add a git repo

## Steps to reproduce

_Brand new to GitJournal (saw it mentioned recently in a HackerNews comment) but I'm not sure what I'm doing wrong:_

1. At the "Enter the Git Clone URL" prompt, enter a valid Git URL
2. Tap **Next**
3. Tap **Generate new Keys**
4. Tap **Copy Key** and paste it on the Git host as appropriate
5. Tap **Clone Repo**

![IMG_9796](https://user-images.githubusercontent.com/3235109/99161055-e8b75180-26bb-11eb-8f84-7a8fd058a296.jpg)

**Comment by vHanda** [comment]
Fixed with `1.73.2`, I'll make a new release on ios today, so you should get it within a few days (Assuming the review process goes fine)
