### ISSUE TITLE
SSH authentication fails with version 1.73.2+2064 on Android

### ISSUE THREAD

**Issue by gerhard-tinned** [GitJournal/GitJournal#351]
## Environment

**App version:**  1.73.2+2064   
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: OnePLus
 - Model: OnePlus 8

## Description

**Expected behavior:**
Sync should work. obvious. :-) 

**Current behavior:**

Error reported by the app is "Sync Error Invalid Credentials" but the credentials are correct (ssh-key) I checked the key and the server logs. So far I could not exactly pinpoint the root cause. 

## Steps to reproduce

My observation is that it worked before the app-update, then it stopped working.

## Others   

<details>
  <summary>Logs</summary>

```
Server SSHD log lines relevant ...
...
sshd[]: Found matching RSA key: *******************************************
sshd[]: debug1: restore_uid: 0/0
sshd[]: debug3: mm_answer_keyallowed: key 0x************* is allowed
sshd[]: debug3: mm_append_debug: Appending debug messages for child
sshd[]: debug3: mm_request_send entering: type 22
sshd[]: debug3: mm_send_debug: Sending debug: Forced command: gitosis-serve SSHKEYNAME
sshd[]: debug3: Wrote 96 bytes for a total of 1517
sshd[]: debug3: Wrote 592 bytes for a total of 2109
sshd[]: debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa
sshd[]: Postponed publickey for git from IP.IP.IP.IP port 2831 ssh2
sshd[]: debug3: mm_request_receive entering
sshd[]: Connection closed by IP.IP.IP.IP
sshd[]: debug1: do_cleanup
sshd[]: debug3: PAM: sshpam_thread_cleanup entering
...
```

</details>

I have not much experience debugging apps on Android. If there is any details I can provide, please explain me in detail how to get those. Thanks.

**Comment by marek0o** [comment]
I have same issue.
Syncing worked right, but after maybe background upgrade I get "Sync Error Invalid Credentials" error. Even after regenerating SSH key.

**Comment by gerhard-tinned** [comment]
I also tried to regenarate the ssh-key, ... no luck. 
I completely removed the app and installed it fresh ... now it works again. 

That means all NOT COMMITED AND PUSHED changes are gone. Sadly. :-(

**Comment by vHanda** [comment]
I've been away for a bit. Let me take a look. This seems bad.

**Comment by Boztown** [comment]
I have this problem as well. On Android. I re-gened my keys and added them to GitHub as I've done before. No luck. I have not tried to newer "Provide Custom SSH Keys" in lieu yet. My hunch tells me that maybe when that feature came out it broke the built-in SSH key method of authenticating.

**Comment by vHanda** [comment]
> I have this problem as well. On Android. I re-gened my keys and added them to GitHub as I've done before. No luck. I have not tried to newer "Provide Custom SSH Keys" in lieu yet. My hunch tells me that maybe when that feature came out it broke the built-in SSH key method of authenticating.

I think you're right. I moved from using openssl to generate the SSH keys to some code in Dart. That's probably what broke this. Could you please try with the custom keys? If it works with that then we will know what the issue is, I can do a fast revert.

**Comment by marek0o** [comment]
> 
> I think you're right. I moved from using openssl to generate the SSH keys to some code in Dart. That's probably what broke this. Could you please try with the custom keys? If it works with that then we will know what the issue is, I can do a fast revert.

Yes, this work for me.
I've copied keys generated on my PC and then all changes from the GitJournall app have been sucessfully synced.

**Comment by Kolossi** [comment]
The fix for me (attaching to gitea) was to go change the "Git Author Settings"->"Full name" in GitJournal settings to the correct git username.

Using "{username}@..." in url seemed to be ignored by GitJournal.

I could then connect & clone ok.

HTH someone.

**Comment by vHanda** [comment]
> The fix for me (attaching to gitea) was to go change the "Git Author Settings"->"Full name" in GitJournal settings to the correct git username.
> 
> Using "{username}@..." in url seemed to be ignored by GitJournal.
> 
> I could then connect & clone ok.
> 
> HTH someone.

Are you sure? Could you please try one more time. The Git Author name is only used during commits, so I'm surprised that this is happening.
