### ISSUE TITLE
Invalid Credentials when cloning repo

### ISSUE THREAD

**Issue by Sigafoos** [GitJournal/GitJournal#353]
## Environment

**App version:**     1.73.3+2106
**Device information:**
 - OS name and version: iOS 14.2
 - Manufacturer: Apple
 - Model: iPhone XS Max

## Description

**Expected behavior:** Adding the credentials for a new repo will add it

**Current behavior:** Get "invalid credentials"

## Steps to reproduce

1. Choose custom hosting provider
2. Enter information (see below)
3. Attempt to clone

This may be a clone of #351, or maybe #85. Initially I was using keys generated on my iPhone by Prompt and cloning a private repo. After seeing those issues I made it public and used keys generated by the app. Thinking it could be a caching issue I even removed and reinstalled the app. 

Here are the logs:

```
{"t":1606157307808,"l":"d","msg":"githostsetup_button_click Clone Repo"}
{"t":1606157307811,"l":"d","msg":"Event.GitHostSetupButtonClick"}
{"t":1606157307812,"l":"i","msg":"RepoPath: <path redacted>"}
{"t":1606157308627,"l":"e","msg":"Failed to add remote","ex":"GitException: Invalid Credentials","stack":"#0      GitRepo.fetch (package:git_bindings/git_bindings.dart:38) <asynchronous suspension> #1      GitHostSetupScreenState._startGitClone (package:gitjournal/setup/screens.dart:532) <asynchronous suspension> "}
{"t":1606157308630,"l":"i","msg":"Not completing gitClone because of error"}
{"t":1606157308630,"l":"d","msg":"Event.GitHostSetupGitCloneError"}
```

In my repo I don't see any attempt to connect. For reference, I made a repo named "test" and cloned it on my laptop, and saw (among other things)

```
2020/11/23 19:00:27 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT repository.* FROM `repository` INNER JOIN `user` ON `user`.id = repository.owner_id WHERE (repository.lower_name = ?) AND (`user`.lower_name = ?) LIMIT 1 []interface {}{"test", "dconley"}
2020/11/23 19:00:27 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT `id`, `owner_id`, `name`, `fingerprint`, `content`, `mode`, `type`, `login_source_id`, `created_unix`, `updated_unix` FROM `public_key` WHERE `id`=? LIMIT 1 []interface {}{7}
```

so using a bad key would, I assume, show at least the first log.

**Comment by vHanda** [comment]
Could you please share you ssh-agent version and the configuration used? That way I'll be able to setup a similar environment and test this out.

**Comment by Sigafoos** [comment]
I'm pretty much using the out-of-the-box gitea configuration. 1.14.0+dev-338-gabb9cffe4 running on Docker (9022:22, 9080:3000).

**Comment by dodtsair** [comment]
I faced the same problem.  Followed instructions to add ssh key to github.  Then attempted to sync.  Sync failed with invalid credentials.   I double checked the finger print  and it matched. 

I then removed that key from git, generated a new key externally (connectbot) and imported the public key into github and git journal ( and the private).  Once done sync worked. 

Generating a key using git journal did not work.   Importing a key externally worked.

**Comment by Boztown** [comment]
I've had this problem on Android, using GitHub (as a user this was previously working for). I commented on another issue somewhere too. Anyway, it turns out what @dodtsair said worked for me. I generated keys myself using `ssh_keygen` and loaded them in, and that worked. Using the built-in GitJournal "generate key" seems to leave me with a dud.

**Comment by Sigafoos** [comment]
I tried generating keys on WSL2 Ubuntu and got the same error. In this case I wonder if it's using the custom provider, as it fails _instantly_, appearing to not even wait for the connection to fail.
