### ISSUE TITLE
App freezes when set to store repo externally

### ISSUE THREAD

**Issue by esm7** [GitJournal/GitJournal#355]
## Environment

**App version:**  1.73.2+2064   
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: Samsung
 - Model: S20

## Description

**Expected behavior:**

When setting the app to store the repo externally, I expect files in that folder (`/storage/emulated/0/GitJournal/journal`) to be shown in the app.

**Current behavior:**

## Steps to reproduce

1. Launch a fresh-installed GitJournal or after clearing data from the app settings. Skip the tutorial.
2. In the settings, turn on "store repo externally"
3. Close the app and relaunch it.
4. The app is now stuck at the splash screen, with the big GitJournal icon filling the screen.

## Others   

Images

<details>
  <summary>Logs</summary>

```
```

```
```
</details>

**Comment by vHanda** [comment]
I can reliably reproduce this issue on an emulator. So I'll try to fix it as soon as I can.

**Comment by vHanda** [comment]
I've fixed this issue with `1.73.6`. I'll make a new release today.
