### ISSUE TITLE
Allow Git Remote to be reconfigured

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#36]
Currently once the Git Remote Host has been setup there is no way to change it, or even view what it was set to. We should provide a way to change the remote host, specially since we're a big advocate of Data Portability.

**Comment by zeddyblue** [comment]
Hi, 
What is the best way to change this at the moment? Specifically, all I want to change is the target folder in the existing git repo I have set up. Is this even possible or do I need to rethink my git setup?

Or is there a way to change the default "notes" folder of GitJournal. I need to do this so it plays nicely with my other linux desktop app. For example if I have ~/notes/ on my desktop everything works fine. But I need to have ~/notes/default/ and I want to make "default" the default folder for gitjournal. It still works as is, but basically I can only see notes in the folder view. The notes view is always empty. 

Thanks

**Comment by deobald** [comment]
Downvoting in earnest since I think this thing is ultimately important but hardly important for early adopters. We can just reinstall the app. Thanks for building gitjournal!

**Comment by vHanda** [comment]
The current solution allows you to clone a different repository. So it's not exactly letting you configure the git remotes, but it's better than nothing.

In the future, I'll add a way to change the remote, thereby preserving the data, and maybe even allow multiple remotes.

**Comment by vHanda** [comment]
Closing this as there are 2 different bugs to allow an extra remote to be added and to add support for multiple repos.
