### ISSUE TITLE
GitJournal doesn't sync, doesn't clone. Possibly chooses gh-pages branch. 

### ISSUE THREAD

**Issue by dummifiedme** [GitJournal/GitJournal#363]
GitJournal doesn't clone the repo. Tried many times. It shows it has synced well. The ssh keys are visible on my github repo settings, but GitJournal isn't syncing at all. If I create a new note in GJ, it shows to have synced onto the server, but there's no commit on the repo.

I had used it before as well, and then it worked fine. I don't know what's the problem. I do feel that the GitJournal is going for the gh-pages branch than the main branch. Since, in folder structure view, it should the index.html file that I have on gh-pages branch.

What should I do?

**Comment by vHanda** [comment]
Earlier I used to use a git clone, now I am using a git fetch, and guessing the branch, which might be the reason behind this.

I'll remove the guessing for the proper way. And once I add the ability to switch branches, maybe that will help. I sadly can't give you a time estimate - please see the November update - development is going to be slow for a while.

**Comment by dummifiedme** [comment]
So how can I trick the guesswork?
Making gh-pages default for sometime then switching back can make any difference? (Stupid of me, but still).

**Comment by vHanda** [comment]
> So how can I trick the guesswork?
> Making gh-pages default for sometime then switching back can make any difference? (Stupid of me, but still).

I don't remember right now. I'll take a look and get back to you.

**Comment by dummifiedme** [comment]
Sure :)

**Comment by vHanda** [comment]
I looked and there isn't an easy way to trick the guess work. It's easier for me to fix this issue properly than add a way to trick the guesswork.

Related https://github.com/GitJournal/GitJournal/issues/299

I've implemented a basic version for Android, but I'm getting some segmentation faults - (probably bad c code which I've written) - I'll try to diagnose it tomorrow and see.

**Comment by dummifiedme** [comment]
Sure.
It would be a great help. 👍

**Comment by vHanda** [comment]
I want to test this out a bit more. So you can expect a new release with this over the weekend or so. The version will be `1.73.5`

**Comment by dummifiedme** [comment]
Sure . Thanks 👍
