### ISSUE TITLE
Render *.txt files as plain text, not as markdown

### ISSUE THREAD

**Issue by gdemin** [GitJournal/GitJournal#364]
## Environment

**App version:** 1.73.2+2064
**Device information:**
 - OS name and version: Android 7.1.2
 - Manufacturer: Xiaomi
 - Model: Redmi 5 Plus

## Description

**What you'd like to happen:** Currently *.txt files are rendered as markdown. More exactly, in the view mode single line breaks are ignored and several lines are shown as single line. 
In the edit mode unicode symbol '✔' is replaced with `:heavy_check_mark:`. It is ok for markdown, but it is not good for plain text. 
Is it possible to show and edit *.txt files as plain text, not as markdown?

**Comment by vHanda** [comment]
One solution would be to not allow txt files to ever be in 'view mode' and always be in 'edit mode'. Would that work for you?

**Comment by gdemin** [comment]
Generally it's fine, but won't solve issue with `check mark is replaced with :heavy_check_mark:`

**Comment by vHanda** [comment]
Cool. It'll at least fix half the bug :)

**Comment by gdemin** [comment]
Is it really needed to keep `:heavy_check_mark:` and other emoji instead of appropriate unicode character?
I use VSCode as my desktop markdown editor and if I edit markdown notes on the phone with GitJournal all such symbols are converted to the text representation with colons. It is rather inconvenient...

**Comment by vHanda** [comment]
Closing this as the emojiy process can be closed from the Settings -> Misc.
