### ISSUE TITLE
"Reset Git Host" should not destroy SSH keys

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#369]
## Environment

**App version:** 1.73.2+2064  
**Device information:** Android

## Description

There is occasionally need to reset the git checkout in the app, if, e.g., there is a merge problem.  However, the previously generated SSH keys should not be destroyed when the host is being reset, since they are likely already deployed and could still be used.  This would be less of an issue if there were a way to reset the git clone without resetting the whole host, but either way I think the key generation/maintenance should be handled separately from the git host config.

Thanks for a great app!

**Comment by vHanda** [comment]
I'm going to close this as this can be solved by - 
* https://github.com/GitJournal/GitJournal/issues/149
* https://github.com/GitJournal/GitJournal/issues/352
* https://github.com/GitJournal/GitJournal/issues/286
