### ISSUE TITLE
Option to disable auto-sync

### ISSUE THREAD

**Issue by dimateos** [GitJournal/GitJournal#375]
## Environment

**App version:** 1.73.2+2064
**Device information:**
 - OS name and version: Android 8.1.0
 - Manufacturer: Xiaomi
 - Model: Redmi Note 5

## Description

**What you'd like to happen:** I'm missing an option to be able to manually commit and push changes. So instead of automatically happen after saving a single file, then it would be possible to edit multiple and then manually sync them (by pressing the cloud icon for example). At least for me, this approach feels better, like what you would do in a kind of "session". 

> Anyway this is a low priority feature request, thanks for the app 😄

**Comment by vHanda** [comment]
Hey. This exists. Settings -> git Remote settings -> sync frequency.

You can't control when it commits though.

**Comment by dimateos** [comment]
Damn I tried to find this twice. Thanks!

**Comment by vHanda** [comment]
No worries. The settings are messy and could definitely use more structure and/or a search option.

I'm happy you find the app useful :)

**Comment by scarlehoff** [comment]
> You can't control when it commits though.

Is it possible to make it not commit at all? I would like to manage the repository externally but use the visualization of gitjournal, I like very much the yaml-based visualization option & ability to pinning but prefer to use my own git-flow.

(sorry for the necrobump)

**Comment by vHanda** [comment]
> > You can't control when it commits though.
> 
> Is it possible to make it not commit at all? I would like to manage the repository externally but use the visualization of gitjournal, I like very much the yaml-based visualization option & ability to pinning but prefer to use my own git-flow.
> 
> (sorry for the necrobump)

Sorry. I missed this.

No. It's not possible and I'm not up for adding this ability as GitJournal is very tied to Git. Internally, each file is now being identified by their sha1 hash, and even the metadata is by default being fetched from Git (modified / created).

I've added a way to see the git log in the experimental settings (not yet released), I'm open to adding way to combine commits or change the commit message, but not avoid commits all together.
