### ISSUE TITLE
git host details keep resetting

### ISSUE THREAD

**Issue by eleith** [GitJournal/GitJournal#376]
## Environment

**App version:**  
1.73.5+2147
android 11

## Description
my git host details (I am not using github or gitlab) are lost and I have to re-enter them to get syncing to work again. 

this seems to happen when app is killed in the background.

**Expected behavior:**
git host details are preserved

-----
this behavior did not exist on the previous version.

**Comment by vHanda** [comment]
Ive pushed a possibly fix already in 1.73.6, if not I've added extra debugging info.

**Comment by eleith** [comment]
I do not observe the issue on your latest push. great!
