### ISSUE TITLE
Is there gonna be a update to fix the syncing issue?

### ISSUE THREAD

**Issue by jarodise** [GitJournal/GitJournal#378]
## Environment
Android and iOS
**App version:*latest*    
**Device information:** Android phone, iPad
 - OS name and version: both latest
 - Manufacturer:
 - Model:

## Description
it's been a while, the sync on both on my android phone and iPad do not work at all, any plan to fix this anytime soon? 
**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

## Others   

Images

<details>
  <summary>Logs</summary>

```
```

```
```
</details>

**Comment by vHanda** [comment]
I'll make a new release on iOS tomorrow morning.

**Comment by vHanda** [comment]
I found a few bugs in the process, and this has gotten delayed. I still want to fix the bugs as it's related to the syncing issue.

**Comment by vHanda** [comment]
Fixed with `1.73.10`. I'm releasing it on Android and iOS right now. it might take a day or two to pass through the review.
