### ISSUE TITLE
Android: Allow sharing to GitJournal from other apps.

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#38]

**Comment by Ziinc** [comment]
There are available plugins for sharing:
https://pub.dev/packages/share

This is quite a critical feature for importing notes

**Comment by Ziinc** [comment]
This is a large pain on android, especially for saving snippets. Is there any way I can help to move it forward?

**Comment by vHanda** [comment]
Hey Zinc.

The link you shared is for sharing from GitJournal to other projects. If I
understand correctly, you want the inverse, correct?

**Comment by vHanda** [comment]
It seems I can use this https://pub.dev/packages/receive_sharing_intent#-installing-tab- . It's not trivial, as it will require refactoring the app a bit, but it seems doable. Okay. I'll make it a priority for next week.

**Comment by Ziinc** [comment]
@vHanda oh I did not realise the difference in sharing direction for the package. Thanks for shifting it up in priority.

Do let me know if I can contribute in any other way, be it design mockups etc
