### ISSUE TITLE
MD files should end with a single newline character

### ISSUE THREAD

**Issue by SotongDJ** [GitJournal/GitJournal#383]
## Environment

**App version:** 1.73.7+2159
**Device information:**
 - OS name and version: Android 11
 - Manufacturer: Google
 - Model: Pixel 5

## Description

**What you'd like to happen:** 
 - Files should end with a single newline character. Refer to [MD047](https://github.com/DavidAnson/markdownlint/blob/v0.22.0/doc/Rules.md#md047)

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by thoschworks** [comment]
It's a **bug** and **not** a feature.

Text files without a newline at the and are not [POSIX-compliant](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

**Comment by vHanda** [comment]
Changed accordingly :)

Could you also please vote on this issue. It helps me prioritize them.
