### ISSUE TITLE
Drop current changes

### ISSUE THREAD

**Issue by fekir** [GitJournal/GitJournal#395]
## Description

I open a file, begin to type, and shortly after notice that GitJournal does not have the changes I made from another device.

If I save the currently made changes (which is what happens if I close the editor), this often results in a merge where the changes made on the other device are not visible on the latest version of the document.

**What you'd like to happen:**

Give me the possibility to stop editing without saving what I just wrote (normally I notice the issue where I can afford readd what I just wrote).
Then I would sync the content and have the latest and greatest version on my device to edit.

**Alternatives you've considered:** Ignore the issue, view git history on a PC and merge the "lost" content back.
But it's not practical when working with smart devices...

https://github.com/GitJournal/GitJournal/issues/286 would help, as it would permit to hard reset the new changes.
I still decided to make a different Ticket as it is a different use case, I might want to stop editing and not saving my work for other reasons...

**Comment by vHanda** [comment]
There is a "Discard Changes" button, would that work for you?

**Comment by fekir** [comment]
-_-"

Yes, just tested, I've never noticed it as I nearly never used the menu...


I believe you can close it then, unless you want to move it in a more visible position, for example near the save/close button... but maybe I'm the only kne who had this "discoverability" issue.

**Comment by vHanda** [comment]
I think commonly used actions should definitely be visible. But I don't know how to depict this with an icon.

Maybe I could implement undo and redo support, and that way those icons could be placed at the bottom bar. The icons are fairly obvious. What do you think?

**Comment by fekir** [comment]
Just thinking out loud... I am not a GUI expert...

Might be a simpler solution, but changing the meaning of the trash to undo unsaved changes (might also be faster than doing multiple undos)

(and the iconic floppy for saving? Cant remember if MS Word used something for discarding changes/not saving...)

For deleting file I think some programs used a shredder (as the trash would be taken) symbol...

And move "delete file" to the menu?
I do not think that tha operation is that common...

Otherwise yes, undo/redo is a much superior solution, it would be welcome/handy/.... but it will take, I suppose, much more time to implement

**Comment by vHanda** [comment]
I think the 'trash can' icon is always expected to delete the note. I asked about 5 different friends and that's the behaviour they expected (not a huge sample size, though).

I started implementing undo / redo since it seemed like fun. I'll try to finish it soon as an experimental feature as I'm just storing every old copy of the note when you're making changes, and that isn't memory efficient. GitJournal already blows up with huge files.
