### ISSUE TITLE
Show Progress Indicator when Cloning

### ISSUE THREAD

**Issue by joshdm42** [GitJournal/GitJournal#397]
## Environment

**App version:** Version 1.70
**Device information:** All; personally using Samsung S9+ and Boox Nova 3

## Description

**What you'd like to happen:** On big repos or on slow internet, it can be difficult to know if "Cloning..." is actually still working, or if the app has frozen. Having some evidence that the app is still working (beyond just the spinning circle) would be really helpful. Either a loading bar or a "downloading file number X out of Y". 

Even better, having an option to see the whole terminal output for the "git pull" command would be prime, especially if there's some weird issue with a repo. Seeing terminal output could allow for debugging in a way that isn't currently possible.

**Comment by vHanda** [comment]
Yes. Some output would be good. This is so difficult though. Talking to libgit2 means going through 3-4 additional layers.

It might be easier for me to just implement git pull / push in Dart and reuse the ssh connection. Hmm. Let me see what I can do.
