### ISSUE TITLE
The app not show my journal entries

### ISSUE THREAD

**Issue by ataliba** [GitJournal/GitJournal#4]
I have a problem here. I start the use of GitJournal today and now, when i try to open my apps my journal entries are lost ( i have the app installed on my phone and on my tablet  ) .

But when i open my Gitlab repository, all of my entries are on the repo. 

Anyone have this problem ? I clean all the app data and try to reconfig the repo and ssh key ... and no success ... 

Here some logs : https://gist.github.com/ataliba/4348dd7acb5d071819e64469d38e4e3d

**Comment by ataliba** [comment]
Here some logs : https://gist.github.com/ataliba/4348dd7acb5d071819e64469d38e4e3d

**Comment by vHanda** [comment]
Hey Ataliba. Thanks for filling the bug report. I think I see what's happening.

Any chance you could provide me with some of the entries? I'm interested in the YAML metadata, the text can be changed to a random strong.

**Comment by vHanda** [comment]
I didn't mean to close this issue. I'm still not 100% sure if it has been fixed.

**Comment by ataliba** [comment]
> Hey Ataliba. Thanks for filling the bug report. I think I see what's happening.
> 
> Any chance you could provide me with some of the entries? I'm interested in the YAML metadata, the text can be changed to a random strong.

Sorry for the late answer. I only read your message now. If you need more information i will send :-)

**Comment by vHanda** [comment]
If you could just send me the app logs after updating to `1.1.1`, I would really appreciate it!

**Comment by ataliba** [comment]
The log : https://gist.github.com/ataliba/17ae1a217f275410013f0fd884fbb7fe

**Comment by ataliba** [comment]
Here the logs : https://gist.github.com/ataliba/d053bf72943ca896108694bbae3d10bd

In one of my files i see an problem with the date. Tomorrow before the problem i made some changes on the file. 

And after the changes the date has been removed .

**Comment by vHanda** [comment]
Hi. Could you also please do the following - 

* share the original file from which the changes were removed
* Share the logs after this RangeError appears.

I'd like to fix all the issues :)

**Comment by ataliba** [comment]
Hello, 

here the file : http://cerebro.freeshell.org/2019-05-26T10:01:41+0-3:00.md.gz

And the log: https://gist.github.com/ataliba/7520f89bdbec9c4484bb37eba7ac946f

Thanks and if you need more information i will give :-)
