### ISSUE TITLE
Support OpenKeychain

### ISSUE THREAD

**Issue by devurandom** [GitJournal/GitJournal#400]
## Environment

**App version:** 1.73.10+2189
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: Fairphone
 - Model: FP3

## Description

When setting up a new "custom" host, I have the option to either "generate new keys" or to "provide custom ssh keys". If I chose the latter, I can "load from file".

**What you'd like to happen:**

I would like to store the keys in [OpenKeychain](https://www.openkeychain.org/) (https://github.com/open-keychain/open-keychain), so I can manage them securely in a central location, do not have to expose them as files and I can use ones that are stored on external devices (smartcards, keys).

**Comment by AutumnalAntlers** [comment]
Awesome idea! Seconded, wish I had the skills to help out as I imagine OpenKeychain has a pretty clear API

**Comment by vHanda** [comment]
I'm not keen on implementing this as OpenKeyChain is Android only. GitJournal currently supports both Android and iOS, and in the future - web + desktop.

Please feel free to open issues regarding what features you would like from OpenKeyChain in GitJournal. I could maybe implement some of those.

I'm leaving this open, as if someone contributes the code, I'll be open to merging it.
