### ISSUE TITLE
Click button "Discard Changes" get a error. need to deal with the boundary case

### ISSUE THREAD

**Issue by huang12zheng** [GitJournal/GitJournal#402]
## Environment

**App version:**    
* master

**Device information:**
```s
uname -a
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```
```
android
API 29 Pixel 4 XL
```

## Steps to reproduce

1. install app
2. add note(just writing something)
3. call a Modal
3.1. call _buildBottomMenuSheet 
4. click "Discard Changes"

---

I would slove if I have time. But issue first is better--how to handle this  boundary case

**Comment by vHanda** [comment]
I think this is something specific to the desktop build. I have an idea why this is not working. For now, I'm not supporting GitJournal desktop. So I'm going to close this.

**Comment by vHanda** [comment]
Could you please share the error? I just tried it out and I don't see any error.

**Comment by huang12zheng** [comment]
Vhande, I'm sorry. I'm new to GitJournal.

* I now know that “Discard Changes” is a discard change in Git.
In other way,
* I thought it was like undo in the editor. like vscode

You can `close it`. Or,
Do you think adding an `undo feature` will provide a better user experience

![截屏2021-01-29 下午1 06 24 (2)](https://user-images.githubusercontent.com/28038074/106234505-ed5bc280-6233-11eb-9c27-b02b9137d595.png)

**Comment by huang12zheng** [comment]
some lib could do it.
https://github.com/rodydavis/undo
or
https://pub.dev/packages/replay_bloc

**Comment by vHanda** [comment]
Closing for #242

I've implemented a very basic undo / redo for just the Raw Editor. It'll take some more work to implement it for the Markdown Editor and Checklist. It also needs lots of improvements as the undo is too fine grained.
