### ISSUE TITLE
Enable Image Zooming

### ISSUE THREAD

**Issue by ModProg** [GitJournal/GitJournal#410]
Images that are very small e.g. in Tables:
![grafik](https://user-images.githubusercontent.com/11978847/106395555-1da58b80-6403-11eb-8f61-2456f6065ff7.png)
May be hard to see on small phone screens. 

They could be shown in a full screen view or as an Overlay, that can be closed by tapping.

Additionaly in this preview they should be zoomable by dragging.

https://pub.dev/packages/photo_view

**Comment by MisterY** [comment]
Why limit this to "small" images?
Opening an image view should work for any image, I guess. What matters is the content of the image and the size of the screen, not the size of the image itself.

**Comment by ModProg** [comment]
The  implementation I chose, defines small image as everything smaller than `screenwidth - 40`.

An image that already is the full width cannot be enlarged, as there is no additional zoom functionality.

But I think that should probably be added aswell as some images are even on full width still too small.

**Comment by ModProg** [comment]
This could be used in future: https://pub.dev/packages/photo_view

**Comment by MisterY** [comment]
Should we create a separate issue or continue with this one (you should probably adjust the title, in that case)?
I was just about to suggest the regular image zoom, exactly as in the library you found. In my case, I have some diagrams and tables that can never be previewed in the screen size and simply have to be zoomed-in to be able to read, when previewing on a mobile device.

**Comment by ModProg** [comment]
I edited this issue.
