### ISSUE TITLE
markdown layer on top of pdf-attachments

### ISSUE THREAD

**Issue by JJger148** [GitJournal/GitJournal#411]
I would love to have a markdown layer on top of attached PDFs.

Highlights could be turned into [[links]], hashtags could be added and highlighted blocks could be referenced.

**Comment by vHanda** [comment]
Hi. This sounds quite challenging as dealing with PDF files is more complex. I'm not going to look at it right now, but I'm leaving it open in case someone else wants to look at it.

PS: If you gather enough votes, I will look into it!

**Comment by JJger148** [comment]
[Keynotes](https://keypoints.app/blog/) is a nice example of what I am looking for, the problem is, that so far it has not been released and it is not open source.

**Comment by datavistics** [comment]
I believe https://github.com/burtonator/polar-bookshelf has solved this.

**Comment by vHanda** [comment]
I'm closing this issue as this is kinda awesome -

> I believe https://github.com/burtonator/polar-bookshelf has solved this.

**Comment by JJger148** [comment]
It has amazing features indeed, but I guess many move away from cloud based applications like Notion and thus also polar-bookshelf.

**Comment by datavistics** [comment]
@vHanda , I think @JJger148 is right. While it has solved parts of it, it forces you into a  rigid workflow. It would be nice to abstract the capabilities away.
