### ISSUE TITLE
Failed, not a git repo... On my smartphone

### ISSUE THREAD

**Issue by aaronxn** [GitJournal/GitJournal#425]
I'm trying to set up a GitHub repo to sync my GitJournal entries between my devices. My journal is on my Galexy S20 Ultra, and I have Store Repo Externally turned on. Every time I try to setup Github, I get the following error message: Failed. Not a git repo. (See screenshot)

I've tried automatic setup, and custom/manual setup. Both have the same error. 

I'm using version 1.74.1+2278

![Screenshot_20210226-214103_GitJournal](https://user-images.githubusercontent.com/15862474/109375782-90781a00-787c-11eb-8993-131fb7cc47d4.png)

**Comment by vHanda** [comment]
Would you mind attaching the debug log as well, please? (Settings -> Debug)

Also could you also please try setting up GitHub first and then enabling 'Store Repo Externally'?

**Comment by vHanda** [comment]
Hi. Please let me know if you're still encountering this issue.
