### ISSUE TITLE
Remember the position when switching to Edit mode

### ISSUE THREAD

**Issue by MisterY** [GitJournal/GitJournal#431]
## Description

**What you'd like to happen:**

When switching the note from Preview to Edit mode, I would like to stay at the same (or close to) the position in the document where I was in the Preview mode. This really helps editing large documents and would be great with #14.

Currently, when switching to Edit mode, the document opens at the top.
When going back to Preview mode, it also starts at the top, losing the position in either direction.

**Comment by vHanda** [comment]
Closing in favor of https://github.com/GitJournal/GitJournal/issues/324 . Could you please vote on it?
