### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by MisterY** [GitJournal/GitJournal#440]
Hi! I've followed the environment setup instructions and have finished everything except for the NDK part. This should not affect Dart files, I hope.
Now I have 4 build errors:

![image](https://user-images.githubusercontent.com/462445/109871816-e1688380-7c6b-11eb-9695-bc1ad498c9f3.png)

Any hints on how to resolve these? I'd like to help out with some of the issues that I'm experiencing (location of the folder, pinning, search, etc.).
Thanks for the clear instructions!

**Comment by MisterY** [comment]
OK, I have to clarify,

with the current repo,  I get

![image](https://user-images.githubusercontent.com/462445/109872252-75d2e600-7c6c-11eb-9e93-c245319ac240.png)

When I upgrade intl to 0.17.0, I get

![image](https://user-images.githubusercontent.com/462445/109872315-8c793d00-7c6c-11eb-913c-f9d76e569805.png)

Apart from that, I've upgraded the flutter_markdown plugin, hence the additional two errors in the first post.

**Comment by MisterY** [comment]
The issue with intl solved https://github.com/flutter/flutter/issues/49931
added `  intl: 0.17.0-nullsafety.2` to overrides.

**Comment by vHanda** [comment]
I'm kinda surprised you're getting build errors given that the CI is green. I'll take a look later today or early tomorrow.

**Comment by MisterY** [comment]
Down to 2

![image](https://user-images.githubusercontent.com/462445/109874634-a8caa900-7c6f-11eb-83e3-d4706b094070.png)

**Comment by MisterY** [comment]
> 
> 
> I'm kinda surprised you're getting build errors given that the CI is green. I'll take a look later today or early tomorrow.

@vHanda No worries. I'm probably done for today. Will get back to this in the coming days, hopefully.

**Comment by MisterY** [comment]
I managed to make it build. Couple of notes, though. Had to comment-out

![image](https://user-images.githubusercontent.com/462445/109985443-09f08c00-7d05-11eb-935e-53d2c7694e89.png)

also, the methods in the Badge seem to have been renamed. Not sure why this happens when the versions are specified in the config.

![image](https://user-images.githubusercontent.com/462445/109985517-2096e300-7d05-11eb-96b0-4289cf710bd7.png)

Additionally, I had to comment-out half the isolates_workaround.dart.

**Comment by MisterY** [comment]
![image](https://user-images.githubusercontent.com/462445/110088428-23d9af80-7d95-11eb-8d41-43551fcb004a.png)

**Comment by MisterY** [comment]
The only remaining issue is with isolates_workaround.dart. I have commented-out the whole implementation to resolve the build problem but I don't know what the real solution would be.

**Comment by vHanda** [comment]
This should be fixed now.
