### ISSUE TITLE
Iconsistent Casing and Order in Localisation File

### ISSUE THREAD

**Issue by ModProg** [GitJournal/GitJournal#442]
The localisation file should probably be cleaned up at some point.
There is a lot of inconsistent casing and overall structure.

`folder_view`, `rootFolder`, `SortingOrderSelector`

Of course nothing urgent.

**Comment by vHanda** [comment]
Cleaning this meaning updating some 10 files (will increase over time). It would certainly be nice to have, but it's not worth the time effort for me, right now. Unless one can automate it.

**Comment by ModProg** [comment]
@vHanda I think some things can be automated, for example preparing all the language files, but a lot of things inside the code would need to be done by hand.

I have a deno script for something similar. 
It could be used to clean the language files.

I will link it here when I'm done with work.
