### ISSUE TITLE
External Location: Do not append 'GitJournal/repoName'

### ISSUE THREAD

**Issue by MisterY** [GitJournal/GitJournal#449]
## Description

As noted in #448, the selected location path appends GitJournal/journal to the selected folder.

**What you'd like to happen:**

The root notes folder should be the selected one (Notes), not a subfolder.

**Images:**

![image](https://user-images.githubusercontent.com/462445/110102516-2cd27d00-7da5-11eb-86bf-526b3d30fc6c.png)

**Comment by vHanda** [comment]
This makes sense in the case where the user has chosen the directory and that directory is writable. If we're defaulting to another directory then I would like to still append 'GitJournal/$repoName$'
