### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by MisterY** [GitJournal/GitJournal#465]
I'd like to resolve the build issues that I'm having. The earlier fixes I had applied only seem to create more problems with new versions of the code. I.e.
![image](https://user-images.githubusercontent.com/462445/110939176-4c355100-8335-11eb-8aa1-d5a5b6bc129f.png)

So, I'm resetting to a clean master branch. The first issue is this:

![image](https://user-images.githubusercontent.com/462445/110940239-dd58f780-8336-11eb-9cf3-0a8be56a75ac.png)

I have the current Flutter v2.0.0 and the SDK is on stable branch. 

![image](https://user-images.githubusercontent.com/462445/110941003-ff06ae80-8337-11eb-837a-59009e4d59b9.png)

**Comment by MisterY** [comment]
Here are the versions of the SDK, which can be specified manually:

https://github.com/flutter/flutter/tags

What would be the version that GitJournal is currently being built on?

Ref: https://stackoverflow.com/questions/49468321/how-to-downgrade-flutter-sdk-dart-1-x

**Comment by MisterY** [comment]
Trying 1.22.6

**Comment by MisterY** [comment]
![image](https://user-images.githubusercontent.com/462445/110943343-65d99700-833b-11eb-9984-40d70cdf074d.png)

which gets solved with

```
classpath 'com.android.tools.build:gradle:3.5.4'
```
~test~

**Comment by vHanda** [comment]
The CI is currently running 1.22.1 and I'm on 1.22.5.

**Comment by MisterY** [comment]
![image](https://user-images.githubusercontent.com/462445/110943895-062fbb80-833c-11eb-9363-c9b34c59f181.png)

just documenting, for now.

I believe the Build file should be updated with the version information for Flutter SDK. Also, Gradle 3.5.0 has some issues.

**Comment by MisterY** [comment]
As for Flutter, I get 678 errors

![image](https://user-images.githubusercontent.com/462445/110944049-35462d00-833c-11eb-9ca7-366363502e2f.png)

**Comment by vHanda** [comment]
> ![image](https://user-images.githubusercontent.com/462445/110943895-062fbb80-833c-11eb-9363-c9b34c59f181.png)
> 
> just documenting, for now.
> 
> I believe the Build file should be updated with the version information for Flutter SDK. Also, Gradle 3.5.0 has some issues.

This is a code signing issue. Not a build problem. Can you please follow the exact steps as the CI?

**Comment by MisterY** [comment]
> 
> This is a code signing issue. Not a build problem. Can you please follow the exact steps as the CI?

That's exactly what I did initially. But it never worked.

**Comment by MisterY** [comment]
ok, now running from the command line works. Will have to check the vscode commands later.

**Comment by vHanda** [comment]
About the Flutter version, I would ideally like to wait till 2.0.2 or so. But maybe we can risk it and update.

**Comment by MisterY** [comment]
> 
> 
> About the Flutter version, I would ideally like to wait till 2.0.2 or so. But maybe we can risk it and update.

Only if you want to keep fixing things. :D
Just updating the build.md should do for now.
But perhaps it would work. There is just one build issue, with isolates workaround. Perhaps that's not even needed after v2.

**Comment by MisterY** [comment]
OK, everything works now. 
Conclusion:

- add Flutter SDK version to Build.md. The default for download is v2 and it introduces build issues.
- gradle 3.5.4 also required in build.gradle
