### ISSUE TITLE
Login Screen in darkmode has bad contrast

### ISSUE THREAD

**Issue by ModProg** [GitJournal/GitJournal#467]
In dark mode, the text and the textfield in the login screen have almost the same color.

![](https://i.imgur.com/lO4oEel.jpg)

**Comment by signedav** [comment]
When highlighting the text in darkmode the contrast is bad as well.

![Screenshot_20210812-224238_GitJournal](https://user-images.githubusercontent.com/28384354/129267722-1b1903f7-e9b3-4acb-920f-9ee9a41913d8.jpg)

Not sure if directly related with the login screen, but I think it goes in the same direction.

**Comment by vHanda** [comment]
Fixed with 1.80

**Comment by signedav** [comment]
Works perfectly. Thanks a lot for the good work on this nice product.
