### ISSUE TITLE
Allow changing Note type

### ISSUE THREAD

**Issue by MisterY** [GitJournal/GitJournal#474]
To complete #463, I would like to be able to simply rename notes and therefore change the note type from Markdown into OrgMode.

Currently (https://github.com/GitJournal/GitJournal/blob/e32bf4004eddea82421d65a3b422bfb81e7369cd/lib/core/note.dart#L446), this is now allowed. 
What would be the preferred way to do this? 

- A pop-up, prompting the user to confirm the note type change?
- Just rename, no questions asked
  - do we reload the note and apply a different parser after this?
- have some other way of changing the note type

I think we should also make a distinction between a Note type and the Editor. 
As we mentioned on Discord, perhaps there is no need for the Serializer at all? All the supported note types are plain text files.

**Comment by vHanda** [comment]
The current way it works is that the last editor which has modifications made saves the 'type' accordingly. How about we introduce an OrgEditor and make that save the type?

**Comment by MisterY** [comment]
OK, let's try that route. Just added an OrgEditor and will expand the functionality based on that.
