### ISSUE TITLE
can't search in subfolder

### ISSUE THREAD

**Issue by eallion** [GitJournal/GitJournal#48]
can't search in subfolder

**Comment by vHanda** [comment]
Hey Charles.

Could you please elaborate? I just tried it out, and it seems to be working
fine.

**Comment by eallion** [comment]
![photo_2019-12-25_17-40-11](https://user-images.githubusercontent.com/1698841/71441743-b6b49e00-273d-11ea-8482-a70c7df401e7.jpg)

> This screenshot is my GitJournal repo.

If I go into a subfolder named `blockchian`, i can't search a note in `Nginx vhost confs` or other, and there is only one note  in the root directory `Notes`, it is the default repo's `README.md`.

**Comment by eallion** [comment]
![FireShot Capture 001 - eallion_journal_ Git Notes via Typora   Gitjournal - github com](https://user-images.githubusercontent.com/1698841/71442119-88d05900-273f-11ea-9702-ab54a36c3c28.png)

This is my GitJournal repo, it forks from another repo of mine.

**Comment by vHanda** [comment]
So what you mean is that you can search in the 'Nginx' folder after you enter it, and you can search in the 'Blockchain' folder after entering it, but there is no way to search in the 'Blockchain' folder when you're inside the 'Nginx' folder? Is that correct?

Additionally, there is also no way to search inside all the folders?

**Comment by eallion** [comment]
almost

**Comment by vHanda** [comment]
Could you please describe a solution which would solve this issue?

**Comment by eallion** [comment]
maybe you can create a search button on the top right

**Comment by eallion** [comment]
maybe you can reate a global search function, search notes anytime anywhere anyfolder

**Comment by vHanda** [comment]
> maybe you can reate a global search function, search notes anytime anywhere anyfolder

I agree. I'll work on it :) Thanks for the suggestion.

**Comment by eallion** [comment]
thanks for your reply. i'll keep this app in my phone.
