### ISSUE TITLE
 New app icon in iOS 

### ISSUE THREAD

**Issue by 1001ruchka** [GitJournal/GitJournal#482]
Gitjournal version 1.75.1 ios. The app icon has changed. Now, instead of a large green notebook, a small notebook with dark borders. In my opinion, the previous icon was more successful.

**Comment by vHanda** [comment]
Yeah. I wanted all platforms to have the same icon. But now looking back the brown border does look hideous. I'll revert back to the old one. Though I really dislike how it looks on ios.

iOS icon must be a square and the normal GitJournal icon doesn't qualify
