### ISSUE TITLE
Refactor for extensibility

### ISSUE THREAD

**Issue by alensiljak** [GitJournal/GitJournal#486]
While trying to support .org files, I ran into too many walls. Currently I'm having troubles to understand the meaning of Note, Doc, Serializer, Codec. These all have the same abstract meaning to me, somehow.
Since the Yaml/Markdown is at the heart of it, a significant refactoring is required in order to support additional file types, even if they are stored in a simple text format in the end.
In order to work on .org support, I would like to extend some base class and add Org-specific features or formatting to it. Currently I don't dare to refactor the above-mentioned classes as I don't have an overview of how this is supposed to work.
Perhaps interface could be used instead of the suggested base class. This does not make too much practical difference.
I could help on this but would appreciate some directions first.

**Comment by vHanda** [comment]
Closing this as I'm now only tracking real bugs over here.

Feature requests are now in Discussions. Plus, I've been slowly working on this, but there is a lot to do. It's high in my list.
