### ISSUE TITLE
Multi Note selection and Context Menu

### ISSUE THREAD

**Issue by ModProg** [GitJournal/GitJournal#488]
Currently, if you long press a note this mode opens where you can share and delete a note. You can't select multiple notes.

![](https://i.imgur.com/Faa6XKv.jpg)

I would propose a popup menu for single Note operations.

![](https://i.imgur.com/A6xwuRI.jpg)

And a button in the top or bottom bar to select multiple.

Or allow selecting multiple when long pressing one, but maybe put actions in a floating action button.

![](https://i.imgur.com/3ci6Pmw.jpg)

**Comment by vHanda** [comment]
Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/90
