### ISSUE TITLE
crash on start on lineageos 17.1

### ISSUE THREAD

**Issue by fekir** [GitJournal/GitJournal#489]
## Environment

**App version:**  1.75.1
**Device information:** Moto G5
 - OS name and version: Lineageos 17.1 (Android 10)
 - Manufacturer: Motorola
 - Model: G5
 - 
For what is worth, I noticed the same behavior on another Lineageos 17.1 device  (Samsung based) 

## Description

**Expected behavior:**

App should start

**Current behavior:**

Logo of gitjournal appears, then disappears. If trying to open app again a dialog of theOS appears with the text "GitJournal keeps stopping".

## Steps to reproduce

1. Open App

## othe info

see attached logcat output (hopefully it contains useful informations)
[journal.txt](https://github.com/GitJournal/GitJournal/files/6253272/journal.txt)

**Comment by MisterY** [comment]
> couldn't find "libflutter.so"

It could be that GApps are adding this, since I'm on Lineage with GApps and everything seems to work.

**Comment by fekir** [comment]
I do not have a device with lineageos 17, so I do not know if it makes sense to keep this issue open (I cannot test) as no-one else reported it.

I did in fact not have GApps.

**Comment by MisterY** [comment]
Thanks for the info. I can confirm that on 17.1 with GApps everything works fine. Been using it daily for a couple of years.

**Comment by vHanda** [comment]
This no longer seems to be an issue in the latest version.
