### ISSUE TITLE
App won't start beyond loading screen

### ISSUE THREAD

**Issue by rgutzen** [GitJournal/GitJournal#496]
## Environment

**App version:**  1.75.1
**Device information:**
 - OS name and version: Android 9
 - Manufacturer: LG
 - Model: H870

## Description

I've been using the GitJournal app on mobile for some time, and absolutely loving it. However, since a while, it won't open properly anymore. When starting the app, it just shows the loading screen (the logo) without progressing to the interface or showing an error message. Reinstalling the app didn't help yet. 
I'm sorry that I can't provide a more helpful bug report.

**Comment by vHanda** [comment]
Hey. Sorry, I didn't land up responding.

Did GitJournal ever start working for you?

**Comment by rgutzen** [comment]
Thank you for responding, the issue still persists.
Unfortunately, I don't remember exactly at which version the app stopped working on my device.

**Comment by yumiris** [comment]
Similar issue here; see: https://github.com/GitJournal/GitJournal/issues/512

**Comment by dflock** [comment]
This also happens to me. Everything was working fine on my old phone (Pixel XL, Android 11). I just got a Pixel 3XL with Android 12. When I start GitJournal, I get this:

![Screenshot_20211211-175546.png](https://user-images.githubusercontent.com/47756/145697524-d1ff9ffb-f0af-468d-bfd4-cb9e2f1d9d4b.png)

It just stays like that forever.

The first time I ran it, I had the `/storage/emulated/0/GitJournal/journal` folder there, copied over from my old phone. I got the front zen loading screen on startup. I renamed the folder to this: `/storage/emulated/0/_GitJournal` and tried again - same thing. It doesn't create a new `/storage/emulated/0/GitJournal` folder on startup either.

**Comment by vHanda** [comment]
Fixed.

Unfortunately, I cannot push a new version until I manage to contact someone from Google as my app keeps getting automatically rejected and appeals are being ignored.

Till then, please consider Installing F-Droid and using the app from there - https://gitjournal.io/fdroid_how_to/ . This way you can also (optionally) installed the development version.

**Comment by dflock** [comment]
This is indeed fixed for me on the dev version from FDroid - thanks!

**Comment by vHanda** [comment]
I've also just released a new version `1.82` in FDroid!
