### ISSUE TITLE
bug: when within a folder the `journal editor` > `default folder` config doesn't apply

### ISSUE THREAD

**Issue by janaka** [GitJournal/GitJournal#499]
## Environment

**App version:** 1.75.1+2324 Pro version
**Device information:**
 - Android version: 11
 - Manufacturer: Google
 - Model: Pixel5

## Description

**Expected behavior:**
new journal entries are always created in the folder configured under the journal editor default folder settings

**Current behavior:**
When in all notes view works correctly. When in a particular folder clicking the new journal entry button creates the fine in the selected folder.

## Steps to reproduce
menu > `folders` > select any folder.
Hit the new journal button on the bottom menu
new entry will be in the select folder/

## Others   

Images

<details>
  <summary>Logs</summary>

```
```

```
```
</details>

**Comment by vHanda** [comment]
Hmm, I'm not sure about this.

In a way it makes sense that journal entries should always go to that folder. I had assumed that since you are in a particular folder, you would want to create the journal in that folder.
