### ISSUE TITLE
The app gets crashes when I delete the journal entry

### ISSUE THREAD

**Issue by friendsmobile** [GitJournal/GitJournal#5]
# Project Information

* Repository: https://github.com/GitJournal/GitJournal
* Project Name: GitJournal
* My Github Account: https://github.com/friendsmobile

# Expected behavior
Journal entry should be completely removed when I delete the journal entry

# Actual behavior

The app gets crashes when I delete the journal entry

# How to reproduce

* Download the app 
* open the application
* click on the plus button and Create a journal entry
* Open the journal entry that you have made
* Click on the Delete icon and try to delete the entry
* Note the BUG

* Browser/App version: Current Version 1.1.1
* Operating system: 6.0

# Recording Of The Bug

![20190529_033652](https://user-images.githubusercontent.com/51118734/58516967-9ba98d80-815e-11e9-8d77-3c782300cad2.gif)

**Comment by vHanda** [comment]
Hi. Thanks a lot for the detailed bug report.

Unfortunately I cannot seem to reproduce it. Would it be possible to attach the `adb logs` from the phone? You'll need to connect it via a cable, enable developer mode, and run `adb logcat`.

In parallel, I'm working on integrating an automatic crash reporting service with all the relevant details, so this reporting will be easier.

**Comment by friendsmobile** [comment]
<pre><code> 05-29 15:54:47.795  6755  6755 I dumpstate: dumpstate is still running

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:47.965  1020  1045 W ActivityManager: Activity pause timeout for ActivityRecord{2725cacd u0 io.gitjournal.gitjournal/.MainActivity t5 f}

05-29 15:54:47.965  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:47.965  1020  1045 W ActivityManager: mDVFSHelper.acquire()

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: setCurrentAppOrientation :5

05-29 15:54:47.975  1020  1045 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:47.975  1020  1045 V WindowManager: rotationForOrientationLw(orient=5, last=0); user=0 USER_ROTATION_LOCKED

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: getProposedRotation : mEnabled = false, mUseScreenOrientationSensor =true

05-29 15:54:47.975  1020  1045 D PowerManagerService: setKeyboardVisibility: false

05-29 15:54:47.985  1910  1910 V Launcher: Launcher.onResume()

05-29 15:54:47.985  1020  1134 D ActivityManager: post active user change for 0 fullscreen true

05-29 15:54:47.985  1020  1134 D KnoxTimeoutHandler: postActiveUserChange for user 0

05-29 15:54:47.985  1020  1134 I KnoxTimeoutHandler: postActiveUserChange, showWhenLocked: false

05-29 15:54:47.985  1020  1020 D KnoxTimeoutHandler: handleActiveUserChange for user 0

05-29 15:54:47.985  1020  1508 D ActivityManager: retrieveServiceLocked(): component = com.google.android.gms/com.google.android.gms.lockbox.LockboxService; callingUser = 0; userId(target) = 0

05-29 15:54:47.985  1020  1020 D PersonaManagerService: getPersonasForUser(): returning null!

05-29 15:54:47.995   249   249 I SurfaceFlinger: id=40 createSurf (1x1),1 flag=4, TurfaceView

05-29 15:54:48.005   249   249 I SurfaceFlinger: id=41 createSurf (720x1280),1 flag=4, Mauncher

05-29 15:54:48.055  1910  1910 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@144f4a9a time:277501

05-29 15:54:48.065  2064  6756 D DisplayManager: DisplayManager()

05-29 15:54:48.065  2064  6756 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:48.325  1020  1050 W ActivityManager: mDVFSHelper.release()

05-29 15:54:48.335  1020  1050 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{39533496 u0 com.s9launcher.galaxy.launcher/com.s9.launcher.Launcher t2} time:277780

05-29 15:54:48.335  1020  1045 I ActivityManager: Killing 4711:io.partiko.android/u0a123 (adj 15): empty #31

05-29 15:54:48.335  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:48.695  3211  3211 D HeadsetPhoneState: Signal level : previous=1 curr=2

05-29 15:54:48.695  1210  1210 D StatusBar.MSimNetworkController: getNumberOfActiveSim:1 05-29 15:54:47.795  6755  6755 I dumpstate: dumpstate is still running

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:47.965  1020  1045 W ActivityManager: Activity pause timeout for ActivityRecord{2725cacd u0 io.gitjournal.gitjournal/.MainActivity t5 f}

05-29 15:54:47.965  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:47.965  1020  1045 W ActivityManager: mDVFSHelper.acquire()

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: setCurrentAppOrientation :5

05-29 15:54:47.975  1020  1045 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:47.975  1020  1045 V WindowManager: rotationForOrientationLw(orient=5, last=0); user=0 USER_ROTATION_LOCKED

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: getProposedRotation : mEnabled = false, mUseScreenOrientationSensor =true

05-29 15:54:47.975  1020  1045 D PowerManagerService: setKeyboardVisibility: false

05-29 15:54:47.985  1910  1910 V Launcher: Launcher.onResume()

05-29 15:54:47.985  1020  1134 D ActivityManager: post active user change for 0 fullscreen true

05-29 15:54:47.985  1020  1134 D KnoxTimeoutHandler: postActiveUserChange for user 0

05-29 15:54:47.985  1020  1134 I KnoxTimeoutHandler: postActiveUserChange, showWhenLocked: false

05-29 15:54:47.985  1020  1020 D KnoxTimeoutHandler: handleActiveUserChange for user 0

05-29 15:54:47.985  1020  1508 D ActivityManager: retrieveServiceLocked(): component = com.google.android.gms/com.google.android.gms.lockbox.LockboxService; callingUser = 0; userId(target) = 0

05-29 15:54:47.985  1020  1020 D PersonaManagerService: getPersonasForUser(): returning null!

05-29 15:54:47.995   249   249 I SurfaceFlinger: id=40 createSurf (1x1),1 flag=4, TurfaceView

05-29 15:54:48.005   249   249 I SurfaceFlinger: id=41 createSurf (720x1280),1 flag=4, Mauncher

05-29 15:54:48.055  1910  1910 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@144f4a9a time:277501

05-29 15:54:48.065  2064  6756 D DisplayManager: DisplayManager()

05-29 15:54:48.065  2064  6756 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:48.325  1020  1050 W ActivityManager: mDVFSHelper.release()

05-29 15:54:48.335  1020  1050 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{39533496 u0 com.s9launcher.galaxy.launcher/com.s9.launcher.Launcher t2} time:277780

05-29 15:54:48.335  1020  1045 I ActivityManager: Killing 4711:io.partiko.android/u0a123 (adj 15): empty #31

05-29 15:54:48.335  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:48.695  3211  3211 D HeadsetPhoneState: Signal level : previous=1 curr=2

05-29 15:54:48.695  1210  1210 D StatusBar.MSimNetworkController: getNumberOfActiveSim:105-29 15:54:47.795  6755  6755 I dumpstate: dumpstate is still running

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:47.965  1020  1045 W ActivityManager: Activity pause timeout for ActivityRecord{2725cacd u0 io.gitjournal.gitjournal/.MainActivity t5 f}

05-29 15:54:47.965  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:47.965  1020  1045 W ActivityManager: mDVFSHelper.acquire()

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: setCurrentAppOrientation :5

05-29 15:54:47.975  1020  1045 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:47.975  1020  1045 V WindowManager: rotationForOrientationLw(orient=5, last=0); user=0 USER_ROTATION_LOCKED

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: getProposedRotation : mEnabled = false, mUseScreenOrientationSensor =true

05-29 15:54:47.975  1020  1045 D PowerManagerService: setKeyboardVisibility: false

05-29 15:54:47.985  1910  1910 V Launcher: Launcher.onResume()

05-29 15:54:47.985  1020  1134 D ActivityManager: post active user change for 0 fullscreen true

05-29 15:54:47.985  1020  1134 D KnoxTimeoutHandler: postActiveUserChange for user 0

05-29 15:54:47.985  1020  1134 I KnoxTimeoutHandler: postActiveUserChange, showWhenLocked: false

05-29 15:54:47.985  1020  1020 D KnoxTimeoutHandler: handleActiveUserChange for user 0

05-29 15:54:47.985  1020  1508 D ActivityManager: retrieveServiceLocked(): component = com.google.android.gms/com.google.android.gms.lockbox.LockboxService; callingUser = 0; userId(target) = 0

05-29 15:54:47.985  1020  1020 D PersonaManagerService: getPersonasForUser(): returning null!

05-29 15:54:47.995   249   249 I SurfaceFlinger: id=40 createSurf (1x1),1 flag=4, TurfaceView

05-29 15:54:48.005   249   249 I SurfaceFlinger: id=41 createSurf (720x1280),1 flag=4, Mauncher

05-29 15:54:48.055  1910  1910 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@144f4a9a time:277501

05-29 15:54:48.065  2064  6756 D DisplayManager: DisplayManager()

05-29 15:54:48.065  2064  6756 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:48.325  1020  1050 W ActivityManager: mDVFSHelper.release()

05-29 15:54:48.335  1020  1050 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{39533496 u0 com.s9launcher.galaxy.launcher/com.s9.launcher.Launcher t2} time:277780

05-29 15:54:48.335  1020  1045 I ActivityManager: Killing 4711:io.partiko.android/u0a123 (adj 15): empty #31

05-29 15:54:48.335  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:48.695  3211  3211 D HeadsetPhoneState: Signal level : previous=1 curr=2

05-29 15:54:48.695  1210  1210 D StatusBar.MSimNetworkController: getNumberOfActiveSim:1 05-29 15:54:47.795  6755  6755 I dumpstate: dumpstate is still running

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:47.815  1020  1020 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:47.965  1020  1045 W ActivityManager: Activity pause timeout for ActivityRecord{2725cacd u0 io.gitjournal.gitjournal/.MainActivity t5 f}

05-29 15:54:47.965  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:47.965  1020  1045 W ActivityManager: mDVFSHelper.acquire()

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: setCurrentAppOrientation :5

05-29 15:54:47.975  1020  1045 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:47.975  1020  1045 V WindowManager: rotationForOrientationLw(orient=5, last=0); user=0 USER_ROTATION_LOCKED

05-29 15:54:47.975  1020  1045 V WindowOrientationListener: getProposedRotation : mEnabled = false, mUseScreenOrientationSensor =true

05-29 15:54:47.975  1020  1045 D PowerManagerService: setKeyboardVisibility: false

05-29 15:54:47.985  1910  1910 V Launcher: Launcher.onResume()

05-29 15:54:47.985  1020  1134 D ActivityManager: post active user change for 0 fullscreen true

05-29 15:54:47.985  1020  1134 D KnoxTimeoutHandler: postActiveUserChange for user 0

05-29 15:54:47.985  1020  1134 I KnoxTimeoutHandler: postActiveUserChange, showWhenLocked: false

05-29 15:54:47.985  1020  1020 D KnoxTimeoutHandler: handleActiveUserChange for user 0

05-29 15:54:47.985  1020  1508 D ActivityManager: retrieveServiceLocked(): component = com.google.android.gms/com.google.android.gms.lockbox.LockboxService; callingUser = 0; userId(target) = 0

05-29 15:54:47.985  1020  1020 D PersonaManagerService: getPersonasForUser(): returning null!

05-29 15:54:47.995   249   249 I SurfaceFlinger: id=40 createSurf (1x1),1 flag=4, TurfaceView

05-29 15:54:48.005   249   249 I SurfaceFlinger: id=41 createSurf (720x1280),1 flag=4, Mauncher

05-29 15:54:48.055  1910  1910 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@144f4a9a time:277501

05-29 15:54:48.065  2064  6756 D DisplayManager: DisplayManager()

05-29 15:54:48.065  2064  6756 D DisplayManager: addAllDisplaysLocked()

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  tag : ACTIVITY_RESUME_BOOSTER@4

05-29 15:54:48.325  1020  1050 D CustomFrequencyManagerService: FrequencyrequestList.getNextCStateDisableRequest, index: 0

05-29 15:54:48.325  1020  1050 W ActivityManager: mDVFSHelper.release()

05-29 15:54:48.335  1020  1050 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{39533496 u0 com.s9launcher.galaxy.launcher/com.s9.launcher.Launcher t2} time:277780

05-29 15:54:48.335  1020  1045 I ActivityManager: Killing 4711:io.partiko.android/u0a123 (adj 15): empty #31

05-29 15:54:48.335  1020  1045 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1020  pkgName : ACTIVITY_RESUME_BOOSTER@10

05-29 15:54:48.695  3211  3211 D HeadsetPhoneState: Signal level : previous=1 curr=2

05-29 15:54:48.695  1210  1210 D StatusBar.MSimNetworkController: getNumberOfActiveSim:1
</code></pre>

**Comment by friendsmobile** [comment]
maybe this logcat help you to find bug

**Comment by vHanda** [comment]
Hi. Could you please try again with latest build? I've made modifications to automatically report crashes with proper symbols, so I can diagnose this better.

Sadly the logcat which you've attached doesn't have any relevant info.

**Comment by friendsmobile** [comment]
sir i was dowloaded latest version of the applicatiion but still bug has been avaliable please recheck the application

**Comment by friendsmobile** [comment]
i was try to gernate acurate logcat but i cannot to gernate logcat new i don,t know what is pronlem

**Comment by vHanda** [comment]
I've rewritten the note deletion code, and handled a few edge cases. Please re-open the bug if this still occurs with version `1.14`.
