### ISSUE TITLE
It does not respect the privacy settings of its own

### ISSUE THREAD

**Issue by gerroon** [GitJournal/GitJournal#506]
## Environment

**App version:** 1.76.1+2419
**Device information:** Samsung Note
 - OS name and version: Android 11
 - Manufacturer: Samsung

## Description
I disabled the Usage and Crash collection and it still tries to make queries to app-measurement.com and firebaseinstallations.googleapis.com

**Expected behavior:**
It should respect the preferences and the user privacy.

## Steps to reproduce

1. Disable Collect Anonymous Usage and Crash collections.

EDIT: Also it makes many dns queries frequently. Anyone who is using this app should be aware of this.

**Comment by vHanda** [comment]
Damn. I'm setting all the flags to disable firebase analytics. Maybe something has changed over there.

The firebase analytics code is closed source.

May I know how you traced the traffic? I would like to do the same.

**Comment by vHanda** [comment]
Based on https://github.com/firebase/quickstart-android/issues/370#issuecomment-600348127 it seems that even if analytics are disabled some events are still going to be sent.

This is horrible.

**Comment by gerroon** [comment]
Hi, thanks for the update. I edited my report, given there does not seem to be a malice here.

**Comment by vHanda** [comment]
I've removed firebase analytics. When I find an alternative, I'll make sure to do a more comprehensive test to make sure it isn't leaking any data. Thank you for bringing this to my attention.

I'll make a new release this week. There are still some changes I need to better test.

**Comment by finzzz** [comment]
Not sure if it will work or not, but why not rewrite all urls of those analytics to something like https://not.exist?

**Comment by vHanda** [comment]
> Not sure if it will work or not, but why not rewrite all urls of those analytics to something like https://not.exist?

Firebase analytics is closed source. I'm not sure how I would rewrite those urls. Or maybe I didn't understand what you meant.
