### ISSUE TITLE
No sync with fresh install, null icon & no error logs

### ISSUE THREAD

**Issue by lildata** [GitJournal/GitJournal#509]
## Environment

**App version:**  1.79.1+2419
**Device information:**
 - OS name and version: Android 10 (kernel 4.14.117)
 - Manufacturer: Nokia
 - Model: 5.3

## Description

Following the most obvious flow the app never sync anything in Github or Gitlab. The top-right "cloud" icon has a "null" label on top, which sometimes blink when trying to sync.
I tried to unistall the app & the process over several times.

**Expected behavior:**
- Sync of the note on Github or Gitlab
- Error logs in Settings / Debug App

**Current behavior:**
- No action in the git repo
- No logs in Settings / Debug App

## Steps to reproduce

- Install the app
- Setup Git Host
- Select Github or Gitlab
- Setup Automatically
- Authorize GitJournal
- Create private repo
(no error message during the process but already the top-right "cloud" icon has a "null" label on top)
- Create a note
![Screenshot from 2021-06-08 16-35-22](https://user-images.githubusercontent.com/7280019/121204956-90be8300-c877-11eb-8f83-5943f249ebae.png)

<details>
  <summary>Logs</summary>

```
```

```
```
</details>

**Comment by vHanda** [comment]
Could you please also use the report a bug button? Perhaps the logs are attached in the email and just not visible in the app?

**Comment by notorious-gay** [comment]
@vHanda is correct regarding the log. I'll try and upload when I'm at a desktop as I've got the same issue.

**Comment by notorious-gay** [comment]
Done some fiddling while on the train and I think I understand the issue. It seems to arise when the default branch is different than master. GitHub is pushing for folks to use main or trunk as the new master given the connotations of the old naming scheme.

The app seems to default to master but for some reason it's not being accepted by GitHub.

Steps to work around for a fresh repo:

1.  Create private repository on GitHub
2.  Commit a readme file to main via web interface
3.  Use automatic setup and select your pre initialised repo. The app will pick up the default branch when cloning.
4. Sync works (for me at least!)

Original error message in log was Remote has no refs, as per previous message I'll sanitise and upload the rest when home but for now this will hopefully let you get up and running @lildata 👌

**Comment by lildata** [comment]
@notorious-gay workaround works :1st_place_medal:  you need to first create the repo on Github & then connect the app !

**Comment by FlorianDold** [comment]
I've had the same problem with a self-hosted git repository. Syncing only started to work once I manually made an initial commit. With an empty repository, a "null" banner appears next to the sync icon and sync wouldn't work.

**Comment by vHanda** [comment]
I see.

Something probably broke with the null safety migration. This has been
happening way too frequently. I want automated tests to detect each of the
cases of cloning. There are many different cases. Here are some off the top
of my mind -

* No local commits, new repo
* Local commits, new repo
* Local commits, existing repo, same branch
* Local commits, existing repo - different branches.

**Comment by vrtmrz** [comment]
It happened to me too in this situation.
- Newly installed GItJournal.
- New repo on Gitea (repo created but no commits have been pushed).
- notes have been committed inside GItJournal.

**Comment by vHanda** [comment]
Fixed with `1.82`. Please let me know if you're still encountering any issues.

**Comment by edrex** [comment]
Now in 1.82.4 You can't get past a null error during the initial sync, which I suppose is better than allowing the user to proceed without sync working, but is still broken. GitJournal should be able to create an initial commit with the changes in the local copy.

After deleting and recreating my repository with a template commit on codeberg as @notorious-gay detailed doing above, I am hit by a **complete loss of local data** as the server side silently overwrites local changes rather than attempting to merge them, a behavior I'm going to guess was introduced as a fix for #473. Replacing one data loss mode with another probably less catastrophic one. I need to file a separate bug for that.
