### ISSUE TITLE
Resolving merge issues

### ISSUE THREAD

**Issue by mayjs** [GitJournal/GitJournal#51]
Hi, first of all thank you for creating this app, I've been looking for something like this before but never found anything that was this close to doing what I wanted.

That being said, while playing around and modifying my journal from another device I deliberately caused a merge conflict. Now I can't get GitJournal to synchronize with the repository anymore. Is there a feature to resolve the conflict? Just merging with git's `ours` or `theirs` strategy would be enough.

**Comment by addamove** [comment]
Any updates?
