### ISSUE TITLE
Opening Results in Blank Screen

### ISSUE THREAD

**Issue by yumiris** [GitJournal/GitJournal#512]
## Environment

**App version:**  1.75.2
**Device information:**
 - OS name and version: iOS 14.6
 - Manufacturer: Apple, Inc.
 - Model: iPhone SE

## Description

**Expected behavior:**

Opening GitJournal opens GitJournal.

**Current behavior:**

Opening GitJournal results in a perpetually white screen with nothing else happening or showing up.

## Steps to reproduce

1. Tap GitJournal
2. Blank Screen Appears
3. Suffer

## Others

| Screenshot |
|----------|
| ![image](https://user-images.githubusercontent.com/10241434/122097561-66099700-ce42-11eb-804b-f521baa729c3.png) |

Can't access logs; however, from memory, this started happening when I added an additional repository and tried syncing it to a remote Git server. The syncing didn't complete, and since then, GitJournal doesn't load at all. Seems to be a case of data corruption. I'd reinstall; however, I've got some important files which I haven't synced yet and losing them would equate to destroying the planet.

If there's any way I could get you more information, don't hesitate to let me know!

**Comment by vHanda** [comment]
Hey. I'm not sure what is going on, but I'll go over the startup code to try and workout all the paths that could result in something like this happening.

Please expect about a week. I'm testing a number of changes for the next release of GitJournal, and after that I'll look into this.

**Comment by yumiris** [comment]
Howdy, no problem at all. What might help is interrupting a cloning procedure and go from there. That's what happened in my case and might be the cause of the startup hang.

**Comment by yumiris** [comment]
GitJournal now starts again on version: `GitJournal 1.77.4+2602`

**Comment by vHanda** [comment]
I'm glad it's now working!
