### ISSUE TITLE
Create file watcher for desktop

### ISSUE THREAD

**Issue by nth-chile** [GitJournal/GitJournal#515]
See [this discussion](https://github.com/GitJournal/GitJournal/issues/137#issuecomment-855087651) for more info

## Environment

Ideally, MacOS, Windows and Linux

## Description

A file watcher application that runs in the background to keep a git repo in sync with a remote repo automatically. Saving a file should update the remote.

I think it would also require the opposite: when the remote updates, the local repo should update as well.

Also, the mobile app GitJournal should receive updates from the remote (if it doesn't already).

Repo will be here: https://github.com/GitJournal/git-auto-sync

**Comment by vHanda** [comment]
Fixed by `git-auto-sync`. Please file issues regarding it, in its repo.
