### ISSUE TITLE
Support for non-rsa ssh keys on Android app

### ISSUE THREAD

**Issue by craigfurman** [GitJournal/GitJournal#516]
## Environment

**App version:**
**Device information:**
 - OS name and version: Android
 - Manufacturer:
 - Model:

## Description

Is it possible to add support for more modern ssh key types on the Android app? When I tried to set up an ed25519 read-only deploy key to a GitHub repo, I received an error: "key does not start with ssh-rsa".

I'm not sure what the limitations on key type on the Android openssh client are, but what do you think of accepting any key string entered, and presenting any error to the user, rather than validating the start of the public key string? That would allow gitjournal users to use any supported key, but it's possible some user-friendliness would be lost.

**Comment by vHanda** [comment]
I don't want to reduce the user-friendliness for now, but you're right - GitJournal internally does support many more key types, and in other formats (such as PEM). And we aren't allowing that.

**Comment by craigfurman** [comment]
Thanks for the quick reply @vHanda, and that's fair about keeping the input validation. I noticed in https://github.com/GitJournal/GitJournal/commit/1b23cb4da92253f4a808f1541f42ea33153241e0 that ed25519 keys are still not allowed. Does GitJournal not support ed25519 internally?

**Comment by vHanda** [comment]
Hey @craigfurman : I checked, and we do support them - https://libssh2.org/changes.html#1.9.0

**Comment by craigfurman** [comment]
Great, that latest commit looks like it will allow ed25519 keys. I look forward to it landing in an Android app release. Nice app btw 👍
