### ISSUE TITLE
BackSpace not working on android devices which have hardware keyboard.

### ISSUE THREAD

**Issue by vrtmrz** [GitJournal/GitJournal#518]
## Environment

**App version:**  1.76.1+2419
**Device information:**
 - OS name and version: Android (Chrome OS)
 - Manufacturer:Lenovo
 - Model: IdeaPad duet

## Description

**Expected behavior:**
Backspace key works.
**Current behavior:**
Backspace key ignored.

## Steps to reproduce

1. Just install
2. Write something
3. We could't delete anything.

## Others   

It caused by Flutter's bug.
https://github.com/flutter/flutter/issues/78769

**Comment by vrtmrz** [comment]
I'm sorry that I couldn't have kept checking the latest version, it works well now!

**Comment by vHanda** [comment]
No worries. I'm glad it now works. Cheers!
