### ISSUE TITLE
It is not possible to make the text bold or italic for two or more words using the toolbar

### ISSUE THREAD

**Issue by 1001ruchka** [GitJournal/GitJournal#522]
## Environment

App version:** 1.77.4
OS name and version: iOS 14.6

## Description

It is not possible to make the text bold or italic for two or more words using the toolbar

https://user-images.githubusercontent.com/5934321/124768849-ad66dd00-df41-11eb-846d-488592280071.MP4

**Comment by vHanda** [comment]
Confirmed. I see a big 'todo' in the codebase for this.
