### ISSUE TITLE
Cloning new created repo on GitHub fails, since app expects master branch.

### ISSUE THREAD

**Issue by jasperslot** [GitJournal/GitJournal#524]
Hello. Could you please re-open this issue if it still occurs with version `1.74`?

_Originally posted by @vHanda in https://github.com/GitJournal/GitJournal/issues/418#issuecomment-784937529_

Hello, I just started to use the app and having the same issue. I created a few notes in gitjournal, then created a new repo on GitHub. But now it doesn't work, since I get the error "GitRefNotFound: refs/remotes/origin/master". This is a valid error, since the new default branch name is "main". So, I tried to change the branch within gitjournal, but it only shows master... I am using gitjournal GitJournal 1.77.4+2602 on Android.

**Comment by AyrtonRicardo** [comment]
@jasperslot the version 1.78.2+2665 is working without any issue.
I think if you just update your app it will work without any problem.

**Comment by vHanda** [comment]
Yup. This is fixed. I forgot to close it.
