### ISSUE TITLE
Search has stopped working

### ISSUE THREAD

**Issue by MisterY** [GitJournal/GitJournal#526]
## Environment

**App version:** 1.78.0 from the Play Store
**Device information:**
 - OS name and version: LineageOS 17.1
 - Manufacturer: Xiaomi
 - Model: Mi 9T

## Description

**Expected behavior:**

A search for the text within the notebook should show the matching notes.

**Current behavior:**

The search screen shows no results when a search term is typed-in.

## Steps to reproduce

1. Tap the search icon in the toolbar on the home screen
2. Type a term that exists in one of the notes

**Comment by vHanda** [comment]
I've pushed a fix with 1.78.1, but it's stuck in review.
