### ISSUE TITLE
Storing repo externally

### ISSUE THREAD

**Issue by sudhamjayanthi** [GitJournal/GitJournal#527]
Turning on store repo externally doesn't push changes to the remote updates files locally, is it a bug or is this the intended behaviour?

**Comment by vHanda** [comment]
Definitely a bug. Could you please share your debug logs. Settings -> Debug.

**Comment by vHanda** [comment]
Ping

Closing for now, as without additional info I can't fix this.

**Comment by sudhamjayanthi** [comment]
Hey sorry, I created this issue long back, can't remember the it properly and how you can reproduce it now. Sure, you can close it!

But just so you know, all I wanted to do was -- **setup a sync for [obsidian](https://obsidian.md/) b/w mobile and desktop** using github on a android(coolpad) phone and was NOT able to do it successfully. You can try doing the same and *might* find a issue or two.
