### ISSUE TITLE
Exception: Failed to fetch, exitCode: 128

### ISSUE THREAD

**Issue by orbanbalage** [GitJournal/GitJournal#528]
## Environment

**App version:**  Version 1.79.1 (2778)
**Device information:**
 - OS name and version: MacOS Catalina, 10.15.7 (19H1323)
 - Manufacturer: Apple
 - Model: MacbookPro

## Description

**Expected behavior:**
After pressing "Clone repo" the repo is cloned

**Current behavior:**
After some time while "Cloning..." is displayed;
it fails with the error code:
Failed 
Exception: Failed to fetch, exitCode: 128

## Steps to reproduce

1. Setup git repo
2. Choose gitlab, manual, add git URI, generate ssh keys
3. Clone Repo

<details>
  <summary>Logs</summary>

```lang-zsh
➜  sudo ./GitJournal -v
Password:
flutter: env GIT_SSH_COMMAND="ssh -i /tmp/PojkXv/key -o IdentitiesOnly=yes"
flutter: git fetch origin
The authenticity of host 'gitlab.com (172.65.251.78)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'gitlab.com,172.65.251.78' (ECDSA) to the list of known hosts.
remote: Enumerating objects: 2000, done.
remote: Counting objects: 100% (2000/2000), done.
remote: Compressing objects: 100% (1941/1941), done.
remote: Total 2000 (delta 33), reused 1943 (delta 18), pack-reused 0
Receiving objects: 100% (2000/2000), 200.48 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (33/33), done.
From gitlab.com:orbanbalage/notes
 * [new branch]      master     -> origin/master
flutter: env GIT_SSH_COMMAND="ssh -i /tmp/BBFOXV/key -o IdentitiesOnly=yes"
flutter: git fetch origin
From gitlab.com:orbanbalage/notes
 * [new branch]      master     -> origin/master
```

</details>

Note: the error was display already at the point of authorizing the gitlab ssh key – so at least after starting the app in verbose mode I was able to do that, so I got to actually sync the repo, and now there are no errors in the output, but the app setup fails.

**Comment by breucode** [comment]
I have the same problem with Linux Mint 20.2 using GitHub.
App version is 1.80.0+10

**Comment by ashutoshsaboo** [comment]
Hi @vHanda , i was just trying out gitjournal on mac - and was receiving the same error as reported above. Was using the version from here - https://github.com/GitJournal/GitJournal/releases/tag/v1.80.0 - which looks like you released on 15th Sept after you made this fix - https://github.com/GitJournal/GitJournal/commit/5ca0a78687fc388e58990c466e2589bd63adba93 . 

I'm new to gitjournal, so was just trying to re-use the same repo that i'm using on android with the mac app as well. Have you tried to reproduce after your fix, if it's even happening now? Or is this crash expected in the released version that i linked above?

**Comment by vHanda** [comment]
Sorry. I haven't released a newer version on GitHub. I wasn't aware people were using it. There is just one bug (a missing cache loading screen) missing from the master branch, and then I'll make a new release for all platforms.

(If you want you can look at the CI and get the last working version - https://github.com/GitJournal/GitJournal/actions/workflows/macos.yml . Sadly builds on macos are failing right now)

**Comment by ashutoshsaboo** [comment]
I tried to use the installer from both the latest builds - https://github.com/GitJournal/GitJournal/actions/runs/1446619902 , https://github.com/GitJournal/GitJournal/actions/runs/1440644985 . For both of them it's not even reaching the exit code screen, on clicking "generate new keys" in the ssh key onboarding setup page, it gets stuck on "Generating ssh key" infinite loading screen - doesn't go ahead. @vHanda when you release the macos build on github, can you please validate if this has been fixed as well (not sure if your existing fix to this issue already fixes this as well or not?)? 

Until then is there an alternative working macos build installer that i can try with, if you have one handy and if you could either link/attach here? @vHanda 

I'm new to gitjournal and find it quite promising, but to make the switch completely a desktop/web app is kind of a requirement for me personally. Which was the only reason, was trying out for the desktop beta app.
