### ISSUE TITLE
Cannot configure self-hosted Gitea

### ISSUE THREAD

**Issue by jcm4atx** [GitJournal/GitJournal#542]
GitJournal version 1.80.0
Android 10
Motorola One 5G Ace

Steps to reproduce the problem:
1. Setup Git Host
2. Select `Custom`
3. Enter valid Git Clone URL
4. Select `Provide Custom SSH Keys`
5. Load both valid keys from file
6. Click `Next`

Nothing happens after this. The `Next` button does change.

I am able to `git clone` my repository. I can also use Visual Studio Code to access my repository. So I believe everything is configured correctly on the server side.

I have the same problem when attempting to use my Github repository.

I have cleared storage and cache, removed the app, rebooted, everything I can think of to do.

**Comment by vHanda** [comment]
Could you please attach the debug logs? (settings -> Debug?)

**Comment by jcm4atx** [comment]
I was able to make this work by generating new keys. It doesn't like my existing keys however. I will attach the debug logs.

**Comment by jcm4atx** [comment]
@vHanda thank you for your response. I reset the app and repeated my steps from this morning and it's now working. I'm puzzled but it's working and I have nothing further, so I'll close the issue.

**Comment by vHanda** [comment]
This makes no sense. I'm happy it's working for you, but on the other hand I want to know what was wrong.
