### ISSUE TITLE
Change date when adding journal entry

### ISSUE THREAD

**Issue by subzero355** [GitJournal/GitJournal#545]
At times, I want to post a back dated entry and I did not find any option to change the date. Is it possible to allow changing dates?
PS: I'm on PRO version.

**Comment by vHanda** [comment]
Which editor would you want to do this in?

Right now, you can temporarily switch to the raw editor and manually edit the date.

**Comment by subzero355** [comment]
Sorry to not mention that, I was referring to Journal editor.

**Comment by vHanda** [comment]
I'll make a new release (`1.81`) tomorrow or on Tuesday :)
