### ISSUE TITLE
Support '.txt' files

### ISSUE THREAD

**Issue by dabeeeenster** [GitJournal/GitJournal#55]
I created a new repo, added a bunch of old notes which are just text files with the .md extension. I've got 281 notes in the repo, but only 41 showing in the app. Is this maybe because the files are missing meta data? 

---
> Please vote on this issue with a 👍reaction. It's one of the primary mechanisms used to prioritize issues.

**Comment by vHanda** [comment]
Hi. Could you please share one of the notes that are not showing up?

It shouldn't matter that they don't have any metadata.

**Comment by vHanda** [comment]
Also, could you please use the 'Report a bug' button from the sidebar. It will attach some debug information. It would be great if you could send that to me. (It might contain some personal info, so please go through it before sending it to me).

**Comment by dabeeeenster** [comment]
Ah ok - the app was filtering on *.md files and some of my files were *.txt. Not sure what the best behaviour ought to be here...

**Comment by vHanda** [comment]
Hey Ben

I can add 'txt' support to GitJournal if you want, but then we won't have
any metadata about those notes.

What do you think about GitJournal converting those 'txt' notes to Markdown
when they are edited?

**Comment by dabeeeenster** [comment]
Yes that might work.
