### ISSUE TITLE
Cannot enable "Store Repo Externally"

### ISSUE THREAD

**Issue by rzfzr** [GitJournal/GitJournal#558]
It gives this error: settings.storage.failedExternal

![image](https://user-images.githubusercontent.com/13456224/141384633-217b3299-5867-4845-a496-9f728227220c.png)

On MIUI 12.5.3 and app 1.81.1
I have entered the settings and enabled all available permissions and no luck.

**Comment by vHanda** [comment]
Sorry. I know.

I can't pass an update for over a week now. I tried to add an extra permission and that seems to have triggered a check, and google keeps rejecting the updates.

Ive filled an appeal, I hope I'll heat back soon.

**Comment by aviaryan** [comment]
@vHanda Do you have an APK for the update? Maybe we can use the APK in the meanwhile.

**Comment by vHanda** [comment]
> @vHanda Do you have an APK for the update? We can install the application via the APK in the meanwhile.

See "Artifacts" at the bottom. https://github.com/GitJournal/GitJournal/actions/runs/1462852471

This version is lacking a loading screen for building an internal cache so that files can sorted based on the git metadata. If after cloning you don't see your files, please wait a minute, and then restart the app.

**Comment by rzfzr** [comment]
![Screenshot_20211124-224152_GitJournal.jpg](https://user-images.githubusercontent.com/13456224/143353422-5362b647-c354-42f3-ae65-043c343fbef9.jpg)
Just tried the app in the latest action, on a Samsung tab, though that the Xiao xiaomi  permissions were at fault

**Comment by rzfzr** [comment]
@vHanda do you by any change have the old builds? Lets say 5 months ago

**Comment by vHanda** [comment]
Closing this in favor of https://github.com/GitJournal/GitJournal/issues/646
