### ISSUE TITLE
RSA SHA-1 disabled in OpenSSH 8.8 so keys don't work any more

### ISSUE THREAD

**Issue by sabotrax** [GitJournal/GitJournal#559]
The GitJournal app could no longer authenticate against
an OpenBSD 7.0 host running OpenSSH 8.8.
As a workaround you can enable SHA1 keys in sshd.conf,
but it's considered insecure.

**Comment by qbit** [comment]
Here are the release notes that talk about the change: https://www.openssh.com/txt/release-8.8

This will impact anything running OpenSSH 8.8 or up (that hasn't explicitly enabled RSA sigs) - Not just OpenBSD 7.0.

**Comment by vHanda** [comment]
This has been affecting me as well 

Honestly I'm a bit stuck on how to fix it. See https://github.com/GitJournal/GitJournal/issues/260#issuecomment-751368868

I need to figure out how to store the public key in the OpenSSH format. If anyone has some simple code to do that, please share it. I can then port it to dart.

**Comment by vHanda** [comment]
For the private key format this seems like a decent explainaton - https://peterlyons.com/problog/2017/12/openssh-ed25519-private-key-file-format/

Now I just need to know how to write the public key.

**Comment by vHanda** [comment]
Yaye. I found something - https://github.com/mikesmitty/edkey

I can try to port that code to Dart. However I'm without a laptop till Monday, so let's see when I can get to it. Any help would be greatly appreciated.

**Comment by qbit** [comment]
Nice! Is there a TestFlight I can enroll in to help test?

**Comment by vHanda** [comment]
Sadly, I've had to revert these changes in ios because of #520. I can't seem to figure it out right now, and its better to use rsa rather than having a broken build.

**Comment by vHanda** [comment]
Fixed with 1.83.11
