### ISSUE TITLE
Exception: Git Merge Bindings failed

### ISSUE THREAD

**Issue by Dieterbe** [GitJournal/GitJournal#560]
Hi, i'm getting this exception when i'm trying to sync from github (using the android app, pro version). This was working until a few days ago. I didn't change anything on github, my private notes repo is still there.

**Comment by vHanda** [comment]
Could you please try after enabling "Dart only Merge" from settings -> experimental.

**Comment by Dieterbe** [comment]
I think that worked, yeah. i can confirm that changes from github have been pulled in to the app.  I'm not sure if changes i made on my phone were synced to github though, because i forgot what they were.

**Comment by vHanda** [comment]
I'm going to close this for now, as I can't reproduce it. Also, I want to stop using the Git Bindings in January for "merging", so hopefully this won't happen again.

**Comment by carlobonamico** [comment]
I just reproduced with version 1.85.0+3575.

Enabling Dart Merge did indeed fix the issue.
