### ISSUE TITLE
renaming a file in git repo -> sync to app. file shows up twice

### ISSUE THREAD

**Issue by Dieterbe** [GitJournal/GitJournal#562]
I had a file named 'Vim todo.md' . I renamed it to vim-todo.md and committed to github (both the removal of old file + addition of new file)

then, syncing in gitjournal makes it show both files

**Comment by vHanda** [comment]
Hello. I can't seem to reproduce this, could you please repeat this and then attach the debug logs? (From Settings -> Debug)

**Comment by vHanda** [comment]
Marking as fixed as the latest version `1.83` has a lot of tests to make sure renames work properly.
