### ISSUE TITLE
Make "Last Modified" and "Created" sort by file metadata as well as YAML tag

### ISSUE THREAD

**Issue by v21** [GitJournal/GitJournal#565]
I currently have the following setup:
- I use Zettlr on my computer to make notes. Zettlr does not have built in YAML frontmatter support & I don't currently set it & modified time by hand.
- I sync from my computer to my phone using SyncThing. Gitjournal is set up to use an external directory, and so picks up on changes made using SyncThing.
- In SyncThing, I sort by "Last Modified" / "Descending" - so I can see my most recent notes.

This works pretty well, although I understand it's probably a fairly niche setup. The pain point I have is that if I create a new note in Zettlr, it sets the modified time, and sync that onto my phone correctly - but Gitjournal does not pick up on the file metadata, and puts it at the bottom of the list. So if I want to look at that note, I either have to search for it, or scroll all the way down.

I would potentially be interested in creating a pull request for this change myself, but would like to know if this is a change that would be welcomed - or was it fixed in #78?

**Comment by vHanda** [comment]
If I understand your use case correctly, this is fixed, but the newer version is still not released.

The current (master) behavior is that it will use the mtime from the git metadata, unless it is specified in the yaml header. Would that work for you?

**Comment by vHanda** [comment]
Fixed.

Unfortunately, I cannot push a new version until I manage to contact someone from Google as my app keeps getting automatically rejected and appeals are being ignored.

Till then, please consider Installing F-Droid and using the app from there - https://gitjournal.io/fdroid_how_to/ . This way you can also (optionally) installed the development version.
