### ISSUE TITLE
Scrolling large lists drops frames

### ISSUE THREAD

**Issue by dabeeeenster** [GitJournal/GitJournal#57]
I have a OnePlus7 Pro, and ~250 notes in a single folder. Scrolling quickly does drop quite a few frames. It seems to speed up if you spend several seconds scrolling up and down (maybe flutter is caching something somewhere). 

Not sure how much can be done in this instance - is flutter capable of scrolling a large list whilst maintaining 60/90 fps?

**Comment by vHanda** [comment]
Hey Ben.

Yes. I have noticed this on my OnePlus as well. I'll run some performance tests to see exactly where is the problem.

**Comment by vHanda** [comment]
Hi. I'm made a lot of performance improvements with the latest version `1.41`. Could you please re-open this if it is still lagging for you?

**Comment by dabeeeenster** [comment]
Yep now perfect
