### ISSUE TITLE
On start, there is splash screen with "reading git history"

### ISSUE THREAD

**Issue by nurgasemetey** [GitJournal/GitJournal#570]
When I start app, there is splash screen with "reading git history 2021-12-20" then changes previous date. Reading December is not finished in 5 minutes. It will not finish reading 2 year repository.

![Screenshot_20211220-163211.png](https://user-images.githubusercontent.com/4669437/146775896-e7aa68f6-5f8e-4225-a3e5-910d6d9837d5.png)

**Comment by vHanda** [comment]
Could you please attach the debug logs? Settings -> Debug -> Copy

**Comment by nurgasemetey** [comment]
@vHanda 

Problem is: because it is 2 year old repo, I was waiting for its finish but I couldn't pass December. 😀 I can't enter to app because of that.

**Comment by vHanda** [comment]
Right. Oops. Do you have dart installed on a laptop?

**Comment by vHanda** [comment]
@nurgasemetey : Would you mind trying to latest build version from FDroid? https://gitjournal.io/fdroid_how_to/

For the GitJournal repo, I've brought the time down from 4 minutes to 24 seconds.

**Comment by vHanda** [comment]
It should be - 

```
Build Version: 1.82.1
Build Number :   3297
```

The build is still being generated as I'm writing this - https://github.com/GitJournal/GitJournal/runs/4584221285?check_suite_focus=true

**Comment by nicholasnadel** [comment]
I'm experiencing the same issue

**Comment by vHanda** [comment]
I've released version `1.83.0` which has massive massive performance improvements. Please let me know if it is still too slow, and I can then explore more optimizations and maybe doing it in the background and not blocking.
