### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by j-r-e-i-d** [GitJournal/GitJournal#576]
Simply can't create a repo without incurring this error message:
Failed
GitException: Invalid Credentials

Git Journal does actually create the repo before this error occurs. I really need to get this sorted soon.

**Comment by vHanda** [comment]
Fixed with 1.82.3. It's still pending review by apple, I just submitted it.

**Comment by j-r-e-i-d** [comment]
Hi Vishesh,
I am now receiving the following error.
I would love to get this working soon.

Jon

-- 
  Jon Reid
  ***@***.***
