### ISSUE TITLE
`&ge;` and `&le;` not properly rendered

### ISSUE THREAD

**Issue by logithack** [GitJournal/GitJournal#577]
If you include the greater-than-or-equal sign or the less-than-or-equal sign in a note's text using the escape sequence `&ge;` or `&le;`, respectively, they are not translated into ≥ or ≤, respectively. They're rendered as the raw escape sequence entered. However, both GitHub and GitLab Markdown render these as the desired math symbol.

Environment:
OS: Android 11
GitJournal version: 1.82.1+3297

Steps to reproduce:
- Configure a GitHub or a GitLab repository in GitJournal.
- Create a new note.
- Enter any text containing `&ge;` or `&le;` into the note's body, e.g. `The secret numbers are &ge; 1 and &le; 3.`.
- Save and view the rendered markdown by hitting the *render* button (the one with the eye icon).

**Comment by vHanda** [comment]
They weren't supported as `&lte;` isn't part of the markdown specification. It's part of html4. However, most markdown renderers are built on top of html, so it just works. Unfortunately, that isn't the case for GitJournal.

I've added support for all the entities I found here - https://github.com/wooorm/character-entities-html4/blob/main/index.js

I'll try to make a new release tomorrow (`1.82.4`).

PS: Please consider leaving a review somewhere if you haven't already, even a few words really help.
