### ISSUE TITLE
That lower right button is annoying.

### ISSUE THREAD

**Issue by OrwillT** [GitJournal/GitJournal#58]
That lower right green round button is annoying when I'm writing my note. It will obscure the text, and cause mishaps. Because of it, each of my notes often generates three to five extra commits. Could you guys do something with that?

PS. Two extra suggestions:
1. I think it will be better if you could display some extra information like witch folder it belongs to and when did it been modified under every note. And display all the subfolder's content in main Note screen.
2. Personally, the submission is too granular.  Can you give more customization options in this regard.

**Comment by vHanda** [comment]
Hmm. Do you think it would be fine, if I made sure it was never obscuring the text?

About (1) - Absolutely. It's something I'm working on.
Regarding (2), I don't quite understand. Could you please elaborate?

**Comment by OrwillT** [comment]
I thinks it will be better if you hide that button when keyboard bump up.

About 2: At now every tiny edit will become a fresh new commit and push to server immediately. Why don't you offer a manual sync setting and rebase multiple commit to one. But keep it sync every tiny edit is still fine I think. It's just a Immature idea.

**Comment by vHanda** [comment]
I'm not sure about hiding it when the keyboard is up. Let me run some experiments.

Regarding (2), I've just pushed a commit adding a way to configure the push frequency - https://github.com/GitJournal/GitJournal/issues/8 . I'll additionally expose a way to see the git commit history, and a way to combine commits (This will take some time - probably not this month). Would that work?
