### ISSUE TITLE
Links without file extension replace existing files

### ISSUE THREAD

**Issue by xaque208** [GitJournal/GitJournal#581]
If a link in a markdown file contains `[[some/file/path]]` where the file is `path.md`, following that link from GitJournal replaces the existing file on save.  I'd expect that the file path is looked up, so that when the extension is appended, the `path.md` file is opened for editing rather than replacing the existing file.

**Comment by xaque208** [comment]
Looking again, perhaps all files are replaced when links are followed.

**Comment by vHanda** [comment]
I just tried out the example given, but I can't reproduce it. Maybe it got fixed as I have mostly been focusing on writing more automated tests this month.

Please reopen the bug if you still encounter it.

**Comment by xaque208** [comment]
I think you're right, this probably got fixed.  I'll continue filing issues as I see them.  Thanks for the support.
