### ISSUE TITLE
Cannot install from Google Play

### ISSUE THREAD

**Issue by dcousens** [GitJournal/GitJournal#583]
| | |
| - | - |
Package Version | 82831610
Model | Pixel 5
Android Version | 12 (5 Janurary 2022)

Using the official Google Play store.

Update failed. 
I uninstalled.
Now I cannot reinstall.

No problem with installing/updating other applications.
I reset the cache for Google Play (and other system services).
No change.

(happy to provide any other information as needed)

<img src="https://user-images.githubusercontent.com/413395/148670589-083f3d46-6b63-444b-b8d3-4ce75354dfd6.jpg" width="384">

**Comment by vHanda** [comment]
Could you please try clearing Google Play's cache?

**Comment by jerluc** [comment]
I'm also in the same boat; I've already tried clearing Play Store and Play Services caches. @dcousens are you running Android 12L beta by any chance? I am currently running on the beta, so not sure if this could somehow impact it (though other app updates have been installing just fine).

**Comment by vHanda** [comment]
What about installing it via FDroid? Does that work?

Gitjournal.io/fdroid

**Comment by kressi** [comment]
Same here, update is not possible. After uninstalling GitJournal, clearing Playstore cache and restarting Android, it is still not possible to install from Playstore again.

Thank you @vHanda installing from F-Droid repository https://gitjournal.io/fdroid/repo works.

**Comment by dcousens** [comment]
> Could you please try clearing Google Play's cache?

No change.

>  @dcousens are you running Android 12L beta by any chance?

- Android 12 SQ1A.220105.002

I can install GitJournal on an Android 10 device.

**Comment by jonnyeom** [comment]
I'm also having installation issues
Pixel 6 Pro, Android 12, Build SD1A.210817.037.A1

**Comment by Amir-Ahmad** [comment]
Same issue here. Galaxy s21 ultra, android 12.

**Comment by callumd789** [comment]
Same issue here. Pixel 6, Android 12, build SD1A.210817.036

**Comment by He4eT** [comment]
Same issue on Pixel 5 :c

**Comment by craigfurman** [comment]
@vHanda does https://github.com/GitJournal/GitJournal/commit/f92df02d92076895742821023ce7911065133230 have anything to do with this issue, or am I speculating wildly? I discovered that commit after trying to google the problem and finding https://stackoverflow.com/questions/69897658/flutter-app-not-installable-from-google-store-for-android-12-despite-being-set-t. I haven't tested this at all, I haven't had an android toolchain set up for (literally) 10 years.

**Comment by vHanda** [comment]
I've released `1.83.0` with a fix! Thanks guys.

**Comment by craigfurman** [comment]
@vHanda the fix appears to have a new problem that prevents the app opening, I've opened https://github.com/GitJournal/GitJournal/issues/587 🙏
