### ISSUE TITLE
 RemoteRepo not configured after host setup

### ISSUE THREAD

**Issue by crimeariver** [GitJournal/GitJournal#585]
Android 10
Motorola G7

I setup a git host from the app and cloned.  The app still displays "No Git Host" and the log reports "Not syncing because RemoteRepo not configured".  

I don't see any errors in the log, but this bit looks suspicious to me:

> {"t":1642234916593,"l":"i","msg":"**_Old Path: /storage/emulated/0/GitJournal/_**"}
> {"t":1642234916594,"l":"i","msg":"**_New Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/GitJournal_**"}
> ...
> {"t":1642234916596,"l":"i","msg":"**_Loading Repo at path /storage/emulated/0/GitJournal/_**"}

Here is a more complete log excerpt, with 36 "GitTransferProgress" messages omitted for brevity.

> {"t":1642234679256,"l":"i","msg":"--------------------------------"}
> {"t":1642234679257,"l":"i","msg":"--------------------------------"}
> {"t":1642234679257,"l":"i","msg":"--------------------------------"}
> {"t":1642234679257,"l":"i","msg":"--------- App Launched ---------"}
> {"t":1642234679257,"l":"i","msg":"--------------------------------"}
> {"t":1642234679257,"l":"i","msg":"--------------------------------"}
> {"t":1642234679258,"l":"i","msg":"--------------------------------"}
> {"t":1642234679258,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","proMode":"false","validateProMode":"true","proExpirationDate":"","debugLogLevel":"v","experimentalMarkdownToolbar":"false","experimentalGraphView":"false","experimentalAccounts":"false","experimentalGitMerge":"false","experimentalGitOps":"false","experimentalTagAutoCompletion":"false","experimentalHistory":"false"}}
> {"t":1642234679269,"l":"d","msg":"Analytics Collection: true"}
> {"t":1642234679269,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
> {"t":1642234679273,"l":"i","msg":"App Version: 1.82.4"}
> {"t":1642234679273,"l":"i","msg":"App Build Number: 3348"}
> {"t":1642234679284,"l":"i","msg":"Repo Ids [0]"}
> {"t":1642234679284,"l":"i","msg":"Current Id 0"}
> {"t":1642234679287,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"other","storeInternally":"false","storageLocation":"/storage/emulated/0","id":"0"}}
> {"t":1642234679287,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
> {"t":1642234679288,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"true","sshPrivateKey":"true","sshPassword":"false","id":"0"}}
> {"t":1642234679288,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
> {"t":1642234679288,"l":"i","msg":"Loading Repo at path /storage/emulated/0/GitJournal/"}
> {"t":1642234679339,"l":"i","msg":"_commitUntracked: 0:00:00.033978"}
> {"t":1642234679340,"l":"d","msg":"BlobCTimeBuilder Cache Size: 0.26 Kb"}
> {"t":1642234679344,"l":"d","msg":"FileMTimeBuilder Cache Size: 0.17 Kb"}
> {"t":1642234679346,"l":"d","msg":"Loading MTimeCache: 1 items"}
> {"t":1642234679346,"l":"d","msg":"Loading CTimeCache: 2 items"}
> {"t":1642234679351,"l":"i","msg":"Branch main"}
> {"t":1642234679351,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
> {"t":1642234679352,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false"}
> {"t":1642234679396,"l":"d","msg":"Received MediaFile Share with App (media): []"}
> {"t":1642234679531,"l":"i","msg":"Notes Cache Loaded: 0 items"}
> {"t":1642234679531,"l":"i","msg":"Finished loading the notes cache - 0:00:00.180002"}
> {"t":1642234679536,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
> {"t":1642234679545,"l":"d","msg":"Got HEAD: 1d90d76f322fd718ec2e55883728c4cc1c4eb783"}
> {"t":1642234679560,"l":"i","msg":"Built Git Time Cache - 0:00:00.014659"}
> {"t":1642234679572,"l":"d","msg":"Saving MTimeCache: 2 items"}
> {"t":1642234679573,"l":"d","msg":"Saving CTimeCache: 3 items"}
> {"t":1642234679575,"l":"i","msg":"_commitUntracked: 0:00:00.039188"}
> {"t":1642234679578,"l":"i","msg":"Done building the FileStorageCache: true"}
> {"t":1642234679594,"l":"i","msg":"Finished loading all the notes - 0:00:00.063301"}
> {"t":1642234679646,"l":"i","msg":"Loading View 0_summary: 0:00:00.012130"}
> {"t":1642234717903,"l":"d","msg":"Event.DrawerSetupGitHost"}
> {"t":1642234718859,"l":"d","msg":"githostsetup_button_click GitHub"}
> {"t":1642234718860,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitHub","icon_url":"assets/icon/github-icon.png"}}
> {"t":1642234721053,"l":"d","msg":"githostsetup_button_click Let me do it manually"}
> {"t":1642234721054,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Let me do it manually","icon_url":""}}
> {"t":1642234753631,"l":"d","msg":"githostsetup_button_click Next"}
> {"t":1642234753642,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
> {"t":1642234756654,"l":"d","msg":"githostsetup_button_click Generate new keys"}
> {"t":1642234756656,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Generate new keys","icon_url":""}}
> {"t":1642234756760,"l":"d","msg":"PublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMRdvmFwRIz7W6c9ZqidToG3Ic6BZFrW2+5ZInJnwUFK GitJournal-android-2022-01-15 "}
> {"t":1642234758472,"l":"d","msg":"githostsetup_button_click Copy Key"}
> {"t":1642234758472,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Copy Key","icon_url":""}}
> {"t":1642234808000,"l":"d","msg":"githostsetup_button_click Copy Key"}
> {"t":1642234808006,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Copy Key","icon_url":""}}
> {"t":1642234913172,"l":"d","msg":"githostsetup_button_click Clone Repo"}
> {"t":1642234913197,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Clone Repo","icon_url":""}}
> {"t":1642234913221,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/GitJournal"}
> {"t":1642234913382,"l":"d","msg":"GitTransferProgress: #3 3 3 0 0 0 475  \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000#"}
> 
> ... 36 GitTransferProgress messages omitted
> 
> {"t":1642234915225,"l":"d","msg":"GitTransferProgress: #3 3 3 0 0 0 475  \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000#"}
> {"t":1642234916408,"l":"i","msg":"Got default branch: main"}
> {"t":1642234916410,"l":"i","msg":"Using remote branch: main"}
> {"t":1642234916428,"l":"i","msg":"Repo has the following branches: [main]"}
> {"t":1642234916428,"l":"i","msg":"Local branches [main]"}
> {"t":1642234916428,"l":"i","msg":"Completing - localBranch: main"}
> {"t":1642234916439,"l":"i","msg":"Merging 'origin/main'"}
> {"t":1642234916543,"l":"d","msg":"Event.GitHostSetupComplete","p":{"host_type":"GitHub","provider_choice":"KnownProvider","setup_manner":"Manual","key_generation":"AutoGenerated"}}
> {"t":1642234916543,"l":"i","msg":"calling onComplete GitJournal origin"}
> {"t":1642234916593,"l":"i","msg":"Old Path: /storage/emulated/0/GitJournal/"}
> {"t":1642234916594,"l":"i","msg":"New Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/GitJournal"}
> {"t":1642234916595,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"other","storeInternally":"false","storageLocation":"/storage/emulated/0","id":"0"}}
> {"t":1642234916595,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
> {"t":1642234916596,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"true","sshPrivateKey":"true","sshPassword":"false","id":"0"}}
> {"t":1642234916596,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
> {"t":1642234916596,"l":"i","msg":"Loading Repo at path /storage/emulated/0/GitJournal/"}
> {"t":1642234916615,"l":"d","msg":"Received MediaFile Share with App (media): []"}
> {"t":1642234916638,"l":"i","msg":"_commitUntracked: 0:00:00.037963"}
> {"t":1642234916641,"l":"d","msg":"BlobCTimeBuilder Cache Size: 0.35 Kb"}
> {"t":1642234916643,"l":"d","msg":"FileMTimeBuilder Cache Size: 0.27 Kb"}
> {"t":1642234916644,"l":"d","msg":"Loading MTimeCache: 2 items"}
> {"t":1642234916644,"l":"d","msg":"Loading CTimeCache: 3 items"}
> {"t":1642234916646,"l":"i","msg":"Branch main"}
> {"t":1642234916646,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
> {"t":1642234916648,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
> {"t":1642234916650,"l":"i","msg":"Notes Cache Loaded: 1 items"}
> {"t":1642234916650,"l":"i","msg":"Finished loading the notes cache - 0:00:00.003387"}
> {"t":1642234916667,"l":"d","msg":"Received MediaFile Share with App (media): []"}
> {"t":1642234916670,"l":"d","msg":"Got HEAD: 1d90d76f322fd718ec2e55883728c4cc1c4eb783"}
> {"t":1642234916671,"l":"i","msg":"Built Git Time Cache - 0:00:00.001119"}
> {"t":1642234916676,"l":"d","msg":"Saving MTimeCache: 2 items"}
> {"t":1642234916676,"l":"d","msg":"Saving CTimeCache: 3 items"}
> {"t":1642234916679,"l":"i","msg":"Done building the FileStorageCache: true"}
> {"t":1642234916679,"l":"i","msg":"_commitUntracked: 0:00:00.031014"}
> {"t":1642234916703,"l":"i","msg":"Finished loading all the notes - 0:00:00.053430"}
> {"t":1642234916734,"l":"i","msg":"Loading View 0_summary: 0:00:00.000683"}
> {"t":1642235083171,"l":"i","msg":"--------------------------------"}
> {"t":1642235083172,"l":"i","msg":"--------------------------------"}
> {"t":1642235083172,"l":"i","msg":"--------------------------------"}
> {"t":1642235083172,"l":"i","msg":"--------- App Launched ---------"}
> {"t":1642235083172,"l":"i","msg":"--------------------------------"}
> {"t":1642235083172,"l":"i","msg":"--------------------------------"}
> {"t":1642235083172,"l":"i","msg":"--------------------------------"}
> {"t":1642235083172,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","proMode":"false","validateProMode":"true","proExpirationDate":"","debugLogLevel":"v","experimentalMarkdownToolbar":"false","experimentalGraphView":"false","experimentalAccounts":"false","experimentalGitMerge":"false","experimentalGitOps":"false","experimentalTagAutoCompletion":"false","experimentalHistory":"false"}}
> {"t":1642235083191,"l":"d","msg":"Analytics Collection: true"}
> {"t":1642235083191,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
> {"t":1642235083196,"l":"i","msg":"App Version: 1.82.4"}
> {"t":1642235083197,"l":"i","msg":"App Build Number: 3348"}
> {"t":1642235083205,"l":"i","msg":"Repo Ids [0]"}
> {"t":1642235083205,"l":"i","msg":"Current Id 0"}
> {"t":1642235083208,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"other","storeInternally":"false","storageLocation":"/storage/emulated/0","id":"0"}}
> {"t":1642235083208,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
> {"t":1642235083209,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"true","sshPrivateKey":"true","sshPassword":"false","id":"0"}}
> {"t":1642235083209,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
> {"t":1642235083209,"l":"i","msg":"Loading Repo at path /storage/emulated/0/GitJournal/"}
> {"t":1642235083262,"l":"i","msg":"_commitUntracked: 0:00:00.033998"}
> {"t":1642235083264,"l":"d","msg":"BlobCTimeBuilder Cache Size: 0.35 Kb"}
> {"t":1642235083267,"l":"d","msg":"FileMTimeBuilder Cache Size: 0.27 Kb"}
> {"t":1642235083270,"l":"d","msg":"Loading MTimeCache: 2 items"}
> {"t":1642235083270,"l":"d","msg":"Loading CTimeCache: 3 items"}
> {"t":1642235083275,"l":"i","msg":"Branch main"}
> {"t":1642235083275,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
> {"t":1642235083276,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false"}
> {"t":1642235083321,"l":"d","msg":"Received MediaFile Share with App (media): []"}
> {"t":1642235083494,"l":"i","msg":"Notes Cache Loaded: 1 items"}
> {"t":1642235083495,"l":"i","msg":"Finished loading the notes cache - 0:00:00.219642"}
> {"t":1642235083499,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
> {"t":1642235083511,"l":"d","msg":"Got HEAD: 1d90d76f322fd718ec2e55883728c4cc1c4eb783"}
> {"t":1642235083512,"l":"i","msg":"Built Git Time Cache - 0:00:00.001396"}
> {"t":1642235083526,"l":"d","msg":"Saving MTimeCache: 2 items"}
> {"t":1642235083526,"l":"d","msg":"Saving CTimeCache: 3 items"}
> {"t":1642235083532,"l":"i","msg":"Done building the FileStorageCache: true"}
> {"t":1642235083539,"l":"i","msg":"_commitUntracked: 0:00:00.041064"}
> {"t":1642235083544,"l":"i","msg":"Finished loading all the notes - 0:00:00.049153"}
> {"t":1642235083591,"l":"i","msg":"Loading View 0_summary: 0:00:00.012284"}
> {"t":1642235089660,"l":"d","msg":"Event.DrawerSettings"}
>

**Comment by vHanda** [comment]
Fixed with `1.83.6`. Thanks for reporting this :)
