### ISSUE TITLE
New app version is not open-able

### ISSUE THREAD

**Issue by craigfurman** [GitJournal/GitJournal#587]
After the fix for https://github.com/GitJournal/GitJournal/issues/583 landed, I can now install the latest GitJournal update again on my pixel 4a, running Android 12.

However, when I tap the app icon, I get a flash message saying "app isn't installed".

Total speculation, but I wonder if https://github.com/GitJournal/GitJournal/commit/f92df02d92076895742821023ce7911065133230 should actually set `android:exported="true"`, rather than false? This is only based on https://stackoverflow.com/questions/17360731/application-is-not-installed-error-when-launched-from-home-screen-shortcut, I have no flutter experience and extremely out of date android experience, apologies if this speculation isn't helpful.

**Comment by vHanda** [comment]
Sorry. I pushed the wrong update, and new one is now pending review.

**Comment by vHanda** [comment]
https://github.com/GitJournal/GitJournal/commit/918159875a791152e3b2630446227bf1109ac91f
