### ISSUE TITLE
GitJournal not loading past splash screen

### ISSUE THREAD

**Issue by c-antin** [GitJournal/GitJournal#588]
After the recent update does the app not load past splash screen.

**Comment by radupotop** [comment]
I have had the same issue yesterday after updating the GitJournal app to the latest ersion.  
It wouldn't load past the splash screen and I had to reset it and setup everything again.

**Comment by bergie** [comment]
Same problem here. Resetting it (clearing cache and storage) made the app open, but I can't complete the GitHub OAuth flow to get my notes back

**Comment by vHanda** [comment]
I see the problem. I've released version 1.83.1 on FDroid with the fix. However, given these bugs and some rather larger changes I've made, I'm going to thoroughly test out GitJournal tomorrow and then push an update on Google Play.

**Comment by vHanda** [comment]
Fixed with `1.83.2`. Please reopen if you're still encountering it.
