### ISSUE TITLE
Failed Null check operator used on a null value

### ISSUE THREAD

**Issue by dsphub** [GitJournal/GitJournal#598]
Cloning empty repository from github can't be complete. An error is "Failed Null check operator used on a null value"
Steps to reproduce:
1. Tap on Setup Git Host at menu
2. Tap on GitHub button
3. Tap on Setup Automatically
4. Tap on Authorize Git Journal and complete authentication
5. Input name a new repository and tap on Next

Actual result:
Cloning wheel is closed after that empty screen with error "Failed Null check operator used on a null value

**Comment by snzhaoyua** [comment]
same issue.
app downloaded from google play store.

**Comment by snowzach** [comment]
Same issue, adding a file to the repo and then trying again works.

**Comment by fndmossmann** [comment]
Had the same issue.
It happens only when cloning an empty repository.
If the repository has some file on it, it works just fine.

**Comment by ptman** [comment]
Same issue, app from google app store and repo on private gitea.

**Comment by ptman** [comment]
Seems adding a file (I added .gitignore) to the repo before cloning really does work.
