### ISSUE TITLE
note go back after deleted

### ISSUE THREAD

**Issue by muhammadarif1** [GitJournal/GitJournal#6]
#### EXPECTED BEHAVIOR
after I delete all the records, the records that I deleted should be lost forever
#### ACTUAL BEHAVIOR
after i delete all note and exit the app then i open the app again note that has i deleted is go back
#### STEP TO REPRODUCE
- install and open the app
- write some journal
- then delete it
- then exit the app and clean recent task
- open the app again and note the error
DEVICE: ANDROID 6.1
APP NAME : GITJOURNAL V 1.1.4
#### BUG RECORDING
https://youtu.be/_xzQ6iyE1hU

**Comment by muhammadarif1** [comment]
please feedback sir

**Comment by vHanda** [comment]
Hi. Could you please try it out with the latest release? I fixed a bug in the note deletion code.

**Comment by muhammadarif1** [comment]
let me try

**Comment by muhammadarif1** [comment]
still appear sir

**Comment by vHanda** [comment]
Alright. Could you please do the following -

* Open the app
* Delete the note
* Open the side Drawer and choose 'Send Bug Report'

This will create an email with an attachment which has the app logs. Please post these app logs.

**Comment by muhammadarif1** [comment]
okey

**Comment by onozasi** [comment]
Android version: 7.0
Make/Model: Tecno k8
Name: Tecno Spark pro 

--------- beginning of main
06-11 07:11:58.027 18160 18160 E FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
06-11 07:11:58.028 18160 18160 E FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
06-11 07:12:19.376 18160 18272 E GitJournalLib: Add Match: 2019-06-11T07:12:15+01:00.md
06-11 07:12:23.845 18160 18216 E GitJournalLib: Add Match: 2019-06-11T07:12:20+01:00.md
06-11 07:12:38.394 18160 18188 E GitJournalLib: Add Match: 2019-06-11T07:12:24+01:00.md
06-11 07:13:42.765 18160 18409 E GitJournalLib: Removing File: /data/user/0/io.gitjournal.gitjournal/files/journal_local/2019-06-11T07:12:15+01:00.md
06-11 07:13:43.535 18160 18414 E GitJournalLib: Removing File: /data/user/0/io.gitjournal.gitjournal/files/journal_local/2019-06-11T07:12:20+01:00.md
06-11 07:13:44.441 18160 18411 E GitJournalLib: Removing File: /data/user/0/io.gitjournal.gitjournal/files/journal_local/2019-06-11T07:12:24+01:00.md

I hope this log is helpful @vHanda.

**Comment by vHanda** [comment]
Hi. I've refactored the deletion code and fixed some edge cases. Your issue should be resolved in version `1.14`.
