### ISSUE TITLE
Issue cloning repo

### ISSUE THREAD

**Issue by seagoj** [GitJournal/GitJournal#600]
I'm having an issue cloning a repo for a new installation on each of my devices (Pixel 4 and Onyx Boox Nova Air). I get the attached error when I attempt to clone on my Pixel 4 running Android 12 with the 2022-01-05 security update.
![Screenshot_20220209-231236](https://user-images.githubusercontent.com/1255078/153342166-e71328c7-289b-4123-8390-5d27d9b519ae.png)

My assumption was this was a write access issue, but I've enabled permission for GitJournal to write to disk. I tried to bypass this by using an external repo, but that seemed to fail as well.

I use GitJournal heavily. Thanks for making such a great product!

**Comment by vHanda** [comment]
Hey. Sorry about the delay, I've been tracking some nasty race conditions.

Would you mind sharing your debug log, please? Also, does this happen regardless of storing in repo internally vs externally in "Storage Settings" in GitJournal?

**Comment by seagoj** [comment]
It seems to do it no matter what storage option I choose. How do I get the debug log for you?

**Comment by vHanda** [comment]
Settings -> Debug, please. Or you can use the Report a bug button, it'll create an email with the debug log.

**Comment by seagoj** [comment]
{"t":1649557773785,"l":"i","msg":"--------------------------------"}
{"t":1649557773785,"l":"i","msg":"--------------------------------"}
{"t":1649557773785,"l":"i","msg":"--------------------------------"}
{"t":1649557773785,"l":"i","msg":"--------- App Launched ---------"}
{"t":1649557773785,"l":"i","msg":"--------------------------------"}
{"t":1649557773785,"l":"i","msg":"--------------------------------"}
{"t":1649557773785,"l":"i","msg":"--------------------------------"}
{"t":1649557773785,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","validateProMode":"true","proExpirationDate":"null","debugLogLevel":"v","experimentalMarkdownToolbar":"false","experimentalGraphView":"false","experimentalAccounts":"false","experimentalGitMerge":"false","experimentalGitOps":"false","experimentalTagAutoCompletion":"false","experimentalHistory":"false"}}
{"t":1649557773817,"l":"d","msg":"Analytics Collection: true"}
{"t":1649557773817,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
{"t":1649557773830,"l":"i","msg":"Repo Ids [0]"}
{"t":1649557773831,"l":"i","msg":"Current Id 0"}
{"t":1649557773835,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"other","storeInternally":"true","storageLocation":"","id":"0"}}
{"t":1649557773835,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlEditorTypeKey":"type","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
{"t":1649557773836,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"true","sshPrivateKey":"true","sshPassword":"false","id":"0"}}
{"t":1649557773836,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
{"t":1649557773836,"l":"i","msg":"Loading Repo at path /data/user/0/io.gitjournal.gitjournal/app_flutter/repo_0/"}
{"t":1649557773838,"l":"i","msg":"App Version: 1.83.10"}
{"t":1649557773838,"l":"i","msg":"App Build Number: 3533"}
{"t":1649557773840,"l":"d","msg":"Event.AppUpdate","p":{"version":"1.83.10","previous_app_version":"1.83.7","app_name":"GitJournal","package_name":"io.gitjournal.gitjournal","build_number":"3533"}}
{"t":1649557773843,"l":"d","msg":"BlobCTimeBuilder Cache Size: 38.57 Kb"}
{"t":1649557773850,"l":"d","msg":"FileMTimeBuilder Cache Size: 31.70 Kb"}
{"t":1649557773856,"l":"d","msg":"Loading MTimeCache: 302 items"}
{"t":1649557773856,"l":"d","msg":"Loading CTimeCache: 434 items"}
{"t":1649557773860,"l":"i","msg":"Branch main"}
{"t":1649557773860,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
{"t":1649557773860,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1649557773863,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false"}
{"t":1649557773887,"l":"i","msg":"Built Git Time Cache - 0:00:00.027455"}
{"t":1649557773888,"l":"d","msg":"Saving MTimeCache: 302 items"}
{"t":1649557773888,"l":"d","msg":"Saving CTimeCache: 434 items"}
{"t":1649557773906,"l":"d","msg":"Received MediaFile Share with App (media): []"}
{"t":1649557773920,"l":"i","msg":"Notes Cache Loaded: 20 items"}
{"t":1649557773920,"l":"i","msg":"Finished loading the notes cache - 0:00:00.060363"}
{"t":1649557773932,"l":"i","msg":"Sending 34 events"}
{"t":1649557773937,"l":"d","msg":"Note modified: aran.schedule-spring-2021.md"}
{"t":1649557773937,"l":"d","msg":"Note modified: arch-installation.md"}
{"t":1649557773937,"l":"d","msg":"Note modified: bonfyre._.md"}
{"t":1649557773937,"l":"d","msg":"Note modified: bonfyre.activity-feed.md"}
{"t":1649557773938,"l":"d","msg":"Note modified: bonfyre.aws.md"}
{"t":1649557773938,"l":"d","msg":"Note modified: bonfyre.campaign.md"}
{"t":1649557773938,"l":"d","msg":"Note modified: bonfyre.chat-translation.md"}
{"t":1649557773939,"l":"d","msg":"Note modified: bonfyre.medtronic.md"}
{"t":1649557773939,"l":"d","msg":"Note modified: bonfyre.mercury.md"}
{"t":1649557773949,"l":"d","msg":"Note modified: bonfyre.quarterly-meeting.md"}
{"t":1649557773949,"l":"d","msg":"Note modified: bonfyre.sso.md"}
{"t":1649557773949,"l":"d","msg":"Note modified: bonfyre.todo.md"}
{"t":1649557773950,"l":"d","msg":"Note modified: bonfyre.welcome-message.md"}
{"t":1649557773950,"l":"d","msg":"Note modified: census-2020.md"}
{"t":1649557773951,"l":"d","msg":"Note modified: cocktail.the-lifeboat.md"}
{"t":1649557773951,"l":"d","msg":"Note modified: code-review.md"}
{"t":1649557773951,"l":"d","msg":"Note modified: d&d.alacritty.md"}
{"t":1649557773957,"l":"d","msg":"Note modified: dotnet.asp.md"}
{"t":1649557773957,"l":"d","msg":"Note modified: google-foobar.find-the-access-keys.md"}
{"t":1649557773989,"l":"i","msg":"Finished loading all the notes - 0:00:00.068969"}
{"t":1649557774030,"l":"i","msg":"Loading View 0_summary_v2: 0:00:00.006901"}
{"t":1649557774993,"l":"i","msg":"Sent 34 Analytics Events"}
{"t":1649557774998,"l":"i","msg":"Sending 1 events"}
{"t":1649557775396,"l":"i","msg":"Sent 1 Analytics Events"}
{"t":1649557775400,"l":"i","msg":"Sending 0 events"}
{"t":1649557775704,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1649557775708,"l":"i","msg":"Sending 0 events"}
{"t":1649557776006,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1649557782594,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1649557788876,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1649557799364,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1649557800892,"l":"d","msg":"githostsetup_button_click Custom"}
{"t":1649557800892,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Custom","icon_url":""}}
{"t":1649560439781,"l":"i","msg":"--------------------------------"}
{"t":1649560439781,"l":"i","msg":"--------------------------------"}
{"t":1649560439781,"l":"i","msg":"--------------------------------"}
{"t":1649560439781,"l":"i","msg":"--------- App Launched ---------"}
{"t":1649560439781,"l":"i","msg":"--------------------------------"}
{"t":1649560439781,"l":"i","msg":"--------------------------------"}
{"t":1649560439781,"l":"i","msg":"--------------------------------"}
{"t":1649560439781,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","validateProMode":"true","proExpirationDate":"null","debugLogLevel":"v","experimentalMarkdownToolbar":"false","experimentalGraphView":"false","experimentalAccounts":"false","experimentalGitMerge":"false","experimentalGitOps":"false","experimentalTagAutoCompletion":"false","experimentalHistory":"false"}}
{"t":1649560439813,"l":"d","msg":"Analytics Collection: true"}
{"t":1649560439813,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
{"t":1649560439826,"l":"i","msg":"Repo Ids [0]"}
{"t":1649560439826,"l":"i","msg":"Current Id 0"}
{"t":1649560439829,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"other","storeInternally":"true","storageLocation":"","id":"0"}}
{"t":1649560439829,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlEditorTypeKey":"type","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
{"t":1649560439829,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"true","sshPrivateKey":"true","sshPassword":"false","id":"0"}}
{"t":1649560439829,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
{"t":1649560439829,"l":"i","msg":"Loading Repo at path /data/user/0/io.gitjournal.gitjournal/app_flutter/repo_0/"}
{"t":1649560439831,"l":"i","msg":"App Version: 1.83.10"}
{"t":1649560439831,"l":"i","msg":"App Build Number: 3533"}
{"t":1649560439838,"l":"d","msg":"BlobCTimeBuilder Cache Size: 38.65 Kb"}
{"t":1649560439844,"l":"d","msg":"FileMTimeBuilder Cache Size: 31.73 Kb"}
{"t":1649560439846,"l":"d","msg":"Loading MTimeCache: 302 items"}
{"t":1649560439846,"l":"d","msg":"Loading CTimeCache: 434 items"}
{"t":1649560439850,"l":"i","msg":"Branch main"}
{"t":1649560439850,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
{"t":1649560439851,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1649560439852,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false"}
{"t":1649560439869,"l":"i","msg":"Built Git Time Cache - 0:00:00.018583"}
{"t":1649560439886,"l":"d","msg":"Received MediaFile Share with App (media): []"}
{"t":1649560439913,"l":"i","msg":"Notes Cache Loaded: 20 items"}
{"t":1649560439916,"l":"i","msg":"Finished loading the notes cache - 0:00:00.065066"}
{"t":1649560439940,"l":"i","msg":"Finished loading all the notes - 0:00:00.024159"}
{"t":1649560440000,"l":"i","msg":"Loading View 0_summary_v2: 0:00:00.010286"}
{"t":1649560446803,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1649560448451,"l":"d","msg":"githostsetup_button_click GitLab"}
{"t":1649560448452,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitLab","icon_url":"assets/icon/gitlab-icon.png"}}
{"t":1649560450667,"l":"d","msg":"githostsetup_button_click Setup Automatically"}
{"t":1649560450668,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Setup Automatically","icon_url":""}}
{"t":1649560452092,"l":"d","msg":"githostsetup_button_click Authorize GitJournal"}
{"t":1649560452093,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Authorize GitJournal","icon_url":""}}
{"t":1649560452093,"l":"d","msg":"Starting autoconfigure"}
{"t":1649560452093,"l":"d","msg":"GitLab: Installed Handler"}
{"t":1649560483584,"l":"d","msg":"GitLab: Called onUrl with {URL: gitjournal://login.oauth2#access_token=f8c60eed69ee45828db5931ebec72f62b6d1b6fcc31dff0c822d156feceb04b1&token_type=Bearer&state=scuYk_mpyY}"}
{"t":1649560483584,"l":"d","msg":"GitHost Initalized: GitHostType.GitLab"}
{"t":1649560483586,"l":"d","msg":"Starting to fetch userInfo"}
{"t":1649560483805,"l":"d","msg":"Got UserInfo - UserInfo{name: true, email: true, username: true}"}
{"t":1649560483810,"l":"i","msg":"Got User Info: UserInfo{name: true, email: true, username: true}"}
{"t":1649560483819,"l":"d","msg":"Starting RepoSelector"}
{"t":1649560483828,"l":"d","msg":"Starting RepoSelector"}
{"t":1649560488875,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1649560488876,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1649560488876,"l":"d","msg":"Starting autoconfigure copletion"}
{"t":1649560488876,"l":"i","msg":"Generating SSH Key"}
{"t":1649560488889,"l":"i","msg":"Adding as a deploy key"}
{"t":1649560489296,"l":"d","msg":"GitLab addDeployKey: {\"id\":9349483,\"title\":\"GitJournal\",\"created_at\":\"2022-04-10T03:14:49.560Z\",\"expires_at\":null,\"key\":\"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC+zl25On1OX91+zt48bYzyN0qQn0zMG+ZMUPK4G/9i4 GitJournal\",\"fingerprint\":\"fe:f1:3c:95:5c:18:80:2d:d1:41:de:0f:6b:be:c7:41\",\"can_push\":true}"}
{"t":1649560489297,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/repo_0"}
{"t":1649560491126,"l":"i","msg":"Got default branch: main"}
{"t":1649560491127,"l":"i","msg":"Using remote branch: main"}
{"t":1649560491129,"l":"i","msg":"Repo has the following branches: [main]"}
{"t":1649560491129,"l":"i","msg":"Local branches [main]"}
{"t":1649560491129,"l":"i","msg":"Completing - localBranch: main"}
{"t":1649560491132,"l":"i","msg":"Merging 'origin/main'"}
{"t":1649560491214,"l":"e","msg":"Failed to clone","ex":"FileSystemException: Cannot open file, path = '/data/user/0/io.gitjournal.gitjournal/app_flutter/repo_0/index.md' (OS Error: Permission denied, errno = 13)","stack":[{"uri":"dart:io","member":"_File.writeAsBytesSync","isCore":true,"library":"dart:io","location":"dart:io"},{"uri":"package:file/src/forwarding/forwarding_file.dart","line":124,"member":"ForwardingFile.writeAsBytesSync","isCore":false,"library":"package:file/src/forwarding/forwarding_file.dart","location":"package:file/src/forwarding/forwarding_file.dart 124","package":"file"},{"uri":"package:dart_git/checkout.dart","line":84,"member":"Checkout._checkoutTree","isCore":false,"library":"package:dart_git/checkout.dart","location":"package:dart_git/checkout.dart 84","package":"dart_git"},{"uri":"package:dart_git/checkout.dart","line":26,"member":"Checkout._checkout","isCore":false,"library":"package:dart_git/checkout.dart","location":"package:dart_git/checkout.dart 26","package":"dart_git"},{"uri":"package:dart_git/checkout.dart","line":17,"member":"Checkout.checkout.<fn>","isCore":false,"library":"package:dart_git/checkout.dart","location":"package:dart_git/checkout.dart 17","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":93,"member":"catchAllSync","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 93","package":"dart_git"},{"uri":"package:dart_git/checkout.dart","line":17,"member":"Checkout.checkout","isCore":false,"library":"package:dart_git/checkout.dart","location":"package:dart_git/checkout.dart 17","package":"dart_git"},{"uri":"package:dart_git/merge.dart","line":76,"member":"Merge.merge","isCore":false,"library":"package:dart_git/merge.dart","location":"package:dart_git/merge.dart 76","package":"dart_git"},{"uri":"package:dart_git/merge.dart","line":197,"member":"Merge._mergeTrackingBranch","isCore":false,"library":"package:dart_git/merge.dart","location":"package:dart_git/merge.dart 197","package":"dart_git"},{"uri":"package:dart_git/merge.dart","line":178,"member":"Merge.mergeCurrentTrackingBranch.<fn>","isCore":false,"library":"package:dart_git/merge.dart","location":"package:dart_git/merge.dart 178","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":93,"member":"catchAllSync","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 93","package":"dart_git"},{"uri":"package:dart_git/merge.dart","line":178,"member":"Merge.mergeCurrentTrackingBranch","isCore":false,"library":"package:dart_git/merge.dart","location":"package:dart_git/merge.dart 178","package":"dart_git"},{"uri":"package:gitjournal/setup/clone.dart","line":196,"member":"_merge.<fn>","isCore":false,"library":"package:gitjournal/setup/clone.dart","location":"package:gitjournal/setup/clone.dart 196","package":"gitjournal"},{"uri":"package:gitjournal/setup/clone.dart","line":193,"member":"_merge.<fn>","isCore":false,"library":"package:gitjournal/setup/clone.dart","location":"package:gitjournal/setup/clone.dart 193","package":"gitjournal"},{"uri":"package:dart_git/utils/result.dart","line":84,"member":"catchAll","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 84","package":"dart_git"},{"uri":"package:gitjournal/setup/clone.dart","line":193,"member":"_merge","isCore":false,"library":"package:gitjournal/setup/clone.dart","location":"package:gitjournal/setup/clone.dart 193","package":"gitjournal"},{"uri":"package:gitjournal/setup/clone.dart","line":139,"member":"cloneRemotePluggable","isCore":false,"library":"package:gitjournal/setup/clone.dart","location":"package:gitjournal/setup/clone.dart 139","package":"gitjournal"},{"uri":"package:dart_git/utils/result.dart","line":84,"member":"catchAll","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 84","package":"dart_git"},{"uri":"package:gitjournal/setup/screens.dart","line":548,"member":"GitHostSetupScreenState._startGitClone","isCore":false,"library":"package:gitjournal/setup/screens.dart","location":"package:gitjournal/setup/screens.dart 548","package":"gitjournal"}]}
{"t":1649560491216,"l":"d","msg":"Event.GitHostSetupGitCloneError","p":{"error":"FileSystemException: Cannot open file, path = '/data/user/0/io.gitjournal.gitjournal/app_flutter/repo_0/index.md' (OS Error: Permission denied, errno = 13)"}}
{"t":1649560495443,"l":"d","msg":"Starting RepoSelector"}
{"t":1649560501178,"l":"d","msg":"Event.DrawerSettings"}

**Comment by seagoj** [comment]
Is there anything more useful I can do?

**Comment by seagoj** [comment]
Clearing cache and storage seemed to correct this

**Comment by soraxas** [comment]
Hi there! I am having the exact same issue (with exact same message as shown in the picture).

However, I am a new user (with no prior repo) so the solution of clearing data/cache doesn't even make sense as it's a new install. I did perform the clearing after seeing this post and sure enough the same error appears. I'm not sure what to do.

Any point would be appreciated, thanks!!

**Comment by vHanda** [comment]
Sorry guys. I forgot to press the release button about 2 weeks ago with the fix. I'll do that today.

**Comment by soraxas** [comment]
Oh awesome, thanks @vHanda!
