### ISSUE TITLE
[Feedback] Notable integration question

### ISSUE THREAD

**Issue by spiral6** [GitJournal/GitJournal#601]
How well does it integrate with Notable? Notable has a pretty simple structure but doesn't automatically sync notes with a Git repository by default. As a result, it doesn't have versioning support by default. Should I just be creating a script to always trigger based on any changes? What would be the best practice for that? I use Windows and Linux (Arch) with Notable.

**Comment by vHanda** [comment]
Hey. I'm a bit busy today, but I'll try my best to answer later tonight.

**Comment by vHanda** [comment]
So I've finally built a tool - https://github.com/GitJournal/git-auto-sync which makes integrating with any other app much easier. Please take a look at it.
