### ISSUE TITLE
Cannot clone private Repository

### ISSUE THREAD

**Issue by JuKu** [GitJournal/GitJournal#602]
Hi,

it cannot clone a private repository.
First, the repository (created yesterday) is not shown in list (why?).
After that, i tried to insert the full name and then I was redirected to the custom settings with the deploy key.
Also the custom repository add does not work.

![Screenshot_20220217-161520_GitJournal.jpg](https://user-images.githubusercontent.com/1138046/154512045-cad425dc-e6d3-4562-a638-4d785b6108bd.jpg)

**Comment by vHanda** [comment]
Sorry about this.

This is trickier to fix than I expected. Please use the workaround mentioned here https://github.com/GitJournal/GitJournal/issues/598#issuecomment-1041474244
