### ISSUE TITLE
New note filename defaults to yyyy-mm-dd-hh-mm when set as Title

### ISSUE THREAD

**Issue by fndmossmann** [GitJournal/GitJournal#604]
When creating a new note with the filename set as 'Title', it defaults to yyyy-mm-dd-hh-mm
Other formats seem to be working,

![image](https://user-images.githubusercontent.com/1223711/155235810-9da1f87d-a8c0-424a-8790-8bfda355a1f5.png)

I've tested with versions 1.83.5+3477 and 1.83.5-dev+3477. I guess they're the same.

**Comment by vHanda** [comment]
I've just released version `1.83.7` with this fix. Thank you for reporting it.

**Comment by fndmossmann** [comment]
Just updated the app and its working just fine!

Thank you for fixing it so quickly!

![image](https://user-images.githubusercontent.com/1223711/155609381-859c4fe8-b330-4757-a20c-9696e38b8d63.png)
