### ISSUE TITLE
Note renaming produces empty commits

### ISSUE THREAD

**Issue by yoricksijsling** [GitJournal/GitJournal#606]
When I rename a note in the IOS app (version 1.82.4+3356), this produces a commit with the right commit message but without any changes in it. In the app it looks like the rename went through but the actual files in the repository are not changed.

This is such a commit, showing 0 changes:
![image](https://user-images.githubusercontent.com/234131/156320058-ef7458cc-e73d-46e6-9d55-c1099f8436cc.png)

And debug logs around that time:
```
{"t":1646167609122,"l":"d","msg":"Event.RepoSynced"}
{"t":1646167610417,"l":"d","msg":"Got HEAD: 03aba9fd81601c77229944bdd5718d722d66d0a9"}
{"t":1646167610417,"l":"i","msg":"Built Git Time Cache - 0:00:00.000228"}
{"t":1646167610418,"l":"d","msg":"Synced!"}
{"t":1646167610420,"l":"d","msg":"Saving MTimeCache: 49 items"}
{"t":1646167610420,"l":"d","msg":"Saving CTimeCache: 77 items"}
{"t":1646167610432,"l":"i","msg":"Done building the FileStorageCache: true"}
{"t":1646167649765,"l":"d","msg":"Event.NoteRenamed"}
{"t":1646167649822,"l":"d","msg":"Event.RepoSynced"}
{"t":1646167651244,"l":"d","msg":"Got HEAD: da8b8b38e39ee08a0e51c973da77fb0db1efdcef"}
{"t":1646167651250,"l":"i","msg":"Built Git Time Cache - 0:00:00.005662"}
{"t":1646167651253,"l":"d","msg":"Saving MTimeCache: 49 items"}
{"t":1646167651253,"l":"d","msg":"Saving CTimeCache: 77 items"}
{"t":1646167651264,"l":"i","msg":"Done building the FileStorageCache: true"}
{"t":1646167652916,"l":"d","msg":"Synced!"}
```

**Comment by vHanda** [comment]
I've just submitted the latest version `1.83.8` for review. You should get it within a day or two. It mostly comes with lots and lots of automated tests :)

GitJournal has had way too many regressions lately, so I'm now making sure I write automated tests for each bug I fix.

I'll close this issue when Apple approves this latest version.

**Comment by vHanda** [comment]
New version released on iOS

**Comment by yoricksijsling** [comment]
I confirmed that it works now, thanks @vHanda!
