### ISSUE TITLE
[Feature][Android] Don't commit changes if the content of note hasn't changed

### ISSUE THREAD

**Issue by mnowotnik** [GitJournal/GitJournal#615]
version of GitJournal on Android: 1.83.9+3526

**What is happening ?**
When a user enters a note and then immediately exists the note widget using any of the provided editors (Markdown, raw, journal, checklist) or simply the View mode, the note is marked as changed, even though no changes have been performed by the user. Then, during the synchronization process one of two things will usually happen:
- if the viewed note has `modified` field, it will be changed to the datetime of the latest viewing; this change will be commmited
- if the viewed note doesn't have `modified` field, the *empty* commit will be made and pushed

**What should be happening?**
When a user enters a note via any mode and doesn't perform any changes, the GitJournal shouldn't update or change the note.

**Comment by vHanda** [comment]
Yup. I've noticed this happening lately. Clearly a regression. I'll look into it and write an automated test.

**Comment by mnowotnik** [comment]
Thanks for fast reply! Happy to support you! :smile:

**Comment by vHanda** [comment]
Sadly, I can't seem to reproduce it. Though I have seem empty commits in my git log. Can you reliably reproduce it? (Could you please try with 1.83.10?)

**Comment by mnowotnik** [comment]
Yes, I just rechecked with 1.83.10. 
I enter note.
I press Android Back button.
I sync notes.
Empty commit is being made.

**Comment by vHanda** [comment]
Could you attach a copy of your debug logs, please?

(Settings -> Debug)

**Comment by mnowotnik** [comment]
<details>
<summary> Show log </summary>

{"t":1647946073011,"l":"d","msg":"Note modified"}
{"t":1647946073011,"l":"e","msg":"AutoCompleter","ex":"RangeError: Invalid value: Not in inclusive range 0..264: -1","stack":[{"uri":"dart:core","member":"_StringBase.lastIndexOf","isCore":true,"library":"dart:core","location":"dart:core"},{"uri":"package:gitjournal/editors/autocompletion_widget.dart","line":280,"member":"TagsAutoCompleter.textChanged","isCore":false,"library":"package:gitjournal/editors/autocompletion_widget.dart","location":"package:gitjournal/editors/autocompletion_widget.dart 280","package":"gitjournal"},{"uri":"package:gitjournal/editors/autocompletion_widget.dart","line":69,"member":"_AutoCompletionWidgetState._textChanged","isCore":false,"library":"package:gitjournal/editors/autocompletion_widget.dart","location":"package:gitjournal/editors/autocompletion_widget.dart 69","package":"gitjournal"},{"uri":"package:flutter/src/foundation/change_notifier.dart","line":308,"member":"ChangeNotifier.notifyListeners","isCore":false,"library":"package:flutter/src/foundation/change_notifier.dart","location":"package:flutter/src/foundation/change_notifier.dart 308","package":"flutter"},{"uri":"package:flutter/src/foundation/change_notifier.dart","line":412,"member":"ValueNotifier.value=","isCore":false,"library":"package:flutter/src/foundation/change_notifier.dart","location":"package:flutter/src/foundation/change_notifier.dart 412","package":"flutter"},{"uri":"package:flutter/src/widgets/editable_text.dart","line":151,"member":"TextEditingController.value=","isCore":false,"library":"package:flutter/src/widgets/editable_text.dart","location":"package:flutter/src/widgets/editable_text.dart 151","package":"flutter"},{"uri":"package:flutter/src/widgets/editable_text.dart","line":136,"member":"TextEditingController.text=","isCore":false,"library":"package:flutter/src/widgets/editable_text.dart","location":"package:flutter/src/widgets/editable_text.dart 136","package":"flutter"},{"uri":"package:gitjournal/editors/raw_editor.dart","line":105,"member":"RawEditorState.didUpdateWidget","isCore":false,"library":"package:gitjournal/editors/raw_editor.dart","location":"package:gitjournal/editors/raw_editor.dart 105","package":"gitjournal"},{"uri":"package:flutter/src/widgets/framework.dart","line":4778,"member":"StatefulElement.update","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4778","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":3370,"member":"Element.updateChild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 3370","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4613,"member":"ComponentElement.performRebuild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4613","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4763,"member":"StatefulElement.performRebuild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4763","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4311,"member":"Element.rebuild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4311","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4795,"member":"StatefulElement.update","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4795","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":3370,"member":"Element.updateChild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 3370","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4613,"member":"ComponentElement.performRebuild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4613","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4763,"member":"StatefulElement.performRebuild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4763","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":4311,"member":"Element.rebuild","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 4311","package":"flutter"},{"uri":"package:flutter/src/widgets/framework.dart","line":2578,"member":"BuildOwner.buildScope","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 2578","package":"flutter"},{"uri":"package:flutter/src/widgets/binding.dart","line":882,"member":"WidgetsBinding.drawFrame","isCore":false,"library":"package:flutter/src/widgets/binding.dart","location":"package:flutter/src/widgets/binding.dart 882","package":"flutter"},{"uri":"package:flutter/src/rendering/binding.dart","line":363,"member":"RendererBinding._handlePersistentFrameCallback","isCore":false,"library":"package:flutter/src/rendering/binding.dart","location":"package:flutter/src/rendering/binding.dart 363","package":"flutter"},{"uri":"package:flutter/src/scheduler/binding.dart","line":1145,"member":"SchedulerBinding._invokeFrameCallback","isCore":false,"library":"package:flutter/src/scheduler/binding.dart","location":"package:flutter/src/scheduler/binding.dart 1145","package":"flutter"},{"uri":"package:flutter/src/scheduler/binding.dart","line":1082,"member":"SchedulerBinding.handleDrawFrame","isCore":false,"library":"package:flutter/src/scheduler/binding.dart","location":"package:flutter/src/scheduler/binding.dart 1082","package":"flutter"},{"uri":"package:flutter/src/scheduler/binding.dart","line":996,"member":"SchedulerBinding._handleDrawFrame","isCore":false,"library":"package:flutter/src/scheduler/binding.dart","location":"package:flutter/src/scheduler/binding.dart 996","package":"flutter"}]}
{"t":1647946073035,"l":"d","msg":"Building autocompleter with {    REDACTED  }"}
{"t":1647946073040,"l":"d","msg":"Note modified: REDACTED.md"}
{"t":1647946074700,"l":"d","msg":"Event.RepoSynced"}
{"t":1647946077718,"l":"d","msg":"Synced!"}
<details/>

**Comment by vHanda** [comment]
I'm mostly interested in the parts which print out all your settings. So I can configure GitJournal in the same way. it's printed in the log each time the app loads.
