### ISSUE TITLE
Feature request: Emoji

### ISSUE THREAD

**Issue by Iglum** [GitJournal/GitJournal#62]
Can you use this repo to get emoji that works on andoid?

### This repo [flutter-emoji](https://github.com/petehouston/flutter-emoji)

😄 ☕️  Cheers

**Comment by vHanda** [comment]
Hi. Could you please elaborate? You want to be able type `:heart:` and see a :heart: ?

**Comment by Iglum** [comment]
Yes, this is precisely what i mean. I do use emojis as headers in my md files.  

Like this.
![image](https://user-images.githubusercontent.com/33994566/74525774-3c74ee80-4f22-11ea-833b-4623dc5ebc17.png)

But on this will not work on mobile.
