### ISSUE TITLE
Using ffi for libgit2

### ISSUE THREAD

**Issue by modulovalue** [GitJournal/GitJournal#63]
I've read that you're using android ndk & ios bindings to access libgit2.

Have you tried using the new ffi in dart for that?

**Comment by vHanda** [comment]
Hi. I haven't. I'm reluctant to use it until it is out of beta (We already get lots of strange crashes in iOS with stable). Let's see if I manage to implement git in dart by then, if not I should definitely switch. Using it with NDK and iOS is a pain.

**Comment by modulovalue** [comment]
Also, somebody tried to use ffi & libgit2 [here](https://gitlab.com/fabio.sturm/git2) 

>  I'm reluctant to use it until it is out of beta
Yes, fair enough. It would be pretty exciting to have a stable dart only implementation of git.

**Comment by vHanda** [comment]
Hey. I'm going to close this issue as there really isn't anything to do, but wait till FFI support goes out of beta.
