### ISSUE TITLE
New, long entry causes duplicate file

### ISSUE THREAD

**Issue by whirledsol** [GitJournal/GitJournal#631]
### Problem
When adding a new entry which takes over 1-2 minutes to type, it appears to autosave with a snapshot. When finally hitting the checkmark and saving, the result is a duplicate file which the full text.

![image](https://user-images.githubusercontent.com/2266464/167897871-d3a3f006-d96c-42b1-9f4e-d22e4ba6070c.png)

### Expected Behavior
Entry is autosaved (which appears to be the case) but once hitting the checkmark, the autosaved entry is overwritten with the latest. The result is one file.

### Environment
Android 11. OnePlus 7T  (*unable to label, sorry*)

**Comment by Gayour1** [comment]
@Gayour1

**Comment by vHanda** [comment]
Confirmed. I've spent a long time trying to fix this, and now I finally understand why this is happening. Hopefully I can fix it soon.

Thanks for reporting this.

**Comment by Michael2MacDonald** [comment]
Was this fixed? Notes sometimes get duplicated for me still.

**Comment by hamedgayou** [comment]
Osh
