### ISSUE TITLE
Note not saved when putting url in the title

### ISSUE THREAD

**Issue by jamesmortensen** [GitJournal/GitJournal#632]
I keep track of online reviews I submit inside individual note cards in Google Keep.  I tried the same in GitJournal, and the note does not save.

Moreover, there is no error message in the UI indicating there is a problem. First, and foremost, I think the UI should indicate if there is a problem saving.  The only way I knew it didn't save was by checking GitHub.  If I had thousands of notes, I would miss this not saving.

Furthermore, adding support for URLs in the title would be awesome.

Here is the title that replicates the issue.  I use the format URL dash title dash read time in minutes:

`https://quantum5.ca/2020/12/26/how-to-make-an-arm-virtual-machine-armhf-aarch64/ - How to make an ARM VM armhf aarch64 - 5m`

Thank you for creating this and syncing it with GitHub, as well as making the UI look as close to Google Keep as possible.  I am looking at switching so I have more control of my data.

**Comment by jamesmortensen** [comment]
UPDATE:  I tried with a different url, and it wrote the note to GitHub.   I also installed the development APK from GitHub Actions, and the sample I supplied above also worked in a new repo.  The original card however won't save. It's as if GitHub has no knowledge of it even though I see it in the app.  I did use the "Bug Report" feature in the app to send logs.  Hope it helps.  Please let me know if you need anything else.  Thanks again!

**Comment by vHanda** [comment]
Would you mind please attaching the debug logs over here?

I'm just getting to all these old bugs, and there are way too many emails.

**Comment by jamesmortensen** [comment]
I'll see if I can find the debug logs. It's been a long time since this happened, and I wasn't able to reproduce this.
