### ISSUE TITLE
GitJournal still needs RSA keys for Azure

### ISSUE THREAD

**Issue by MalcolmMielle** [GitJournal/GitJournal#633]
This is related to #629 

I'm unable to clone the repo. I used to have the error shown in 629 but now the cloning never finishes and I have the error GitException: remote 'origin' does not exists. Right now I'm stuck at 100% for network and index but the page does not finish to load. I then stop the app and restart it and then I have #629 again. The fix should be in 1.84 I think but I'm still on 1.83 so that's probably the problem (I'm on iPhone).

Also could you live the choice between rsa and ed25519 since Azure hasn't switched to ed25519 yet? For now, I provide my own ssh key if that helps.

**Comment by vHanda** [comment]
Damn. I haven't shipped 1.84 on the  iPhone, Apple raised some issue. I'll try to fix them by tomorrow. So hopefully you should have version 1.84 by Monday.

Hmm, I guess I could add rsa keys again. I'm just not sure how to expose it in the UI. The setup process is already way too complex, and modifying it is quite a pain. Maybe I'll provide an option in the settings.

**Comment by vHanda** [comment]
@MalcolmMielle : I don't mind the occasional pings. I still haven't found a project management style that works for me, so pinging is a decent way to make me remember.

I'll release version `1.85` later today, till then you can use the dev version from Fdroid - https://gitjournal.io/fdroid_how_to/

**Comment by MalcolmMielle** [comment]
Ok good to know, I usually don't like to ping, but I wasn't sure how else to do it :). I'll check the fdroid version, I didn't think it worked on iOS :)
