### ISSUE TITLE
[Feature request] kebab-case filenames

### ISSUE THREAD

**Issue by nottrobin** [GitJournal/GitJournal#636]
It's very indulgent of me to ask this, please feel free to ignore or reject.

It would be great for me if there was an option for [Kebab Case](https://lodash.com/docs/#kebabCase) (or caterpillar case, or [something](https://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case) filenames based on the title. That is, filenames based on the title, but with lowercased words separated by a hyphen.

`an-example-article.md`

This is good for my use-case because I use GitJournal to publish blog posts, and the filename makes up the URL. But I do also feel this makes a generally quite attractive filename.

**Comment by vHanda** [comment]
I haven't properly tested this.

Additionally, I want to get one more change before I ship the new version. Till then, maybe you want to try out the dev version from FDroid? https://gitjournal.io/fdroid_how_to/ It probably has fixes for your issues. (You can have both the dev and normal version installed in parallel)

**Comment by nottrobin** [comment]
Amazing! Thank you so much

**Comment by nottrobin** [comment]
I'm guessing I have to wait a bit? I don't see it in the Dev version yet.

![image](https://user-images.githubusercontent.com/519935/173052353-645bd733-6c5e-4bf9-b432-45e5b96115c2.png)

**Comment by vHanda** [comment]
The builds were set on a cron job, I've now changed it to rebuild after each update on GitJournal. Not sure why I never did that before.

Please just wait for the CI to complete - https://github.com/GitJournal/fdroid/runs/6829926512

**Comment by nottrobin** [comment]
This is now in the Dev build, but I don't think it works as intended.

![image](https://user-images.githubusercontent.com/519935/173108429-8174c1dc-b89d-43cf-b80d-672c90437cd2.png)

![image](https://user-images.githubusercontent.com/519935/173108488-ebaa8062-0fde-4faf-ad88-63d6b1c5da9f.png)

**Comment by vHanda** [comment]
Fixed. Releasing version `1.85` today.
