### ISSUE TITLE
search doesn't work for note titles

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#64]
If you try searching for a word that appears only in the title of a note, the search result is empty.  In other words, search is not finding words in note titles.  It seems like it definitely should.

Just out of curiosity, how does the search work exactly?  Is it the equivalent of a grep through the body of the notes?  Or is note text indexed somehow?

Thanks.

**Comment by vHanda** [comment]
Hey James.

You're right about it not searching through the title. When I implemented
it, there was no title.

The search works as a grep.

**Comment by jrollins** [comment]
Is it possible to have it search title also?  If it's doing a grep it seems like it might be easier to just let it search over the entire note, rather than filtering out the title. I would certainly prefer it to search titles also, if possible.

**Comment by jrollins** [comment]
Thanks!

**Comment by vHanda** [comment]
I'm happy to help :)

I'll make a fresh release today or tomorrow morning. The fix will be in version `1.41`.
