### ISSUE TITLE
Cannot import ssh keys in any means

### ISSUE THREAD

**Issue by James4Ever0** [GitJournal/GitJournal#645]
I tried to copy an existing ssh key pair `id_rsa` and `id_rsa.pub` out of an rooted android phone under `/data/data/io.gitjournal.gitjournal`.

However no matter how I import these keys into GitJournal, like copy and paste or import from files, or even set a password like `abcde` for the `id_rsa` file, it fails to import, without any hint. When I hit the `Next` button it just cannot continue.

I have read the code and it does not encrypt the RSA private key during creation. I do not know why it fails to import the RSA key which is generated all by itself.

**Comment by jelech** [comment]
same problem

**Comment by vHanda** [comment]
Please use an ed25519 key till this is fixed.

Closing this in favor of https://github.com/GitJournal/GitJournal/issues/623
