### ISSUE TITLE
Fatal GitException Error

### ISSUE THREAD

**Issue by boelenz** [GitJournal/GitJournal#649]
I am setting up Gitjournal for first use, with my remote git-repository hosted on Github, containing my Zettlr notes.
From my local Macbook, using the cli git, I have no trouble syncing to the github version of my notes, using the same ssh-keys as the ones I try to use with Gitjournal.

The error I get, is:
"Failed GitException:ERROR:You're using an RSA key with SHA-1, which is no longer allowed."

(Message trucated)

**Comment by xyegithub** [comment]
Same error. Is it solved now?

**Comment by xyegithub** [comment]
> I am setting up Gitjournal for first use, with my remote git-repository hosted on Github, containing my Zettlr notes. From my local Macbook, using the cli git, I have no trouble syncing to the github version of my notes, using the same ssh-keys as the ones I try to use with Gitjournal.
> 
> The error I get, is: "Failed GitException:ERROR:You're using an RSA key with SHA-1, which is no longer allowed."
> 
> (Message trucated)

I find that the app download here is ony the version 1.80.0. I downloaded the version 1.85.2 from https://apkpure.com/gitjournal-markdown-notes-in/io.gitjournal.gitjournal . It dose not have this problem.

**Comment by vHanda** [comment]
Closing this as it seems related to GitHub - Per https://github.blog/2021-09-01-improving-git-protocol-security-github/, Github is discontinuing support for SHA-1 RSA ssh keys as of 2022-1-11.

See - https://github.com/git-up/GitUp/issues/802 - for more info.
