### ISSUE TITLE
remote changes to notes not being picked up until app is restarted

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#65]
I've been testing out remote editing of notes.  The app seems to pick up the addition of new notes created remotely without problem.  However, it seems to fail to pick up edits to existing notes until the app has been restarted.  So it seems that it picks up the git updates, but that what's displayed is a cache of the note contents from when the app was first opened.  If I close the app, and then reopen, then the remote edits are visible.

**Comment by vHanda** [comment]
Hey James. Could you try pulling down to refresh or clicking on the cloud icon. That will trigger a git pull and push.

I'm not sure how to fix this - currently we sync after each edit. Perhaps this should also be done each time a note opens? Or should we just do it every x minutes?

**Comment by jrollins** [comment]
Hey Vishesh.  I've tried all the various update methods (click on cloud, stroke down) but none seems to update the note text.  I think the notes that have changes just need to be reopened by the app.  Is that difficult somehow? (I honestly have no idea how things like this would work in the app)

**Comment by vHanda** [comment]
Hey James.

It's possible I broke something during a recent refactor. I'll check it out
and let you know

**Comment by vHanda** [comment]
Hi. I just tried it out with the latest version and it's working for me.

Could you please try again and after that use the 'Report a bug' button on the sidebar. That will generate an email with the debug logs. It'll help diagnosing the issue.

**Comment by jrollins** [comment]
Hey, Vishesh.  I tried to send a report from the app as you've suggested.  I don't really do email on my phone, though, so hopefully it went through.  Let me know.

**Comment by jrollins** [comment]
Is there any way that I can view the apps logs?  I'm suspecting that there's some issue with the git synchronization, or maybe in header parsing, that's contributing to the inability of the app to incorporate updates properly.  If I could view the apps logs directly it would really help with my ability to debug what's going on.

**Comment by bbkane** [comment]
I'm also running into this. Submitted bug report.

**Comment by vHanda** [comment]
> I'm also running into this. Submitted bug report.

Hi Ben
Thanks for reporting it. You're now the 3rd user to report this. I'll try my best to expose some developer tools in the app, and add extra debugging info. With the current logs, it's not apparent what is wrong.

**Comment by bbkane** [comment]
If I knew anything about Flutter or Android dev, I'd try to help. I really love this app! All I've wanted for so long is to be able to edit markdown notes in folders on my computer and have them sync to my phone- and this DOES IT! AND IT'S OPEN SOURCE!

**Comment by vHanda** [comment]
> If I knew anything about Flutter or Android dev, I'd try to help. I really love this app! All I've wanted for so long is to be able to edit markdown notes in folders on my computer and have them sync to my phone- and this DOES IT! AND IT'S OPEN SOURCE!

Ben. You are helping a lot - You're reporting bugs, and providing positive feedback which is extremely motivating. And maybe you're even telling others about the app.

All of this is incredibly valuable. Please don't feel bad about not contributing via code. It's all these other parts that I need help with.

**Comment by jrollins** [comment]
> If I knew anything about Flutter or Android dev, I'd try to help. I really love this app! All I've wanted for so long is to be able to edit markdown notes in folders on my computer and have them sync to my phone- and this DOES IT! AND IT'S OPEN SOURCE!

@bbkane I've been working on a client app that I've been using heavily and works pretty well: https://gitlab.com/jrollins/xotes .  Would love to have other users and feedback.  I was going to send a note about it to the gitjournal team soon.

**Comment by bbkane** [comment]
@jrollins thanks, but I all I want or feel like I need on the computer side is git, vim, and ripgrep. Its a solved problem for me. I really like this app because it lets me carry those botesover to the phone.

**Comment by jrollins** [comment]
> @jrollins thanks, but I all I want or feel like I need on the computer side is git, vim, and ripgrep. Its a solved problem for me. I really like this app because it lets me carry those notes over to the phone.

xotes is little more than a python wrapping of those things that presents a highly simplified interface.  It's very light weight.  It also includes a xapian indexing of the notes for faster search, if you choose.  I developed it before I ever heard of gitjournal, so am appreciate of gitjournal for the same reason.

**Comment by jrollins** [comment]
Definitely still seeing this issue.  Remote changes are only picked up when I restart the app.  Haven't figured out any way around it yet, and it seems to be unavoidable.

**Comment by vHanda** [comment]
Hey guys. This is one of the main issues that I will be working on over the weekend. So either this will get fixed or there will be some developer tools exposed which will help us understand the problem better.

**Comment by vHanda** [comment]
Hello wonderful people. I investigated this, and it did result in me finding a sorting bug, but I couldn't reproduce it. I tried adding a new note in my Github repo via the command line, pressing the cloud button in GitJournal, and then the note would appear.

Perhaps it was just the sorting issue, though given that the note appears after restart makes me believe it is not the case. I have added lots more debugging logs, so now it should be easier to figure out what the problem is.

I've made some rather large changes to the way the notes are listed and I'm not comfortable making a new release without fixing some bugs and testing it out a bit more. So the extra debugging info + sorting fixes will have to wait for that. I should get that done tomorrow / Wednesday. I'll keep you updated.

(If you can reliably reproduce this, please give me very detailed steps on how to reproduce it)

**Comment by jrollins** [comment]
Thanks so much for your work on this @vHanda.

I can definitely reliably reproduce the issue, but I don't need to do anything special to do so: I modify a note remotely, push to the repo, update in gitjournal, see no change to the note, close the app, reopen app and see changes.  I've never actually seen the update happen in situ without having to restart.

**Comment by vHanda** [comment]
Wait. This is interesting. You modified an existing note. I only added a new one. Could you check if adding a new note works? I'll try to reproduce this via modifying an existing note tomorrow.

**Comment by jrollins** [comment]
Yes, adding a new note works.  Sorry, I maybe should have been clearer.  The problem is that updates on existing notes do not get picked up without restarts.

**Comment by jrollins** [comment]
It feels to me that this is probably a problem with the app caching the notes, and not flushing the cache on git updates.
