### ISSUE TITLE
Cannot restore purchase

### ISSUE THREAD

**Issue by signedav** [GitJournal/GitJournal#656]
I have a new device and I want to unlock the pro version.

I click "restore purchase" but I get the error (1):
"Subscription Expired on purchase_screen.unknown"

When I want to purchase again I receive the message: "You already own this item" (2) followed by a "purchase_error: BillinResponse.itemAlreadyOwned" (3) and a (apparently) never ending moving circle (4).

| Step 1 | Step 2     | Step 3      | Step 4     | Vers. |
|:-----------------:|:----------------:|:----------------:|:---------------:|:----------------:|
| ![](https://user-images.githubusercontent.com/28384354/185486112-d1cd9afd-c3e2-470f-b8f8-43f072e3c3cf.png)  |![](https://user-images.githubusercontent.com/28384354/185486236-0609847d-7751-4bc4-b1b9-901a1ef77fd7.png)  | ![](https://user-images.githubusercontent.com/28384354/185486276-6ce917e3-3684-4a82-a82f-8298c86ac865.png)  | ![](https://user-images.githubusercontent.com/28384354/185486323-25b63b91-c458-43c5-9c3e-8e5bb248f59e.png)  | ![](https://user-images.githubusercontent.com/28384354/185486395-cfe5d123-c818-4c17-a5a1-e8af4357cc32.png)  |

**Comment by vHanda** [comment]
Sorry. This happens to some users. Could you please email me a copy of your receipt? vhanda@gitjornal.io I'll provide a workaround

**Comment by signedav** [comment]
I guess it's gitjournal.io - did it. thanks.

**Comment by signedav** [comment]
Any news on that?

**Comment by signedav** [comment]
Anything missing from my side?

**Comment by signedav** [comment]
@vHanda should we reopen that
