### ISSUE TITLE
option to display just note titles in listing

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#66]
I would like an option where the app just shows the note titles in the listing, rather than the title followed by a snippet of the body.  I think it would make the interface a lot cleaner.  Maybe the note listing could just be the note title with the time of last modification on the right..

**Comment by vHanda** [comment]
Alright. This is something that can be done.

I seem to be getting more and more requests of totally different ways on how to list the notes - Different people prefer different things, depending on the situation. Maybe a very configurable approach is really the way to go.

**Comment by jrollins** [comment]
I am trying to transition from ColorNote, which lists notes just with title and modification date, which I think works well.  Keeps the interface less cluttered.

I would suggest that if a note doesn't have a title then the first line of the body could be used in the listing instead.

**Comment by Ziinc** [comment]
I think the display style depends totally on the workflow and app usage style of the user. 

If it's more of a daily journal (like a diary) , then the lastmod or inserted date would be more valuable to the user.

If it's more wiki-style note taking (like Onenote/Evernote) , then page titles are more valuable. 

If it's more snippet-style note taking (like keep) , then the first line is more valuable.

**Comment by jrollins** [comment]
> If it's more wiki-style note taking (like Onenote/Evernote) , then page titles are more valuable.
> 
> If it's more snippet-style note taking (like keep) , then the first line is more valuable.

If the first line was the note title, then both of these use cases would be satisfied simultaneously.  It's not clear a separate title field is needed, actually, if you just use the first line.  People who want a separate title could just fill in the first line appropriately.

**Comment by scoobertron** [comment]
On a related note, it looks as though newlines are stripped out of the snippet of the note body.  So:

test
test
test

appears as:

test test test

This is a bit confusing - particularly for checklists

**Comment by vHanda** [comment]
Hey guys. I've been thinking on how to tackle this problem. Here is my proposed solution -

We provide a number of pre-defined views -
* **Journal View** - This will be exactly as it currently as - however the title will always be a date. Either the creation or modification date, depending on the sorting criteria.
* **Standard View** - The same list based view. The title will either be the note's title or note's filename. I can provide an option regarding which should be shown.
* **Compact View** - A list with one just line per item. You'll be able to configure it to be either the title or the filename. I can also add the option to show the first 'x' words in case the title is missing.
* **Card View** - This is a view similar to Google Keep's current style. The notes will be arranged in a grid, with a large amount of the note's contents being visible. It's something I've been wanting for quite a while, as I still often use Google Keep for some use cases.

With this framework, in the future, we can add other Note Views. I'm not sure what to call these - **Views** or **Listings** or something else?

Please let me know what you think. It'll be good to know if this will cover your individual cases before I start implementing it.

**Comment by jrollins** [comment]
Sounds like a fine solution.  I also like being able to see the last modification date, but that could also be added to the note view itself.

I note that you could achieve most of all of these options with two configs options, one a format string and the other a check box:
```
  listing format: "{title} ({modified})"
  [ ] include snippet of note body
```

I also reiterate that i think adding the ability to change note file names will add complication that I think would be just as well avoided.

**Comment by Ziinc** [comment]
@vHanda views are a more intuitive name. You could call it folder/repo views if you want to make a clear distinction between it and editor views.


@jrollins filename changing could allow for interlinking of notes in the future, since typing/autocompleting  relative pathname would be easier than typing the timestamp file name

**Comment by jrollins** [comment]
> @jrollins filename changing could allow for interlinking of notes in the future, since typing/autocompleting relative pathname would be easier than typing the timestamp file name

@Ziinc but why should anyone need to type a pathname?  The UI should completely hide the structure of the store from the user.  At least that's what I want the note management system to do...  This should probably be discussed further in #56
