### ISSUE TITLE
Bug: App crashes on startup after trying to clone from local repo

### ISSUE THREAD

**Issue by lguenth** [GitJournal/GitJournal#667]
Hey, I just started using your app because I like the simplicity and concept.

Unfortunately, after trying to clone from a repo on my local network, GitJournal suddenly closed right after telling me it's syncing and now whenever I try to open it, I see a brief glimpse of my two previously written test files (on my phone) and then the app crashes. I get the Android popup "GitJournal keeps stopping." with the option to close the app or submit feedback etc.

...after un- and reinstalling, the app just shows me a black screen on startup, then nothing happens. Seems like the app storage might be corrupted? How do I remove left-over configs?

**Comment by lguenth** [comment]
Update: Uninstalled Google Play Store version, installed apk from the latest (first?) GitHub release. App works again but I haven't tested cloning yet.

**Comment by vHanda** [comment]
Would you mind trying the FDroid release please?

Also, could you please provide info about the ssh version of your server, basically the more information you can provide the better. Unless I can reproduce it, there is a low chance of this getting fixed.
