### ISSUE TITLE
use first line of note as title if title not provided

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#67]
I suggest the first line of the body be used as the note title if no title is provided.

**Comment by vHanda** [comment]
Hi. I'm not keen on doing this - Only cause I find it annoying when other note taking apps do it. Though maybe it makes sense if the first line is the header?

In general, I'd prefer just leaving the title blank and changing the note list to show a blank title. I like how Google Keep does it.

**Comment by jrollins** [comment]
I guess this is somewhat related to #66, where I would really like the main note list to just show the title and not any of the note body.  In that case, if the note does not have a title then it could just use the first line of the body.  But I guess this is all just details of how a title-only list would behave, so I'll just close this issue in favor of #66.
