### ISSUE TITLE
Can't sync GitHub repository: FileSystemException

### ISSUE THREAD

**Issue by friaca** [GitJournal/GitJournal#677]
When trying to sync a repository from GitHub, I get an exception right after adding the key to the repository. What can I do to mitigate this?

![gitjournal exception](https://user-images.githubusercontent.com/41522991/197094805-545d5acc-0159-4a30-9556-faae325e631a.jpg)

**Comment by abianche** [comment]
Same thing. Only happens if I enabled the "store externally" option.

**Comment by vHanda** [comment]
Sorry. Storing the data externally seems quite broken in Android 11+, I need to rethink the entire approach and figure out how to implement it.

Till then, I'll add a disclaimer in the app.

Closing this in favor of https://github.com/GitJournal/GitJournal/issues/646
