### ISSUE TITLE
Bug Report feature is looking for the wrong filename (date is off)

### ISSUE THREAD

**Issue by orbanbalage** [GitJournal/GitJournal#679]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/285574/200148647-a782c56a-89ed-4bf5-ab38-d05a61ac0b2d.png">

The Debug says:
```
12:06:50 Log file /Users/orbanbalage/Library/Caches/logs/2022-11-04.jsonl not found
```

The date is one day off, and the correct date filename is present:
`/Users/orbanbalage/Library/Caches/logs/2022-11-05.jsonl`

**Comment by vHanda** [comment]
It looks for the current date, and one day in the past. I'm going to remove the log message as I see it's not super useful.
