### ISSUE TITLE
git remote settings not editable

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#68]
In the current version (1.40.0+966), in the settings under "Git Remote Settings", the configurable options are the ssh public key and the sync frequency.  It's not currently possible to edit the URL of the git remote.  It would be nice to be able to edit the git remote URL itself.

**Comment by vHanda** [comment]
Confirmed. It's something I'm actively working on.

**Comment by vHanda** [comment]
Marking this as fixed as you can reconfigure the remote. It's not perfect as it's equivalent to cloning a new repo, but it works. Bug #149 is there for adding another remote.
