### ISSUE TITLE
app "raw editor" seems to be showing parsed note, not raw

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#69]
The apps "raw editor" seems to be parsing the note before presenting it to the user.  I would prefer it actually show the note completely raw, without any parsing.

The reason I know the note has been processed is that the header 'modified' datetime field is shown in local timezone in the raw editor, even though the field was written in UTC by my external remote app.  

I concede it's possible that this issue is not with the raw editor but that the note is being spuriously parsed and re-written by the app in some other way before the raw display, even though the note content has not change.  If that's what's going on, then I guess the bug issue here is that the app is modifying notes spuriously when not requested to do so by the user.

**Comment by vHanda** [comment]
I think this is because of issue #43 . Does it always occur for you?

**Comment by vHanda** [comment]
I'm closing this issue for #43 as the raw editor presents the note date without any other modifications. Please feel free to re-open if you notice that it happens for notes where you're in the same timezone.
