### ISSUE TITLE
Support Multiple Journals with different Views

### ISSUE THREAD

**Issue by DarwinJS** [GitJournal/GitJournal#7]
If I could override the document name I could use it as a general notebook - which is my use case to replace Gnotes.

**Comment by vHanda** [comment]
Hey Darwin.

Thanks for reaching out.

I had originally planned this app just as an alternative to other Journalling apps, but it seems like mots of the users and using it more for note taking. And I also would like to move away from Google Keep.

Do you have any suggestions on how I could provide different document naming? In terms of the interface.

**Comment by DarwinJS** [comment]
You could simply default it to the same as now, but have an edit control to allow me to change it?
That would preserve the value as a journal?  The downside is that it becomes more "hidden" that it can be used for pure notes - so maybe when I hit "new item" it defaults the name to the current, but places my cursor ready to edit name.

Or maybe a setting for "Journal vs Notes" because I can see how with journal mode people don't necessarily want a new document if they edit multiple times a day?

Eventually, pure "notes" users will ask for folders - so maybe backlog that right away?

FYI I am also doing IT Operations checklists on desktops using Typora and CopyQ (both multiplatform and work on Windows, Mac, Linux).

If you ever had a visual rendering mode that allowed one to checkoff boxes - that would be the bomb.

In my case, checkboxes aren't enough cause you can't combine them with numeric bullets (standard rending makes the bullet disappear even if numeric).  So we use CopyQ to insert time/date stamps and todo stamps like these (render background color in typora with style commands).  A simple text macro capacbility with a formatable date stamp function would give the same.

<span style="background-color:salmon;border: 1px">**[SKIPPED 07/28 @ 07:45 SKIP_REASON_HERE]**</span> 

<span style="background-color:red;border: 1px">**[RECORD RESULT HERE]**</span> 

<span style="background-color:lightblue;border: 1px">**[TODO]**</span> 

<span style="background-color:lightgreen;border: 1px">**[DONE 07/28 @ 07:45]**</span>

**Comment by DarwinJS** [comment]
Another idea would be to ensure your embedded git client is re-usable by other projects - then other editors could use this convenient feature.  Would be nice to have a little control over how often it commits, either "sync frequency" in minutes or even "every edit", "every hour", "every day"

**Comment by vHanda** [comment]
> You could simply default it to the same as now, but have an edit control to allow me to change it?
> That would preserve the value as a journal? The downside is that it becomes more "hidden" that it can be used for pure notes - so maybe when I hit "new item" it defaults the name to the current, but places my cursor ready to edit name.
> 

Maybe it would make sense to allow you to setup multiple 'Journals' each with its own mode. The Journalling mode or Note taking, even in Note taking one could want multiple different ways of viewing the notes. Not sure.

> Or maybe a setting for "Journal vs Notes" because I can see how with journal mode people don't necessarily want a new document if they edit multiple times a day?
> 
> Eventually, pure "notes" users will ask for folders - so maybe backlog that right away?

Yup. That's high in my list of priorities.

> 
> FYI I am also doing IT Operations checklists on desktops using Typora and CopyQ (both multiplatform and work on Windows, Mac, Linux).
> 
> If you ever had a visual rendering mode that allowed one to checkoff boxes - that would be the bomb.
>

Heh. It's a large part of how I use Google Keep, so I definitely want to add something basic like this.
 
> In my case, checkboxes aren't enough cause you can't combine them with numeric bullets (standard rending makes the bullet disappear even if numeric). So we use CopyQ to insert time/date stamps and todo stamps like these (render background color in typora with style commands). A simple text macro capacbility with a formatable date stamp function would give the same.
> 
> **[SKIPPED 07/28 @ 07:45 SKIP_REASON_HERE]**
> 
> **[RECORD RESULT HERE]**
> 
> **[TODO]**
> 
> **[DONE 07/28 @ 07:45]**

I see. I was planning on just supporting the markdown syntax for todo items -
```
[ ] Item to be done
[x] It done
```

That way it would be fairly standard. I'm not sure about a more advanced system.

**Comment by vHanda** [comment]
> Another idea would be to ensure your embedded git client is re-usable by other projects - then other editors could use this convenient feature. Would be nice to have a little control over how often it commits, either "sync frequency" in minutes or even "every edit", "every hour", "every day"

Right now it commits after each change that is made. Is that too much?

Regarding sync frequency, I see your point. Currently, it tries to sync immediately. Could you please file another bug regarding this? That way it will not get lost.

**Comment by DarwinJS** [comment]
That would be sufficient.

FYI Nextcloud Notes seems to be open source and have a visual rendering mode: https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes.

FYI - Typora is not open source, but many folks are hoping for mobile clients: https://github.com/typora/typora-issues/issues/525

**Comment by DarwinJS** [comment]
FYI - somehow it's hard to find your app on google play with "git markdown" - I'm not sure how one does SEO for that.  Also "git markdown android" on the web as well.  I was looking for exactly your solution, but hard to find.  I know that you don't have hours a week for SEO - just noting that the category is both uncrowded and hard to find solutions in.

**Comment by thesofakillers** [comment]
Hi @vHanda, thanks so much for this project! 
I noticed that you removed this from your backlog. 
I also see that this is a "coming-soon" feature listed in the pro features in the app. 
Do you still intend to allow users to have multiple repositories (and hence multiple journals)? 
Thank you!

**Comment by vHanda** [comment]
Yup. I'm refactoring the settings right now, and after that I plan to tackle multiple repos.

**Comment by vHanda** [comment]
Closing this as we now have multiple repos, and each can have a different view.
