### ISSUE TITLE
Checklist format not consistent with most editors

### ISSUE THREAD

**Issue by groovenectar** [GitJournal/GitJournal#71]
GitJournal's format:

```
[ ] Item 1
[ ] Item 2
[ ] Item 3
```

Common Markdown format:

```
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3
```

For example, pasting those two in the GitHub editor results in:

[ ] Item 1
[ ] Item 2
[ ] Item 3

- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

From the GitHub blog: https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/

Also tested in a few desktop Markdown editors. I would like to try working on this unless someone else gets to it first... I might also want to add a detection of whether a document contains *only* a checklist, and use the checklist view by default (perhaps via setting)

**Comment by vHanda** [comment]
Hey. Your proposal sounds great. Please let me know if I can help - you can email me or message me on Telegram (vHanda).

Regarding detecting if the document only contains checkboxes - I was thinking of a simpler solution where we store the editor used with each note (if it isn't the default). What do you think?

**Comment by groovenectar** [comment]
> Regarding detecting if the document only contains checkboxes - I was thinking of a simpler solution where we store the editor used with each note (if it isn't the default). What do you think?

I think that's a cool idea as well...

```
---
title: The title of the document
type: Checklist
---
```

And I wonder if the checklist editor could actually be integrated into the document itself... to where it would become a global option of "enable checklist editor"... so any checklists in the document use the editor, and the other markdown still displays normally.. I almost got fully up and running with a dev environment two nights ago with only a couple kinks.. Talk soon!

**Comment by mipro98** [comment]
So as far as I understand the checklist-detection to use the right editor is now implemented? But would it be possible to change the syntax the checklists use from

```
[ ] item
```
 to

```
- [ ] item 
```

to make it more compatible with other markdown editors/parsers?

**Comment by vHanda** [comment]
Yes. It's something that has been annoying me a lot. I've tried to do this
a few times now and because of the way the markdown parser in dart is
implemented, it's quite challenging.

I think I'm just going to hack around it, and maybe not even parse all of
the markdown, but just go line by line and use a simple regexp.
