### ISSUE TITLE
error when syncing note after modifying it on another device

### ISSUE THREAD

**Issue by maxpiano** [GitJournal/GitJournal#73]
I modified an already existing file inside my gitjournal repository from another device via git push and now when gitournal tries to sync it, I get the following error.
![Screenshot_20200302-171526_GitJournal](https://user-images.githubusercontent.com/8249085/75695516-78da7580-5caa-11ea-8430-de4b4dd6852f.jpg)

**Comment by vHanda** [comment]
Thanks for reporting this. I'll release a new version within the hour.
