### ISSUE TITLE
gitjournal doesn't push changes

### ISSUE THREAD

**Issue by maxpiano** [GitJournal/GitJournal#76]
since the last update gitjournal doesn't seem to push edits to the selected github repository. when I restart the app, the edits are gone. tried reinstalling.

**Comment by vHanda** [comment]
Could you please use the 'Report a bug' button? It'll send me the debug logs which I can use to further diagnose the issue.

**Comment by jrollins** [comment]
@vHanda I suspect that these issue are because of problems with the git interaction, and i think it would be very useful to view the git log, both for debugging purposes and since there may be things the user can do to clear up the issue.
