### ISSUE TITLE
Get note modified/created metadata from Git

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#78]
Currently the modified/created timestamp is fetched from the YAML metadata. However, it isn't always present and many users prefer to not store a YAML header.

GitJournal should fallback to extract this metadata from the git data.

This is going to require deeper integration with git, so I probably won't get to it until the `dart_git` has the required functionality. Going through libgit2 and the many layers of indirection is too frustrating 

---
> Please vote on this issue with a 👍reaction. It's one of the primary mechanisms used to prioritize issues.

**Comment by jrollins** [comment]
I think this would be a nice simplification, which would allow removing the need for the yaml header.  The first line of the note could double as the title in this case.  This is in fact how [xotes](https://gitlab.com/jrollins/xotes) originally worked.

**Comment by vHanda** [comment]
Definitely. However, I'm still learning towards having the YAML header by default as it allows us to store extra metadata such as Note type and tags.

**Comment by vHanda** [comment]
This task is currently blocked by [packfile format](https://git-scm.com/docs/pack-format) support in [dart-git](https://github.com/GitJournal/dart_git). The moment I implement that, I can then more deeply integrate with Git.

Currently all git operations happen via `Flutter -> Android -> NDK -> Custom-c-lib -> libgit2` or `Flutter -> ios -> Custom-c-lib -> libgit2`. This makes using libgit2 very cumbersome. Hence why I'm slowly working on dart-git.

**Comment by jasonwilliams** [comment]
@vHanda ard you tracking packfile format support support in dart-git? I couldn’t see where upstream this was happening.

If his doesn’t happen would it make sense to do this in flutter for now?

**Comment by vHanda** [comment]
> @vHanda are you tracking packfile format support support in dart-git? I couldn’t see where upstream this was happening.
> 
> If his doesn’t happen would it make sense to do this in flutter for now?

It's done in dart-git and been tested quite a bit. It "just" needs to be incorporated in GitJournal.

My hands are somewhat injured so I now have to take many breaks in between coding (when I feel up to it), hence the slow progress last month and this one.

I'll write a November recap tomorrow and maybe elaborate (I'm not sure how much detail I want to reveal)

**Comment by nbuergi** [comment]
Any progress on this? If not, as a potentially easier to implement alternative (or maybe just as workaround until a better solution exists): Why not just use the modified date of the note file in the local system storage? This date also reflects last modified and is presumably very easy to access, I would assume.

Btw thanks for a great and super helpful app!

**Comment by vHanda** [comment]
> Any progress on this? If not, as a potentially easier to implement alternative (or maybe just as workaround until a better solution exists): Why not just use the modified date of the note file in the local system storage? This date also reflects last modified and is presumably very easy to access, I would assume.
> 
> Btw thanks for a great and super helpful app!

Sadly, not yet. The workaround you suggested is implemented, but it's flakey.

My rough priority list is -
* Improve App Marketing Material (icon, app store images, etc)
* Autocompletion for tags / wiki links (It's the most voted feature)
* This

**Comment by bs** [comment]
Really looking forward to this as well! Currently, sorting isn’t working as some have frontmatter (dendron) and some don’t.

Thanks for your work!
