### ISSUE TITLE
Enable Configuration of Sync / Push Frequency + Add Pull 

### ISSUE THREAD

**Issue by DarwinJS** [GitJournal/GitJournal#8]
Allow a setting for how often sync should be done.  At a minimum keep supporting "after every edit" but allow it to be made longer in either minutes or categories.
- After Every Edit
- X times per Y (where Y is "Hour" or "Day" ?)

You might also want to let this mode do "pulls" in case I am adding to the repo with other utilities?  Maybe you already do that?

Or maybe pull needs it's own schedule?

**Comment by bmschwa** [comment]
Not a huge one for me, but there is an [AWS free tier limit for code commit ](https://aws.amazon.com/codecommit/pricing/) that I'd prefer to avoid.
