### ISSUE TITLE
remove configurability of "modified" yaml header field name

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#82]
I see no point in having the name of this field be configurable, and allowing it to be changed makes things unnecessarily complicated for other apps that are trying to build gitjournal compatibility.

**Comment by vHanda** [comment]
The reason it was added was that a certain portion of the users use this for managing static websites - Jekyll / Hugo / Gatsby. Each of these use a different way of indicating when a markdown file has been last modified.

**Comment by vHanda** [comment]
Hey. I'm going to close this bug as it's a feature some users requested. I'd like GitJournal to be extremely configurable as user has very different preferences.

**Comment by jrollins** [comment]
Fair.  It didn't occur to me that this might have been for compatibility with other apps.
