### ISSUE TITLE
filename "ISO8601" without timestamp should be UTC, not local time

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#83]
If a time stamp does not include a time zone, then there is ambiguity of time, unless a reference time is assumed.  ISO time stamps without time zone should therefore always be assumed to be UTC.  Thanks!

**Comment by vHanda** [comment]
The ISO 8601 spec specifies that if a timezone is not specified it should be interpreted as local time - https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators . Therefore, I'm not keen to go against this behaviour - It's also what Dart internally does.
