### ISSUE TITLE
public key isn't work in some websites

### ISSUE THREAD

**Issue by AlexiFeng** [GitJournal/GitJournal#87]
Use GitJournal to generate the public key(Android and iOS) but some websites can't identify it(Format Error).
**When I delete the datetime at the end of pk,it can be identified.**
I used ssh on win10 to generate the pk and it can be identified in anywhere.

**Comment by vHanda** [comment]
Hi. Thanks for the bug report.

If you change the space before the date to a `-` does it then work?

**Comment by AlexiFeng** [comment]
Well,I delete the space before the date and it works,cool.

**Comment by vHanda** [comment]
Let me make that the default.
