### ISSUE TITLE
Unable to enable or restore purchase of Pro Mode on Android

### ISSUE THREAD

**Issue by ravenscroftj** [GitJournal/GitJournal#894]
I am running yesterday's GitJournal 1.86 release on android 13.

I recently subscribed to the £4/mo pro tier but I saw in commit  b7dd2042b6fe0ffe178562e0e644bc4e2d4f022f that you will no longer be supporting subscriptions. Even since I started using the app around a week ago I can see that its something I will get a lot of value out of so I decided to take the plunge and pay the full one-off fee.

Unfortunately I am still locked out of Pro features and clicking restore pro mode does not currently do anything.

Just to confirm I did the following:

1. Open app
2. click on add a repo to bring up "Pro" payment prompt
3. paid for pro using google play
4. nothing happened

I tried again running adb logcat:

1. Open app
2. click on add a repo to bring up "Pro" prompt 
3. click restore pro 
4. nothing happened

Looking in logcat I see the following when I click on "restore pro"

```
01-20 07:18:55.904 12948 28285 I Finsky  : [526] hmy.a(14): io.gitjournal.gitjournal: Account determined from installer data - [somehash]

01-20 07:18:55.904 12948 28285 I Finsky  : [526] hmy.a(61): Billing preferred account via installer for io.gitjournal.gitjournal: [thesamehash]
```

Anything you can do would be great, I'm happy to support this work but at the moment I'm locked out of some of the most useful features which is quite frustrating.

**Comment by vHanda** [comment]
Hello.

Could you please email me at vhanda@gitjournal.io ? I can provide a workaround.

Supporting subscriptions is too much work going forward. I'm going to be switching GitJournal to a one time payment model, as I can see that I'm developing far less features these days. My plan is to give everyone with the subscription the full version of GitJournal, regardless of how many months they have paid.
