### ISSUE TITLE
Provide build instructions

### ISSUE THREAD

**Issue by philippeowagner** [GitJournal/GitJournal#9]
Would be nice if you could provide build instructions. Thanks.

**Comment by k4biri** [comment]
Would be much nicer if you could also provide build instructions for iOS, too! 👍

**Comment by vHanda** [comment]
> Would be much nicer if you could also provide build instructions for iOS, too! 👍

The build process in iOS is currently really complicated, and I haven't even managed to automate it enough to put in the CI. I have to run it manually from my computer each time :(

This is the problem I'm stuck at - https://stackoverflow.com/questions/63072231/flutter-ios-plugin-with-custom-frameworks - in case you know how to solve it.
