### ISSUE TITLE
Text error in sort order selection

### ISSUE THREAD

**Issue by ThomUK** [GitJournal/GitJournal#910]
Very minor, but the option text says Descending/ Descending, but should probably be Ascending/Descending.

The actual sorting works as expected, just the text is confusing.

![Screenshot_20230326-202337.png](https://user-images.githubusercontent.com/10871342/227799563-451cceec-5bdd-4090-b652-f85b951f9e7a.png)

**Comment by gantanikhilraj** [comment]
hey @ThomUK, I would like to fix this issue. Please assign it to me.

**Comment by ThomUK** [comment]
Hey @gantanikhilraj, I can't do that as I'm not a member of the project. Perhaps a PR to the owner would be accepted...

**Comment by clach04** [comment]
I was just about to log  a bug for then then saw some already had done so.

![image](https://github.com/GitJournal/GitJournal/assets/424032/d1046541-aa13-4f8c-9454-d76102cf2266)

@gantanikhilraj did you get anywhere with this? I took a quick search through translations and text looks fine there.

**Comment by vHanda** [comment]
Fixed about a month ago.

Thanks for reporting it.
