### ISSUE TITLE
Will this be in F-Droid?

### ISSUE THREAD

**Issue by mofosyne** [GitJournal/GitJournal#911]
Understandable if it is too much work, but just wondering if it will be in the opensource appstore F-droid repository.

**Comment by AudunVN** [comment]
It has a repo you can add already: https://gitjournal.io/fdroid_how_to/

**Comment by quantenzitrone** [comment]
While having a 3rd-Party F-Droid Repo is acceptable, for security reasons I would prefer if GitJournal was in the official F-Droid repo.

**Comment by vHanda** [comment]
Closing this as this isn't a bug.

I have no immediate plans to move to F-Droid as that involves not using Google Play for payment and integrating a third party payment provider, which isn't a small task. Eventually, when I get to it, then I might put it in the official F-Droid repo, though in general, I much prefer having a custom repo where I have more control over the distribution.
