### ISSUE TITLE
Graph view is not visible in new versions

### ISSUE THREAD

**Issue by SebastianoReginiUniba** [GitJournal/GitJournal#913]
Hi,
I've noticed that the experimental features "Graph View" doesn't work in versions above the 1.7x.x

It was a great idea to add this feature, and it's a pity that it no longer works.

---
### Description of the issue
When the feature is activated, if opened will return an empty screen (black screen with dark theme, ora white in case of light theme).
It was tested to work both with access to GitHub and without, also two different versions of Android (version 7 and version 13) were used, but in each of these cases the graph does not appear.
Once tested with version 1.75 of the application, the graph appeared.

**Comment by vHanda** [comment]
Closing this as WONTFIX.

Sorry, while I liked the idea of implementing the Graph View, it just isn't going to happen. In fact, I'm streamlining GitJournal to remove half-done features.
