### ISSUE TITLE
cmake error on linux build

### ISSUE THREAD

**Issue by carnotweat** [GitJournal/GitJournal#916]
I am on nixos
nix-shell -p gtk3 pkgconfig
cd ~/linuxdir 
cmake .
CMake Error at flutter/CMakeLists.txt:6 (include):
  include could not find requested file:

    /home/dev/clone/GitJournal/linux/flutter/ephemeral/generated_config.cmake

CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/sentry_flutter/linux" which is not an
  existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:73 (include)

CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux" which is not
  an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:73 (include)

**Comment by vHanda** [comment]
I don't plan to support a linux app anymore. I'd never really finished it, but it's very clear that just having a Android + iOS version is enough work.

I might release a web version later, but I have no plans of Windows / MacOS / Linux support.
