### ISSUE TITLE
Restore Pro Subscription

### ISSUE THREAD

**Issue by hgad** [GitJournal/GitJournal#917]
Hi,

I'm unable to restore my pro subscription from the app. Can you please help?

Thanks,
Haitham

**Comment by vHanda** [comment]
Could you please email me a copy of the receipt?

**Comment by hgad** [comment]
Here:

![image](https://github.com/GitJournal/GitJournal/assets/469577/072eb4c5-2ecb-4a4c-9d7f-9dcf87418060)

**Comment by hgad** [comment]
Oh, I hadn't realized this was a one year subscription. Nevermind then.

**Comment by vHanda** [comment]
Please message me privately on - vhanda@gitjournal.io - and I'll provide a way to work around.

I've barely been working on Gitjournal this year, and I've changed it to a one time payment. Id prefer if you didn't pay again.
