### ISSUE TITLE
github: Add tags / releases for all released versions to track app releases

### ISSUE THREAD

**Issue by PRESFIL** [GitJournal/GitJournal#923]
## Summary

Add `tags` / `releases` so that the moment of the release of the new version of the
application is clear. 

## Details

Some users subscribe to email notifications, some use GitHub's RSS, some can use
`releases` / `tags` with `git` or Obtanium to update application from GitHub releases
(if you will attach the collected apk's to GitHub releases). But the base for all this is
git tags. Now, after the fact that the applications were first published in PlayMarket,
then in f-droid, then in custom f-droid repository, and once on GitHub, (have I listed
everything in the right order?) it is very difficult to figure out what happend.

In addition, it is now very difficult to find past releases of previous versions
from the history of the repository.

**Comment by vHanda** [comment]
Understood. I'll try to be more diligent in the future!

I have a new release planned fairly soon.
