### ISSUE TITLE
Android error Exception: Git Merge Bindings failed

### ISSUE THREAD

**Issue by clach04** [GitJournal/GitJournal#934]
I got the error `Exception: Git Merge Bindings failed` when attempting to sync:

![Screenshot_20231116-084917_GitJournal~01](https://github.com/GitJournal/GitJournal/assets/424032/4ef5ae10-17ca-40cb-9247-4ca747c81745)

Refreshing does NOT make a difference :-( I do not now how to recreate this.

As an experiment (after seeing this error) I enabled Dart git and Dart merge under Experiment and sync worked again. Although I'm not sure of the implications of enabling these options

**Comment by vHanda** [comment]
Sorry. I've noticed that as well. I'm just going to enable the dart-git bindings by default.

It's fairely stable.

**Comment by clach04** [comment]
Just had an error:

    Exception: Stop?

Similar to above, never succeeded... So reverted back to bindings disabled both dart options for git) and sync worked.

**Comment by clach04** [comment]
It is possible the errors were triggered by having poor network connection during pull/push, however I can;t reproduce this at will. Once one of the errors happens, it persists until switching git back end.
