### ISSUE TITLE
Git Journal won't delete files when files are deleted from remote

### ISSUE THREAD

**Issue by kshensovato** [GitJournal/GitJournal#956]
I'm using Git Journal to sync with Obsidian (using Obsidian Git plugin) on desktop.
If I delete files from Obsidian, after the file deletion is pushed to GitHub, those files still show up in Git Journal. They are not deleted on Git Journal side.

**Comment by adambro** [comment]
Yeah, I've got similar issue. In my case I've moved files `git mv` across directories. GitJournal restored the original notes, so I ended up with duplicate notes: the new one with my additions and the old contents (before move).

**Comment by seadowg** [comment]
Having the same problem. Currently I need to remove/readd the repository to honour deletes from the remote.

**Comment by whirledsol** [comment]
Also experiencing this as of late.
Would `git rm <file>` work to remove the original files?

**Comment by seadowg** [comment]
I'm guessing this is related to #962 and #957

**Comment by vHanda** [comment]
Closing this in favor of https://github.com/GitJournal/GitJournal/issues/962

I see what the issue is and how to fix it.
