### ISSUE TITLE
Yaml frontmatter Hugo

### ISSUE THREAD

**Issue by henrysheehy** [GitJournal/GitJournal#961]
I’d like to kindly request extensible front matter to integrate with Hugo, if possible?
Presently, one can change it manually, of course, but it would be great if there was some autocompletion (perhaps, even like Notion), so that users unfamiliar with Hugo receive hints in the front matter. 
Thank you!

**Comment by vHanda** [comment]
Sorry. I'm going to close this.

I don't want to add special features for Hugo, especially as I don't even use Hugo any more. If you have ideas of feature requests that can be helpful for all CMSs / Note Taking / Journaling, I'd be very interested.
