### ISSUE TITLE
Unreadable fields / Theme colours

### ISSUE THREAD

**Issue by ScaredyCat** [GitJournal/GitJournal#966]
In Dark mode or System Default on a dark mode selected device some fields are very difficult to read with black text on a dark background. I think the attached image shows this quite well. Seems that the background should be green rather than the dark grey or at least lighter text as per the "Git Remote Settings" screen. Personally I'd prefer the green as it seems to make the text more obviously 'clickable'.

![visibility](https://github.com/GitJournal/GitJournal/assets/168872/ec9991c8-4432-4554-9cff-3ad96087a1d0)

**Comment by vHanda** [comment]
Closing in favor of https://github.com/GitJournal/GitJournal/issues/612
