### ISSUE TITLE
gitjournal keeps restoring deleted files

### ISSUE THREAD

**Issue by jrollins** [GitJournal/GitJournal#970]
My gitjournal app (android 1.87.0+3768) is in a state where it keeps restoring files that I am deleting from the remote git repo from another host.  Here is the behavior I'm seeing:

0. On a separate host (host A) I delete files from the git repo, commit the changes to the repo, and push the changes to the remote git host.
1. On the gitjournal app I then update/sync from the git remote.  Presumably this should pull in the change that removes the deleted files.
2. Initially there appears to be no change on the git remote, and if I do a git pull on host A I do not see the files restored.
3. Then I create a new note on the app, and sync those changes to the git remote.
4. If I now do a pull on host A, I see a single new commit in the git repo that inclues the newly created note, as well as all the restored deleted files.

So clearly somehow gitjournal is not correctly processing the commits that delete files, and is not actually deleting the files in the apps working directory, allowing those files to be "re-added" when a new note is created.   Presumably gitjournal is running the equivalent of "git add -A" when new files are create, which is then re-adding the old files that were not properly deleted from the apps working tree.

**Comment by TheTurtleIsHungry** [comment]
Can confirm seeing this on iOS version of the app

**Comment by TheTurtleIsHungry** [comment]
It feels like #962 and #957 are related to this. Maybe the same underlying issue causing this? They are all related to how to deal with deleted files

**Comment by whirledsol** [comment]
BUMP

**Comment by vHanda** [comment]
Closing for #962
