### ISSUE TITLE
YYYY-MM-DD Date format

### ISSUE THREAD

**Issue by cvladan** [GitJournal/GitJournal#972]
I'm delighted that GitJournal supports metadata YAML Frontmatter. However, the problem is that I use the "yyyy-mm-dd" format for date, which properly works in Hugo static site generator. But here, it's not recognized; it must be in Unix Timestamp or ISO-8601 format. Is it possible to add/recognize this date format?

**Comment by whirledsol** [comment]
As an ISO-8601 supporter, I approve this message. Maybe in Pro?

**Comment by whirledsol** [comment]
In Android at least, going to Storage & File Formats > Note Metadata Settings allows the timestamp to be adjusted to ISO-8601.

Could this be marked as closed or is OP asking for a a timestamp magnitude of just the date "yyyy-mm-dd"?

**Comment by vHanda** [comment]
Thank you @whirledsol

**Comment by cvladan** [comment]
I am aware of the ISO-8601 format, but I use a date format without time info, seconds and minutes, just the date, and it works fine in Hugo for example... but not in GitJournal 😞

**Comment by vHanda** [comment]
I see the option for it in 'Settings -> Storage -> New Note Filename'. There is an option for yyyy-mm-dd. Is that not what you want?

**Comment by cvladan** [comment]
Thanks! But no, that doesn't solve my problem. That's about the filename.

I need it in YAML frontmatter as I already have a huge number of files having "date: YYYY-MM-DD" in frontmatter.

**Comment by vHanda** [comment]
Ah. Understood.
