### ISSUE TITLE
"Setup git host" stuck on cloning phase

### ISSUE THREAD

**Issue by chrg127** [GitJournal/GitJournal#974]
Setting up a git host (using the "Setup git host" button), using the GitHub provider, and using "Setup automatically" always leads me to a "Cloning" screen that never finishes. I'm using an existing, private repo. I've noticed I can authorize GitJournal correctly, and it also added a deploy key to the repo as well. The repo is very tiny, it shouldn't take very long to clone (and yet I waited up to 5 minutes before giving up).
EDIT: I'm not sure, but it appears I get stuck on cloning no matter the method I use.

**Comment by metasyn** [comment]
Same here, using a custom git provider. I tried uninstalling and reinstalling the app just in case, to no avail. Version 1.88.0

**Comment by apprehensions** [comment]
Can reproduce when using Codeberg.

**Comment by vHanda** [comment]
Closing in favor of https://github.com/GitJournal/GitJournal/issues/953
