### ISSUE TITLE
Default folder for new notes

### ISSUE THREAD

**Issue by roadmanict** [GitJournal/GitJournal#975]
Thanks for creating this app.

I would love the option to configure a default folder to save new notes.

**Comment by vHanda** [comment]
It's there in Settings -> Storage -> Default Folder for new notes.

Would adding a search functionality in the settings help?

**Comment by roadmanict** [comment]
Hey, maybe it would help, but this seems like a logical place to put it, I just completely overlooked the Storage settings.

Thanks for taking the time to help!
