### ISSUE TITLE
notes in view mode by default

### ISSUE THREAD

**Issue by adelinacastelao** [GitJournal/GitJournal#98]
The possibility of when opening a note (markdown editor), by default open in view mode, not edit mode.
I understand this was once the default behaviour.
If not by default, then possible by option in app configuration.

Thanks

**Comment by vHanda** [comment]
I rather not have it by default. But it definitely should be configurable. I'll try to do it today :)

**Comment by ataliba** [comment]
Thanks, 

it's good :-)
